### ISSUE TITLE
System Error when running Ganache 2.3.0 on win32

### ISSUE THREAD

**Issue by WJY996** [trufflesuite/ganache#1730] opened 2020-04-17 15:34 UTC
PLATFORM: win32
GANACHE VERSION: 2.3.0

EXCEPTION:
```
Error: connection not open
    at WebsocketProvider.send (D:\Software\Ganache\resources\static\node\node_modules\web3-providers-ws\src\index.js:282:18)
    at Timeout._onTimeout (D:\Software\Ganache\resources\static\node\node_modules\web3-providers-ws\src\index.js:267:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by wbt** [comment] 2020-05-22 22:34
Not sure the "windows" tag fits; it's [observed on darwin too](https://github.com/trufflesuite/ganache/issues/1735).

**Comment by davidmurdoch** [comment] 2020-10-28 18:14
closing as duplicate of https://github.com/trufflesuite/ganache/issues/2039

**Closed by davidmurdoch** 2020-10-28 18:14 UTC
Labels: Ethereum, bug, windows
