### ISSUE TITLE
System Error when running Ganache 2.1.0 on win32

### ISSUE THREAD

**Issue by gcill** [trufflesuite/ganache#1651] opened 2020-02-29 09:01 UTC
i just click on transaction in the transaction tab and then issue occur

PLATFORM: win32
GANACHE VERSION: 2.1.0

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 2736$ of contract$ EternalStorage (ID 990)
    at vars.concat.linearizedBaseContractsFromBase.map (C:\Program Files\WindowsApps\Ganache_2.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:158:19)
    at Array.map (native)
    at allocateContract (C:\Program Files\WindowsApps\Ganache_2.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:155:61)
    at Object.getStorageAllocations (C:\Program Files\WindowsApps\Ganache_2.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:113:47)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\WindowsApps\Ganache_2.1.0.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.1.0) with initial configuration: {"gasLimit":8000000,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":8545,"network_id":5777,"default_balance_ether":500,"total_accounts":5,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"C:\\Users\\cchay\\AppData\\Roaming\\Ganache\\workspaces\\kittyToken\\chaindata"}
T+808ms: Ganache started successfully!
T+808ms: Waiting for requests...
T+871ms: eth_getCode
T+926ms: eth_subscribe
T+1002ms: eth_getLogs
T+1057ms: eth_subscribe
T+1109ms: eth_getCode
T+1182ms: eth_getCode
T+1243ms: eth_getCode
T+1295ms: eth_getCode
T+1354ms: eth_getCode
T+679773ms: eth_call
T+679855ms: eth_call
T+679952ms: eth_call
T+680090ms: eth_call
T+680168ms: eth_estimateGas
T+680229ms: eth_estimateGas
T+680313ms: eth_getTransactionCount
T+680400ms: eth_getTransactionCount
T+680549ms: eth_sendRawTransaction
T+680606ms: eth_sendRawTransaction
T+682447ms:   Transaction: 0xdf8b434972bb381e80c651d904b04a9493fd8bbfe3bf3ad524f7e00a3b29919f
T+682495ms:   Gas usage: 46426
T+682495ms:   Block Number: 74
T+682546ms:   Block Time: Sat Feb 29 2020 15:57:58 GMT+0700 (SE Asia Standard Time)
T+682596ms: eth_getTransactionReceipt
T+682655ms: eth_getBlockByNumber
T+694260ms: eth_call
T+694333ms: eth_call
T+694402ms: eth_call
T+694467ms: eth_call
T+694549ms: eth_estimateGas
T+694626ms: eth_getTransactionCount
T+694754ms: eth_sendRawTransaction
T+696656ms:   Transaction: 0x175ecc7c45b8a2cefe1d7ac5d06b477829616aeceb275f166ac2735a4b85797d
T+696656ms:   Gas usage: 204551
T+696656ms:   Block Number: 75
T+696704ms:   Block Time: Sat Feb 29 2020 15:58:13 GMT+0700 (SE Asia Standard Time)
T+696764ms: eth_getBlockByNumber
T+696837ms: eth_getTransactionReceipt
T+704867ms: eth_call
T+704940ms: eth_call
T+705001ms: eth_call
T+705049ms: eth_call
T+741537ms: net_version
T+741654ms: eth_unsubscribe
T+741702ms: eth_unsubscribe
T+741760ms: eth_unsubscribe
T+741807ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:18
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1333

**Closed by davidmurdoch** 2020-10-28 18:18 UTC
