### ISSUE TITLE
Issues with Running via Terminal

### ISSUE THREAD

**Issue by haarts** [trufflesuite/ganache#1061] opened 2018-12-28 11:05 UTC
After downloading version 1.2.2 and changing the permissions with `chmod +x <file>`, running it crashes immediately with:
```
$ ./ganache-1.2.2-x86_64.AppImage 
/tmp/.mount_ganachWuPX7U/Ganache: symbol lookup error: /tmp/.mount_ganachWuPX7U/Ganache: undefined symbol: _ZN12v8_inspector8protocol8Debugger3API6Paused10ReasonEnum3XHRE
```

The same error is thrown with version 2.0.0.

## Your Environment

* Version used: 1.2.2 and 2.0.0-beta
* Operating System and version: Ubuntu 18.10

**Comment by seesemichaelj** [comment] 2019-01-03 20:06
Thanks @haarts for reporting this! I'm spinning up a clean 18.10 instance to verify and see what the root cause is.

**Comment by seesemichaelj** [comment] 2019-01-03 20:23
@haarts Unfortunately, I can't reproduce your error either with 1.2.2 or 2.0.0-beta.1 AppImage files on the Github Releases page.

I used an Ubuntu Desktop 18.10 ISO image (from here: http://releases.ubuntu.com/cosmic/). I just used the "Live CD" environment to ensure a clean setup.

Is there any other information you can give me to help reproduce the problem?

Thanks!!

**Comment by haarts** [comment] 2019-01-03 20:42
Well. I've found something more with the magic `LD_DEBUG` environment variable. Do `export LD_DEBUG=symbols` to yield this output: https://gist.github.com/haarts/41b59f748da6c064b91a7e26be051170. I'm curious which files are searched at your system.

**Comment by seesemichaelj** [comment] 2019-01-03 20:43
I guess a couple of potential things you can try:
- Do older versions (i.e. [1.1.0](https://github.com/trufflesuite/ganache/releases/tag/v1.1.0)) of Ganache work?
- This is always repeatable?
- Can you try double clicking the icon in the file explorer after adding execute permissions?
- What are the `sha256sum`s of the files (i.e. `sha256sum ./ganache-1.2.2-x86_64.AppImage`)?
  - I get:
```
$ sha256sum ./\*anache\*AppImage
e2512f9bf703e4a049a4f78b5325fc6d67e4386bab53905cf1a4e2f07bdec8e4  ganache-1.2.2-x86_64.AppImage
96ec91ce0b9cec0c8207733d3d79018a8306259a833d49357c6f87c2dd3f52d0  Ganache-2.0.0-beta.1.AppImage
```


Just shooting from the dark, my best guess is there is something installed on your system which is conflicting with the setup. (Now looking at your latest comment, could definitely be on the right track, going to give that a shot)

**Comment by haarts** [comment] 2019-01-03 20:55
- Version 1.1.0 doesn't work either.
- It is always repeatable.
- .... I'll be damned. That works... 
- the shas are:

```
57bbd55bccf2f74462e89f8096f550335bc748b039f068ed7b48584084ad7dfb  ganache-1.1.0-x86_64.AppImage
e2512f9bf703e4a049a4f78b5325fc6d67e4386bab53905cf1a4e2f07bdec8e4  ganache-1.2.2-x86_64.AppImage
96ec91ce0b9cec0c8207733d3d79018a8306259a833d49357c6f87c2dd3f52d0  Ganache-2.0.0-beta.1.AppImage
```

Soooo. Fixed?

**Comment by seesemichaelj** [comment] 2019-01-03 20:57
Now that double clicking works, try opening via terminal again? Some weird voodoo stuff going on here lol

**Comment by seesemichaelj** [comment] 2019-01-03 20:59
I actually get a different error (now that I've installed 18.10 instead of the live cd) about not being able to find `libgtk-x11-2.0.so.0`

**Comment by haarts** [comment] 2019-01-03 21:05
Terminal still does't work. `libgtk2.0-common` is already installed. Perhaps some sort of look up path is different... Can you start via the terminal?

**Comment by seesemichaelj** [comment] 2019-01-03 21:10
I can start via terminal, but it hangs before anything is loaded on the screen (just the background color), without crash or error. Double clicking works :joy:

I guess that's the work around for now?

Since I can reproduce similar weird behavior when running via terminal, I'm going to keep this one open. Thanks for helping!

**Comment by seesemichaelj** [comment] 2019-01-04 20:11
Not gonna lie. After a restart of my 18.10 VM, I no longer can reproduce the problem. I'm guessing my issue was not restarting after installing libgtk (or running a new process of `bash`).

Either way, I'm going to close this as can't reproduce. There's something in your environment that must be messing stuff up. Sorry! At least you have a workaround :)

**Closed by seesemichaelj** 2019-01-04 20:11 UTC
Labels: bug, linux, priority-medium
