### ISSUE TITLE
CONTRACTS tab - Decoding Error when running Ganache 2.0.2 on linux

### ISSUE THREAD

**Issue by SvenMeyer** [trufflesuite/ganache#1623] opened 2020-02-13 05:40 UTC
Ganache could not decode a standard OpenZeppelin ERC20 contract on the 'CONTRACTS' tab.

PLATFORM: linux
GANACHE VERSION: 2.0.2

```
pragma solidity ^0.5.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/token/ERC20/ERC20Detailed.sol";
import "@openzeppelin/contracts/token/ERC20/ERC20Mintable.sol";
import "@openzeppelin/contracts/token/ERC20/ERC20Burnable.sol";

contract FECoin is ERC20, ERC20Detailed, ERC20Mintable, ERC20Burnable {
    uint8   public constant DECIMALS = 18;
    uint256 public constant INITIAL_SUPPLY = 0;

    /**
     * @dev Constructor that gives msg.sender all of existing tokens.
     */

    constructor () public ERC20Detailed("FECoin-Type1", "FEC1", DECIMALS) {
        _mint(msg.sender, INITIAL_SUPPLY);
    }

}
```

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 357$ of contract$ FECoin (ID 35)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:158:19)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:155:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:113:47)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:18
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1333

**Closed by davidmurdoch** 2020-10-28 18:18 UTC
