### ISSUE TITLE
WorkspaceManager: System Error when running Ganache 2.3.0-beta.1 on linux

### ISSUE THREAD

**Issue by zdeheshti** [trufflesuite/ganache#1585] opened 2020-01-01 17:13 UTC
i just download ganache 2.3.0 beta version and try to run it, but i got this error.
Error: dest already exists.
    at doRename (/node_modules/fs-extra/lib/move-sync/move-sync.js:25:34)
    at Object.moveSync (/node_modules/fs-extra/lib/move-sync/move-sync.js:17:10)
    at map (/webpack:/src/main/types/workspaces/WorkspaceManager.js:32:17)
    at Array.map (<anonymous>)
    at et.enumerateWorkspaces (/webpack:/src/main/types/workspaces/WorkspaceManager.js:21:10)
    at et.bootstrap (/webpack:/src/main/types/workspaces/WorkspaceManager.js:47:10)
    at EventEmitter.<anonymous> (/webpack:/src/main/index.js:391:22)
```

**Comment by davidmurdoch** [comment] 2020-01-13 17:43
Hm, interesting. This is happening as part of the migration logic to a new version of Ganache when installed via the appx (the old version couldn't handle signing certificate name changes automatically).

Are you able to reproduce this error on start up? Or did it happen just on the one time. If you open the beta are all your old workspaces still there? If not, are you old workspaces still available when opening the previous version? (If you didn't uninstall it already, of course).

The way the migration works is that on start up we detect the previous version of ganache, copy its workspaces over to this new version of ganache's workspace directory (this is where it seems to be failing for you), then once everything has been moved, automatically uninstall the original version of ganache.

**Comment by davidmurdoch** [comment] 2020-01-13 22:06
@zdeheshti do you mind letting me know which OS you are running Ganache UI on?

**Comment by davidmurdoch** [comment] 2020-04-11 16:42
Should be fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!

**Closed by davidmurdoch** 2020-04-11 16:42 UTC
Labels: awaiting-response, bug
