### ISSUE TITLE
System Error when running Ganache 2.0.3 on darwin

### ISSUE THREAD

**Issue by le4ker** [trufflesuite/ganache#1351] opened 2019-07-09 23:33 UTC
PLATFORM: darwin
GANACHE VERSION: 2.0.3

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 205$ of contract$ CryptoDeities (ID 37)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:158:19)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:155:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:113:47)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+361110ms: eth_getBlockByNumber
T+363675ms: net_version
T+367112ms: eth_getBlockByNumber
T+370109ms: eth_getBlockByNumber
T+373059ms: eth_blockNumber
T+376111ms: eth_getBlockByNumber
T+379108ms: eth_getBlockByNumber
T+385116ms: eth_getBlockByNumber
T+388163ms: eth_getBlockByNumber
T+390053ms: net_version
T+390153ms: eth_accounts
T+390153ms: eth_getBlockByNumber
T+390153ms: eth_getCode
T+390153ms: eth_getBlockByNumber
T+390184ms: eth_call
T+390221ms: eth_getBlockByNumber
T+390249ms: eth_getCode
T+390314ms: eth_getBlockByNumber
T+390339ms: eth_call
T+390388ms: eth_getBlockByNumber
T+394258ms: eth_accounts
T+394258ms: net_version
T+394258ms: eth_getBlockByNumber
T+394258ms: eth_getBlockByNumber
T+394258ms: net_version
T+394258ms: eth_getBlockByNumber
T+394258ms: eth_estimateGas
T+394258ms: net_version
T+394258ms: eth_blockNumber
T+394258ms: eth_getBlockByNumber
T+394258ms: eth_sendTransaction
T+394258ms:   Transaction: 0x9c20fa2e393b64afc4399fad20194a37351377bedba21030fb5ce43a8cd41fef
T+394258ms:   Contract created: 0xe404b5495f6a9050b976fd9ce411079d6eeae4ed
T+394258ms:   Gas usage: 2507151
T+394258ms:   Block Number: 3
T+394258ms:   Block Time: Wed Jul 10 2019 02:30:04 GMT+0300 (EEST)
T+394258ms: eth_getBlockByNumber
T+394258ms: eth_getTransactionReceipt
T+394258ms: eth_getCode
T+394258ms: eth_getTransactionByHash
T+394258ms: eth_getBlockByNumber
T+394258ms: eth_getBalance
T+394258ms: eth_getBlockByNumber
T+394258ms: eth_getBlockByNumber
T+394258ms: eth_sendTransaction
T+394258ms:   Transaction: 0xda2615793d6841f33fec56574c8dae328f9e0d0015e8c8b077ef0bf187cfb6b4
T+394258ms:   Gas usage: 27023
T+394258ms:   Block Number: 4
T+394258ms:   Block Time: Wed Jul 10 2019 02:30:05 GMT+0300 (EEST)
T+394258ms: eth_getBlockByNumber
T+394258ms: eth_getTransactionReceipt
T+394479ms: eth_blockNumber
T+394507ms: eth_getBlockByNumber
T+397120ms: eth_getBlockByNumber
T+403266ms: eth_getBlockByNumber
T+406270ms: eth_getBlockByNumber
T+407948ms: net_version
T+412274ms: eth_getBlockByNumber
T+413110ms: eth_blockNumber
T+415279ms: eth_getBlockByNumber
T+421305ms: eth_getBlockByNumber
T+423862ms: net_version
T+424310ms: eth_getBlockByNumber
T+430308ms: eth_getBlockByNumber
T+433120ms: eth_blockNumber
T+433309ms: eth_getBlockByNumber
T+439311ms: eth_getBlockByNumber
T+442443ms: eth_getBlockByNumber
T+447906ms: eth_getBlockByNumber
T+450409ms: eth_getBalance
T+450719ms: eth_getTransactionCount
T+450856ms: eth_getBlockByNumber
T+453136ms: eth_blockNumber
T+457121ms: net_version
T+458920ms: eth_getBlockByNumber
T+462524ms: eth_getCode
T+473150ms: eth_blockNumber
T+478615ms: eth_getTransactionCount
T+478650ms: eth_getBlockByNumber
T+484096ms: net_version
T+486704ms: eth_getBlockByNumber
T+493162ms: eth_blockNumber
T+494870ms: eth_getBlockByNumber
T+495800ms: eth_getBalance
T+496268ms: eth_getBlockByNumber
T+499867ms: eth_getBalance
T+500017ms: eth_getTransactionCount
T+500068ms: eth_getBlockByNumber
T+503387ms: eth_blockNumber
T+503469ms: net_version
T+503528ms: eth_getBlockByNumber
T+503671ms: eth_getBlockByNumber
T+503724ms: eth_getBalance
T+503724ms: eth_getBalance
T+503724ms: eth_getBalance
T+503739ms: eth_getBalance
T+508158ms: eth_getBlockByNumber
T+510604ms: net_version
T+516033ms: eth_getCode
T+516103ms: eth_estimateGas
T+521972ms: eth_getTransactionCount
T+522149ms: eth_sendRawTransaction
T+524574ms:   Transaction: 0x52f6ecae5964a031a0ff9738cfc38f527f277465880ff4fdcff3cb6fdf9b2b8d
T+524634ms:   Gas usage: 22489
T+524667ms:   Block Number: 5
T+524685ms:   Block Time: Wed Jul 10 2019 02:32:16 GMT+0300 (EEST)
T+524715ms: eth_getBlockByNumber
T+524761ms: eth_getTransactionByHash
T+524794ms: eth_blockNumber
T+524810ms: eth_getBlockByNumber
T+524834ms: eth_getBlockByNumber
T+524864ms: eth_getTransactionByHash
T+524917ms: eth_getBalance
T+524947ms: eth_getBalance
T+524972ms: eth_getBalance
T+524989ms: eth_getBalance
T+525013ms: eth_getBlockByNumber
T+525030ms: eth_getTransactionReceipt
T+525054ms: eth_getTransactionCount
T+525070ms: eth_getTransactionByHash
T+525093ms: eth_getTransactionByHash
T+525119ms: eth_getTransactionReceipt
T+525145ms: eth_blockNumber
T+530940ms: eth_getBlockByNumber
T+531135ms: net_version
T+538882ms: eth_getBlockByNumber
T+543471ms: eth_blockNumber
T+544332ms: net_version
T+546943ms: eth_getBlockByNumber
T+555951ms: eth_getBlockByNumber
T+563530ms: eth_blockNumber
T+564952ms: eth_getBlockByNumber
T+573962ms: eth_getBlockByNumber
T+583565ms: eth_blockNumber
T+583602ms: eth_getBlockByNumber
T+592832ms: eth_getBlockByNumber
T+601561ms: eth_getBlockByNumber
T+603580ms: eth_blockNumber
T+604465ms: net_version
T+610558ms: eth_getBlockByNumber
T+611532ms: net_version
T+611594ms: eth_unsubscribe
T+611594ms: eth_unsubscribe
T+611620ms: eth_unsubscribe
T+611620ms: eth_unsubscribe
T+611620ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:21
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1470

**Closed by davidmurdoch** 2020-10-28 18:21 UTC
