### ISSUE TITLE
Decoding Error when running Ganache 2.4.0 on win32

### ISSUE THREAD

**Issue by orbitmechanic** [trufflesuite/ganache#2080] opened 2020-10-20 21:19 UTC
Running Solidity 0.7.0.  Multiple inheritance in play.  One inheritance branch is 3 parents tall.   The other inheritance is an interface with everything overridden in the deployed contract.   API works fine.  GUI display won't show storage.  Says there's an error.

My Ganache project with all files in this state is up at:
https://github.com/orbitmechanic/CryptoZoo/tree/Add-Create-Animal

PLATFORM: win32
GANACHE VERSION: 2.4.0

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 474$ of contract$ CryptAnimal (ID 419)
    at C:\Program Files\Ganache\resources\static\node\node_modules\@truffle\decoder\lib\allocate\storage.ts:181:13
    at Array.map (<anonymous>)
    at allocateContract (C:\Program Files\Ganache\resources\static\node\node_modules\@truffle\decoder\lib\allocate\storage.ts:178:59)
    at Object.getStorageAllocations (C:\Program Files\Ganache\resources\static\node\node_modules\@truffle\decoder\lib\allocate\storage.ts:23:19)
    at TruffleContractDecoder.<anonymous> (C:\Program Files\Ganache\resources\static\node\node_modules\@truffle\decoder\lib\interface\contract-decoder.ts:237:39)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\Ganache\resources\static\node\node_modules\@truffle\decoder\dist\interface\contract-decoder.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:21
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1470

**Closed by davidmurdoch** 2020-10-28 18:21 UTC
