### ISSUE TITLE
Unable to change gas limit

### ISSUE THREAD

**Issue by kdelwat** [trufflesuite/ganache#850] opened 2018-07-20 03:50 UTC
In the chain settings, I set the gas limit to be 10000000000. This is reflected in the GUI, as in the image below. However, executing a transaction works against the default gas limit of 6721975, not my custom gas limit.

In this image, you can see the chain information show the updated gas limit, but the transaction receipt show the old limit.

![image](https://user-images.githubusercontent.com/1031518/42982134-38fa1370-8c23-11e8-858a-e65629be5e9f.png)

## Expected Behavior
Changing the gas limit in the settings increases the simulated gas limit for transactions.

## Current Behavior
The gas limit remains as the default in transactions, although it is updated in some parts of the GUI.

## Steps to Reproduce (for bugs)
1. In the chain settings dialogue, change the gas limit to 10000000000
2. Restart the chain
3. Make any transaction against Ganache and check the receipt

## Your Environment
* Version used: 1.1.0.0
* Operating System and version: Windows 10 Home 1803

**Comment by mallapurbharat** [comment] 2018-07-20 09:45
If I understand it right, Ganache GUI setting actually is for Block Gas Limit (it can also mean transaction gas limit if there is only one transaction in the block - which is what happens in a local test blockchain)

When you make a transaction, how are you submitting the transaction? Through Metamask or some such tool right? Is the Gas Limit in that tool set to 6721975? If so, then I'd think that that particular Gas Limit will be used. If it is through your code (eth.sendTransaction() ), then default settings might prevail.

**Comment by benjamincburns** [comment] 2018-08-13 23:43
@mallapurbharat said it better than I could have. The default transaction gas limit is actually fixed to 90,000 by the protocol (this is needed for consensus). If your transaction is being ran w/ a limit of 6721975, you're almost certainly using something which estimates the gas ahead of time and injects that into the tx for you (my guess: MetaMask).

Closing this as it's not a bug on our end.

**Closed by benjamincburns** 2018-08-13 23:43 UTC

**Comment by mrbabtc** [comment] 2020-01-28 14:08
my block gas limit is setted to 10000000 but i only can put 38 transactions per block and use 2415128 per block sending transactions contract creation from same address, are this a protocol limit?

**Comment by benjamincburns** [comment] 2020-02-04 18:37
Hi @mrbabtc - I no longer maintain Ganache or work for Truffle, but what you're describing does sound like a bug, assuming that the transaction that fails due to running out of gas would not cause you to trip over the 10000000 block gas limit. To verify if this is the case, try running the failing transaction without the transactions before it, then check the transaction receipt to see the gas used. This will be more accurate than calling `eth_estimateGas`.

There aren't any protocol limits in play here that I'm aware of. Such protocol limits would likely break things for enterprise chains, as users of Quorum and similar like to set very high block gas limits to enable much more computationally intensive transactions than would normally be allowed on a public network.

As someone who used to be an insider, I can tell you that if you're impacted by this issue the best way to get it fixed quickly is to write a minimal test or program that demonstrates the bug, and then raise a new issue, including the reproduction source directly into the issue, or link to the reproduction source. This will make it very easy for the team to debug it.

Also I'd try testing out `ganache-cli` and see if it has the same issue. If so, you'll want to raise the new issue against [trufflesuite/ganache-core](https://github.com/trufflesuite/ganache-core) instead of Ganache.

**Comment by benjamincburns** [comment] 2020-02-04 18:37
Also pinging @davidmurdoch, as I believe he now oversees Ganache maintenance.

**Comment by YannyD** [comment] 2020-12-24 21:39
Did a solution to this ever come through?  I also changed the truffle config file, updated the black limit in the ganache gui, but gas sent is stuck at 6721975
