### ISSUE TITLE
System Error when running Ganache 2.0.0 on win32

### ISSUE THREAD

**Issue by avinanakarmi** [trufflesuite/ganache#1184] opened 2019-03-26 21:36 UTC
I tried to create a new work space in Ganache and it said this when i added a project and saved the workspace.

PLATFORM: win32
GANACHE VERSION: 2.0.0

EXCEPTION:
```
SyntaxError: Unexpected token k in JSON at position 0
    at JSON.parse (<anonymous>)
    at Pipe.channel.onread (internal/child_process.js:468:28)
```

**Comment by DiscRiskandBisque** [comment] 2019-03-29 15:49
Same as #1184

**Comment by DiscRiskandBisque** [comment] 2019-03-29 15:51
Hi @avinanakarmi, can you provide more context as to when the error occurred? Thanks!

**Comment by avinanakarmi** [comment] 2019-03-30 22:07
I installed the Ganache Windows App and tried to create a new work-space. When i add a project i.e. truffle-config.js file and save work-space, i get the fore mentioned error.

**Comment by davidmurdoch** [comment] 2019-04-02 14:52
@avinanakarmi, Do you mind sharing your truffle config here?

**Comment by imdario** [comment] 2019-04-03 10:06
I ran into this same error. Please find attached my truffle-config.js.

**Comment by davidmurdoch** [comment] 2019-04-03 14:34
@imdario I was unable to reproduce with the supplied `truffle-config.js`. Are you able to share your entire project?

**Comment by imdario** [comment] 2019-04-03 14:38
Actually, I just did this steps:

```
mkdir Greeter
cd Greeter
truffle init
```

That's all. Truffle's version is v5.0.10.

**Comment by davidmurdoch** [comment] 2019-04-03 15:03
@imdario, what version of node does `node --version` return and what OS are you running?

**Comment by avinanakarmi** [comment] 2019-04-03 15:08
Thank you for your response.

I have already solved the issue.
My account in MetaMask was in private mode. I switched it off n the problem
was solved.

**Comment by davidmurdoch** [comment] 2019-04-03 15:35
@avinanakarmi interesting! This is still a bug in Ganache we'll get fixed, as metamask connecting in private mode shouldn't crash it! Thanks!

**Comment by davidmurdoch** [comment] 2019-04-03 15:39
@avinanakarmi I can't reproduce in private mode. Are there any other steps I should take?

**Comment by imdario** [comment] 2019-04-04 07:08
@davidmurdoch It returns v10.7.0. I upgraded and tested against 10.15.3 LTS and it just worked.

I also checked my MetaMask settings and it doesn't have private mode activated.

**Comment by davidmurdoch** [comment] 2019-04-09 15:49
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.

**Closed by davidmurdoch** 2019-04-09 15:49 UTC
Labels: bug, needs more information, needs validation
