### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by conwise18** [trufflesuite/ganache#686] opened 2018-05-30 13:40 UTC
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"gasLimit":2000000000000,"gasPrice":10,"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":9545,"total_accounts":10,"unlocked_accounts":[]}
T+285ms: Ganache started successfully!
T+285ms: Waiting for requests...
T+16990ms: eth_accounts
T+17111ms: eth_call
T+17218ms: eth_call
T+17259ms: eth_accounts
T+17497ms: eth_sendTransaction
T+39942ms: eth_accounts
T+40066ms: eth_call
T+40173ms: eth_call
T+40211ms: eth_accounts
T+40291ms: eth_sendTransaction
T+40433ms:   Transaction: 0xb4ba9a7a65aa3165397bcdc0373588fb18942f25e4bdc140efc30bffc8045514
T+40433ms:   Contract created: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
T+40433ms:   Gas usage: 269607
T+40441ms:   Block Number: 1
T+40441ms:   Block Time: Wed May 30 2018 23:30:51 GMT+1000 (AEST)
T+40449ms: eth_newBlockFilter
T+40457ms: eth_getFilterChanges
T+40469ms: eth_getTransactionReceipt
T+40582ms: eth_getCode
T+40596ms: eth_uninstallFilter
T+40607ms: eth_sendTransaction
T+40684ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+40684ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+40684ms: 
T+40684ms: TypeError: Cannot read property 'get' of undefined
T+40684ms:     at dbGet (/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+40684ms:     at /node_modules/ganache-cli/build/lib.node.js:17614:5
T+40684ms:     at /node_modules/ganache-cli/build/lib.node.js:23091:20
T+40684ms:     at iterate (/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+40684ms:     at /node_modules/ganache-cli/build/lib.node.js:23184:29
T+40684ms:     at /node_modules/ganache-cli/build/lib.node.js:22954:16
T+40684ms:     at /node_modules/ganache-cli/build/lib.node.js:17619:7
T+40684ms:     at /node_modules/ganache-cli/build/lib.node.js:56034:9
T+40684ms:     at dispatchError (/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+40684ms:     at /node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by seesemichaelj** [comment] 2018-05-31 01:19
Hey thanks for reporting this! It's actually a duplicate of #667

**Closed by seesemichaelj** 2018-05-31 01:19 UTC
