### ISSUE TITLE
Eth Balance changes to 0 if you change the amount of Accounts Generated.

### ISSUE THREAD

**Issue by balexander4** [trufflesuite/ganache#969] opened 2018-11-16 02:41 UTC
Changing the amount of accounts that are set in Ganache UI generates new accounts but those account have an Eth balance of 0 when 100 would be the expected balance.

## Expected Behavior

Would expect the balance to be what is set in the Account Default Balance.

## Current Behavior

Currently if a user changes the default accounts the Eth Balance is displayed on the Ui as 0.

## Steps to Reproduce (for bugs)

1.In the Accounts & Keys Setting View the current values set
2.Change the Total Accounts to Generate , Save/Restart
3.View the new accounts generated and the Eth Balance associated vs what should appear in the settings. 

## Your Environment

* Version used:2.0.0
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:windows, ios
* Operating System and version:
* Link to your project:

**Comment by seesemichaelj** [comment] 2018-11-16 02:44
Is this any different than your other issue from earlier today #967?

**Comment by seesemichaelj** [comment] 2018-11-19 19:41
Duplicate of #967

**Closed by seesemichaelj** 2018-11-19 19:41 UTC
Labels: bug
