### ISSUE TITLE
Ganache 1.0.2 hangs on startup

### ISSUE THREAD

**Issue by Celo44** [trufflesuite/ganache#239] opened 2018-01-09 06:52 UTC
<img width="1203" alt="screen shot 2018-01-09 at 10 47 54 am" src="https://user-images.githubusercontent.com/10275440/34708127-ab16fb02-f52a-11e7-88b9-567a31bd8ab3.png">

Ganache hangs on the startup screen every time I open. Just upgraded from version 1.0.1 recently due to the crashing issue. I've tried re-downloading the dmg and re-installing the application.

OS: macOS Sierra 10.12.6
Node: 8.6.0
Npm: 5.3.0

**Comment by loktarjugg** [comment] 2018-01-09 07:03
same here

**Comment by GeoffMall** [comment] 2018-01-09 07:23
This happened to me too. I had to clone repo, then `npm install`, `npm start` to get it working.

**Comment by benjamincburns** [comment] 2018-01-09 09:50
Well that's super disappointing! Thanks for reporting this, all of you. Just for my sanity, can you please quit out of any instances of Ganache, and then from the terminal `ps aux | grep -i ganache` just to make sure you don't have any other instances running in the background? We have a known bug where Ganache hangs on startup when its port is in use by other applications.

**Comment by tomowang** [comment] 2018-01-09 10:14
OS version: 10.12.6 (16G1114)
No other instances running. I have killed related three processes, the same result. Do you have any log files for debugging?

**Comment by eloudsa** [comment] 2018-01-09 10:58
Same here on macOS 10.13.2

**Comment by itamarwe** [comment] 2018-01-09 12:39
Same

**Comment by starspire** [comment] 2018-01-09 14:15
Same here
OS: macOS High Sierra 10.13.2
Node: 9.3.0
NPM: 5.6.0

**Comment by elie222** [comment] 2018-01-09 14:49
Same

**Comment by goldquest** [comment] 2018-01-09 16:12
Which ports need to be free? (Having the same issue)

**Comment by benjamincburns** [comment] 2018-01-10 00:26
All - my deepest apologies for this. We tested the Windows build on two different machines, but I actually forgot to test the mac build on a machine other than my own. Sure enough, when we tested it on @tcoulter's mac, it hung.

I'm in the process of rebuilding and republishing, but I want to get confirmation from a few different people that the new build doesn't hang before I post it.

While that's happening we've marked the 1.0.2 release as a prerelease so that it doesn't show up on the truffle website.

Again, I'm very sorry for the false start here. I promise the next build we post won't have this issue!

**Comment by benjamincburns** [comment] 2018-01-10 00:32
For those of you having this issue, perhaps #216 is related? Can you please check your security settings and verify whether allowing running of apps from any developer fixes the issue? I realize this is a long shot (if this is the problem you shouldn't even get to the spashscreen), but my thinking is that we spawn a subprocess which actually serves up the underlying blockchain, and perhaps that's failing integrity checks somehow?

That said, I can verify that I have removed my developer certificates from keychain and toggled my security settings to run only identified apps, and I can still run this build of Ganache. I'm running High Sierra, 10.13.2.

**Comment by benjamincburns** [comment] 2018-01-10 00:40
One other request - could somebody who is experiencing this issue please try running Ganache from the command line (just open Terminal, iTerm2, or whatever and type `/Applications/Ganache.app/Contents/MacOS/Ganache`) and let me know what you see for output there?

I _think_ you can also run `/Applications/Ganache.app/Contents/MacOS/Ganache --inspect-brk` and then in chrome do `chrome://inspect` and you'll be able to attach the Chrome development tools. This should let you see any internal console output that for whatever reason isn't printing to stdout.

Sincerest thanks in advance for this. Until I can get this reproducing locally, you all are my eyes and ears on this, so I'd be much obliged for any info you're able to dig up.

**Comment by tomowang** [comment] 2018-01-10 00:53
@benjamincburns 
`Blockchain process exited prematurely with code '1', due to signal 'null'`

**Comment by GeoffMall** [comment] 2018-01-10 02:29
tried `/Applications/Ganache.app/Contents/MacOS/Ganache --inspect-brk`
opened chrome and went to `chrome://inspect`. Chrome redirects me to `chrome://inspect/#devices`. Nothing in chrome dev tools console for me.

I got same error as @tomowang 
`Blockchain process exited prematurely with code '1', due to signal 'null'.`

**Comment by benjamincburns** [comment] 2018-01-10 03:58
Thanks for the help, everyone.

I've now uploaded a mac build which appears to no longer exhibit this issue. Special thanks to @M1kep for helping to test this (and other) builds! I'll be leaving this as a prerelease build for now, until I hear back from a few more people that this fixes the problem.

**Since I can't reproduce this myself, please report back here on whether or not this fixes the hanging issue you're experiencing.**

[Direct download link](https://github.com/trufflesuite/ganache/releases/download/v1.0.2/Ganache-1.0.2.dmg)

**Comment by tomowang** [comment] 2018-01-10 06:38
"Ganache" is damaged and can't be opened.

Even worse

**Comment by benjamincburns** [comment] 2018-01-10 20:36
@tomowang can you please confirm the md5 sum of the dmg you downloaded for me?

**Comment by tcoulter** [comment] 2018-01-10 21:53
I was able to reproduce the same issue as @tomowang. I don't believe it to be an md5/transport issue; the dmg allowed me to install Ganache fine, but once I ran Ganache I ran into the same error.

**Comment by benjamincburns** [comment] 2018-01-11 04:12
Alright - I've finally been able to reproduce these issues locally by setting up an OS X vm. I've now updated [the dmg file](https://github.com/trufflesuite/ganache/releases/download/v1.0.2/Ganache-1.0.2.dmg) for what will hopefully be the last time. MD5 sum is `0xbb8db43e1b50aad0a3bfaf1c0a090fd8`.

**Comment by lichla1988** [comment] 2018-01-11 15:48
I download version 1.0.2 on the MAC and it hung.  I downloaded version 1.0.1 and it worked fine until I configured it to point to a blockchain I cannot get too in the settings, then this version hangs.  I need to remove the configurtion files and restart.  On version 1.0.1 when I start from the command line this is the error Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/Applications/Ganache.app/Contents/Resources/app/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by Snuff** [comment] 2018-01-11 18:26
@benjamincburns 1.0.2 works fine, thank you.

**Comment by benjamincburns** [comment] 2018-01-12 01:32
I'm closing this issue, as we've now tested it on four different machines, two of which were VMs w/ fresh installs of OS X (El Capitan & High Sierra) with default security settings.

@lichla1988 If you are still experiencing a hanging problem with 1.0.2, I can only assume that one of the following is true:

1. Check the md5 sum of `Ganache-1.0.2.dmg` with the `md5` command in the terminal. It should be `0xbb8db43e1b50aad0a3bfaf1c0a090fd8`. If it doesn't match, please download it again from the releases page.
2. You are experiencing issue #126. Please check to make sure that the port Ganache listens on (7545 by default) is available by using `netstat -an | grep LISTEN | grep 7545` (change number if you changed the port it's listening on)
3. You are experiencing some other problem, perhaps one which is previously undiscovered. If this is the case, please raise a new issue and we'll look into it. We'll need a bit more info than the heartbeat failure to diagnose it, though. The best way to get this information if you can't load past the splashscreen is to clone the source, switch to the v1.0.2 tag, and run with `npm install && npm start`. This will load the chrome debugging tools alongside Ganache, and you'll be able to see more informative console output there.

**Closed by benjamincburns** 2018-01-12 01:33 UTC

**Comment by pedroduartecosta** [comment] 2019-05-20 15:19
For anyone who may run into this in the future. My problem was that I was **loading a truffle.js config** file and it was getting stuck on the loading screen. 

Running `npm install` inside my project folder, where the truffle.js file is, **fixed** the problem.
