### ISSUE TITLE
System Error when running Ganache 2.1.2 on win32

### ISSUE THREAD

**Issue by mmani99** [trufflesuite/ganache#1590] opened 2020-01-09 16:01 UTC
Created a simple ERC20 contract and deployed using truffle. Using web3j (4.1 ) to transfer tokens from the first account to second account. When I tried to click on the Block and the contract call, I get this error. 
---- MyToken.sol -------
pragma solidity ^0.5.12;
import "openzeppelin-solidity/contracts/token/ERC20/IERC20.sol";
import "openzeppelin-solidity/contracts/token/ERC20/ERC20.sol";
import "openzeppelin-solidity/contracts/token/ERC20/ERC20Detailed.sol";

contract MyToken is ERC20, ERC20Detailed {

	constructor( )   
		ERC20Detailed( "Platimum", "PLT", 2) 
		public {
			_mint( msg.sender, 100000000 );
	}
}

------------------------ 3_deploy_MyToken.js ------

// Note: Interfaces and abstract contracts cannot be deployed and hence not linked
const SafeMath = artifacts.require("SafeMath");
const ERC20 = artifacts.require("ERC20");
const MyToken = artifacts.require("MyToken");

module.exports = function(deployer) {
  deployer.deploy(SafeMath);
  deployer.link(SafeMath, ERC20);
  deployer.deploy(ERC20);
  deployer.link(ERC20, MyToken);
  deployer.deploy(MyToken);
};
-----------------------------------------------------------------------------
PLATFORM: win32
GANACHE VERSION: 2.1.2

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 108$ of contract$ MyToken (ID 81)
    at vars.concat.linearizedBaseContractsFromBase.map (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:164:19)
    at Array.map (native)
    at allocateContract (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:161:61)
    at Object.getStorageAllocations (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:117:47)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+503580451ms: eth_getBlockByNumber
T+503580480ms: eth_getTransactionReceipt
T+503580504ms: eth_getCode
T+503580526ms: eth_getTransactionByHash
T+503580554ms: eth_getBlockByNumber
T+503580571ms: eth_getBalance
T+503580589ms: eth_getBlockByNumber
T+503580617ms: eth_getBlockByNumber
T+503580634ms: eth_getBlockByNumber
T+503580654ms: eth_estimateGas
T+503580683ms: eth_getBlockByNumber
T+503580700ms: eth_blockNumber
T+503580727ms: eth_sendTransaction
T+503580744ms:   Transaction: 0x60798b6192add1ecd97853aff2e5f5b08ed6fd23da41039b4fba48c4afd3100d
T+503580744ms:   Contract created: 0x89c23fb649495ee514c6a34cdd6f77c70b88cc53
T+503580744ms:   Gas usage: 1358322
T+503580744ms:   Block Number: 55
T+503580761ms:   Block Time: Wed Jan 08 2020 14:52:50 GMT-0500 (Eastern Standard Time)
T+503580788ms: eth_getBlockByNumber
T+503580822ms: eth_getTransactionReceipt
T+503580822ms: eth_getCode
T+503580849ms: eth_getTransactionByHash
T+503580866ms: eth_getBlockByNumber
T+503580882ms: eth_getBalance
T+503580907ms: eth_getBlockByNumber
T+503580924ms: eth_getBlockByNumber
T+503580941ms: eth_sendTransaction
T+503580967ms:   Transaction: 0x7c249ab457b435a4479d1e1336552167b71202b65bb8ff42d2947d67c459b40f
T+503580967ms:   Gas usage: 27023
T+503580967ms:   Block Number: 56
T+503580967ms:   Block Time: Wed Jan 08 2020 14:52:50 GMT-0500 (Eastern Standard Time)
T+503580984ms: eth_getBlockByNumber
T+503581001ms: eth_getTransactionReceipt
T+503798730ms: net_version
T+503798763ms: eth_getCode
T+503813941ms: net_version
T+503814169ms: net_version
T+504303758ms: eth_blockNumber
T+504303812ms: net_version
T+504303874ms: eth_accounts
T+504303942ms: eth_accounts
T+504330560ms: eth_getBlockByNumber
T+504357092ms: eth_accounts
T+504375847ms: eth_getBlockByNumber
T+504375900ms: eth_call
T+504380376ms: eth_getBlockByNumber
T+504380414ms: eth_call
T+504390256ms: eth_getBlockByNumber
T+504390303ms: eth_call
T+504398552ms: eth_getBlockByNumber
T+504398602ms: eth_call
T+507938981ms: web3_clientVersion
T+507939549ms: eth_call
T+507939651ms: eth_getTransactionCount
T+507939694ms: eth_sendRawTransaction
T+507939766ms:   Transaction: 0xb5b41a2f3fb983151d66f59e2f8225ffbb28e1c82da006124957ab43becdcf31
T+507939766ms:   Gas usage: 39439
T+507939766ms:   Block Number: 57
T+507939766ms:   Block Time: Wed Jan 08 2020 16:05:30 GMT-0500 (Eastern Standard Time)
T+507939808ms: eth_getBlockByNumber
T+507939879ms: eth_getTransactionReceipt
T+507939922ms: eth_call
T+507939962ms: eth_call
T+507939998ms: eth_call
T+507940033ms: eth_call
T+575116916ms: web3_clientVersion
T+575117476ms: eth_call
T+575117555ms: eth_getTransactionCount
T+575117598ms: eth_sendRawTransaction
T+575117708ms:   Transaction: 0x08d57999636f44c8554ba36f1bc8608637ced8c07167bfdaad565a271162e701
T+575117708ms:   Gas usage: 39439
T+575117708ms:   Block Number: 58
T+575117751ms:   Block Time: Thu Jan 09 2020 10:45:08 GMT-0500 (Eastern Standard Time)
T+575117827ms: eth_getTransactionReceipt
T+575117861ms: eth_getBlockByNumber
T+575117902ms: eth_call
T+575117940ms: eth_call
T+575117981ms: eth_call
T+575118019ms: eth_call
T+575118052ms: eth_call
T+575118087ms: eth_call
T+575539885ms: web3_clientVersion
T+575540420ms: eth_call
T+575540477ms: eth_getTransactionCount
T+575540530ms: eth_sendRawTransaction
T+575540604ms:   Transaction: 0xc09218efcec6648914510cacf250faee6458acd8e01ad1f197d631a047de005e
T+575540604ms:   Gas usage: 39439
T+575540604ms:   Block Number: 59
T+575540604ms:   Block Time: Thu Jan 09 2020 10:52:11 GMT-0500 (Eastern Standard Time)
T+575540693ms: eth_getBlockByNumber
T+575540693ms: eth_getTransactionReceipt
T+575540727ms: eth_call
T+575540768ms: eth_call
T+575540807ms: eth_call
T+575541573ms: eth_call
T+575541610ms: eth_call
T+575541641ms: eth_call
T+575541707ms: eth_getTransactionCount
T+575541774ms: eth_sendRawTransaction
T+575541846ms:   Transaction: 0x65c71b042594eac37557369c891c6a9a7104843dba7a7f3ffbf3aaeb4df7357d
T+575541846ms:   Gas usage: 51432
T+575541846ms:   Block Number: 60
T+575541846ms:   Block Time: Thu Jan 09 2020 10:52:11 GMT-0500 (Eastern Standard Time)
T+575541878ms: eth_getBlockByNumber
T+575541918ms: eth_getTransactionReceipt
T+575542021ms: eth_call
T+575542060ms: eth_call
T+575747297ms: net_version
T+575747542ms: net_version
T+575747583ms: eth_unsubscribe
T+575747678ms: eth_unsubscribe
T+575747727ms: eth_unsubscribe
T+575747727ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:19
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1333

**Closed by davidmurdoch** 2020-10-28 18:19 UTC
