### ISSUE TITLE
Decoding Error when running Ganache 2.4.0 on linux

### ISSUE THREAD

**Issue by simonsavoca** [trufflesuite/ganache#1773] opened 2020-05-04 17:04 UTC
PLATFORM: linux
GANACHE VERSION: 2.4.0

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 90$ of contract$ DemoToken (ID 26)
    at /tmp/.mount_ganachFQjlnG/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:181:13
    at Array.map (<anonymous>)
    at allocateContract (/tmp/.mount_ganachFQjlnG/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:178:59)
    at Object.getStorageAllocations (/tmp/.mount_ganachFQjlnG/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:23:19)
    at TruffleContractDecoder.<anonymous> (/tmp/.mount_ganachFQjlnG/resources/static/node/node_modules/@truffle/decoder/lib/interface/contract-decoder.ts:237:39)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_ganachFQjlnG/resources/static/node/node_modules/@truffle/decoder/dist/interface/contract-decoder.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:22
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1470

**Closed by davidmurdoch** 2020-10-28 18:22 UTC
