### ISSUE TITLE
Linux AppImage is always loading and can't proceed to menu

### ISSUE THREAD

**Issue by neilpalima** [trufflesuite/ganache#317] opened 2018-01-30 06:06 UTC
Ganache AppImage in Linux does not proceed to menu after changing the default settings to invalid/valid local settings ip, port and network id.

 

## Expected Behavior
GUI should show the menu and its information

## Current Behavior
GUI is not showing the menu and its information after changing the settings.

## Steps to Reproduce (for bugs)

1. Open ganache, go to settings
2. Change settings ip, port and network id to a valid/invalid config
3.
4.

## Context

I cannot use the application

## Your Environment

* Version used: Ganache v1.1.0-beta.0
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version: Ubuntu 17.10
* Link to your project:

**Comment by benjamincburns** [comment] 2018-01-30 11:55
This is likely one of a few known issues. Please make sure that no other instances of Ganache are running and that nothing is listening on port 7545. Alternatively, it's possible that you've told Ganache to listen on a network interface which either does not exist, or which your user account doesn't have permission to listen on for that port (this is often controlled by SELinux).

**Comment by neilpalima** [comment] 2018-01-30 23:01
How can I temporary fix this? Even I close then open the AppImage of ganache it does not proceed to the menu. It just shows the loading page with text `Ganache v1.1.0-beta.0` and I cannot do anything.

**Comment by benjamincburns** [comment] 2018-01-31 00:55
First you need to figure out what the problem is. Based on the other reports of similar issues it's likely something else listening on port 7545.

```shell
GANACHE_PORT=7545; sudo netstat -anp | awk '{ if ($4 ~ /.*'$GANACHE_PORT'/) { split($7, parts, "/"); print "PID: " parts[1] " Process Name: " parts[2]; } }'
```

If that spits out a PID, then that is the process which is "stealing" your port. If it's a simple process you can generally kill it with `sudo kill $PID_GOES_HERE`.

I run a full ethereum node on my linux box. Since my node is dockerized, if I change the port in the above script to 8545, it spits out `PID: 8128 Process Name: docker-proxy`. At that point I could do a `docker ps | grep 8545' to figure out which container is the offending one, and stop it.

**Comment by neilpalima** [comment] 2018-01-31 01:22
I run the said script and ganache GUI nows load the menu. None is using port 7545. What happened last time was I set the port to 6545 since I want to try if it can get the data in testrpc that is connected to port 6545 and suddenly the GUI is just loading.

**Comment by benjamincburns** [comment] 2018-01-31 01:24
In that case, this report duplicates #126. I'll close this one, and can you please subscribe to that issue for updates?

**Closed by benjamincburns** 2018-01-31 01:24 UTC

**Comment by neilpalima** [comment] 2018-01-31 01:27
Sure, thanks!
