### ISSUE TITLE
System Error when running Ganache 2.1.1 on win32

### ISSUE THREAD

**Issue by RostyslavDzhohola** [trufflesuite/ganache#2066] opened 2020-10-14 18:21 UTC
PLATFORM: win32
GANACHE VERSION: 2.1.1

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (C:\Users\Rostyslav\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\web3-core-helpers\src\errors.js:35:16)
    at WebsocketProvider._timeout (C:\Users\Rostyslav\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\web3-providers-ws\src\index.js:255:48)
    at W3CWebSocket.connection.onclose (C:\Users\Rostyslav\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\web3-providers-ws\src\index.js:155:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Users\Rostyslav\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\yaeti\lib\EventTarget.js:107:17)
    at W3CWebSocket.onClose (C:\Users\Rostyslav\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (C:\Users\Rostyslav\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (C:\Users\Rostyslav\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\websocket\lib\WebSocketConnection.js:389:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+0ms: eth_unsubscribe
T+20ms: eth_unsubscribe
T+20ms: eth_unsubscribe
T+14548ms: Starting server (version 2.1.1) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","db_path":"C:\\Users\\Rostyslav\\AppData\\Roaming\\Ganache\\workspaces\\recondite-clocks\\chaindata","default_balance_ether":100,"hostname":"127.0.0.1","locked":false,"network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[],"verbose":false,"vmErrorsOnRPCResponse":true}
T+23879ms: Ganache started successfully!
T+23879ms: Waiting for requests...
T+24616ms: net_version
T+25320ms: eth_accounts
T+26050ms: eth_accounts
T+26699ms: eth_getCode
T+27339ms: eth_subscribe
T+27339ms: eth_getLogs
T+28106ms: eth_subscribe
T+28694ms: eth_getCode
T+96657ms: eth_unsubscribe
T+206651ms: net_version
T+206651ms: eth_getBlockByNumber
T+206651ms: eth_getCode
T+206651ms: eth_getBlockByNumber
T+206651ms: eth_getCode
T+206651ms: eth_getBlockByNumber
T+206651ms: eth_accounts
T+206651ms: eth_getBlockByNumber
T+206651ms: eth_getBlockByNumber
T+206651ms: eth_getBlockByNumber
T+206651ms: eth_estimateGas
T+211656ms: eth_getBlockByNumber
T+211656ms: eth_blockNumber
T+211656ms: eth_sendTransaction
T+211656ms:   Transaction: 0xc7b4e27f6817da7eb14e06a88c9b1aa209d774d1772ba9319be3a8f4865a6a18
T+211656ms:   Contract created: 0x064e44842611d387b2281b48a9683b58cd35867a
T+211656ms:   Gas usage: 219143
T+211656ms:   Block Number: 1
T+211656ms:   Block Time: Wed Oct 14 2020 13:18:30 GMT-0500 (Central Daylight Time)
T+211656ms: eth_getTransactionReceipt
T+211656ms: eth_getCode
T+211656ms: eth_getTransactionByHash
T+211656ms: eth_getBlockByNumber
T+211656ms: eth_getBalance
T+211656ms: eth_getBlockByNumber
T+211656ms: eth_getBlockByNumber
T+211656ms: eth_sendTransaction
T+211656ms:   Transaction: 0x59c54f099e973974d28a077c3350024d9f5b57ec13f2fbdd94f139add477828c
T+211656ms:   Gas usage: 41998
T+211656ms:   Block Number: 2
T+211656ms:   Block Time: Wed Oct 14 2020 13:18:31 GMT-0500 (Central Daylight Time)
T+211656ms: eth_getTransactionReceipt
T+211656ms: eth_getBlockByNumber
T+211656ms: eth_accounts
T+211656ms: eth_getBlockByNumber
T+211656ms: eth_getBlockByNumber
T+211656ms: eth_getBlockByNumber
T+211656ms: eth_estimateGas
T+211656ms: eth_getBlockByNumber
T+211656ms: eth_blockNumber
T+211656ms: eth_sendTransaction
T+211656ms:   Transaction: 0x090eac8daef3696ee8bc027d698899f3bc32abf31bb1a24bd40dc9ab10f60969
T+211656ms:   Contract created: 0x1794d32efc63c347c34873b9c34090d15f2e1c62
T+211656ms:   Gas usage: 840355
T+211656ms:   Block Number: 3
T+211656ms:   Block Time: Wed Oct 14 2020 13:18:31 GMT-0500 (Central Daylight Time)
T+211656ms: eth_getTransactionReceipt
T+211656ms: eth_getCode
T+211656ms: eth_getTransactionByHash
T+211656ms: eth_getBlockByNumber
T+211656ms: eth_getBalance
T+211656ms: eth_getBlockByNumber
T+211656ms: eth_getBlockByNumber
T+211656ms: eth_call
T+211656ms: eth_getBlockByNumber
T+211656ms: eth_getBlockByNumber
T+211656ms: eth_sendTransaction
T+211656ms:   Transaction: 0xba069c0c6df871d0a719c8237409704e478690f6791072820944a927d14768ba
T+211656ms:   Gas usage: 26998
T+211656ms:   Block Number: 4
T+211656ms:   Block Time: Wed Oct 14 2020 13:18:32 GMT-0500 (Central Daylight Time)
T+211656ms: eth_getTransactionReceipt
T+217546ms: eth_unsubscribe
T+217546ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:16
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1770

**Closed by davidmurdoch** 2020-10-28 18:16 UTC
