### ISSUE TITLE
System Error when running Ganache 2.4.0 on win32

### ISSUE THREAD

**Issue by bichuga** [trufflesuite/ganache#2021] opened 2020-09-28 01:55 UTC
Clicking on "createPair" transaction which was created during my migration.

My code:
```
module.exports = function(deployer, network, accounts) {
    var cat, dog, factory;
    return deployer.deploy(UniswapV2Factory, accounts[0]).then(function (instance){
        console.log("uniswapfactory address", UniswapV2Factory.address);
        factory = instance;
        console.log("deploying CatToken");
        return deployer.deploy(CatToken).then(function (instance){
            cat = instance;
            console.log("done deploying CatToken");
            console.log("CatToken address", instance.address);
            console.log("deploying DogToken");
            return deployer.deploy(DogToken).then(function (instance){
                dog = instance;
                console.log("DogToken address", instance.address);
                console.log("creating pair");
                factory.createPair(cat.address, dog.address).then(function(instance){
                    console.log("the pair", instance);
                    console.log("the pair address", instance.address);
                });
            });
        });
    });
};
```

PLATFORM: win32
GANACHE VERSION: 2.4.0

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 8871$ of contract$ UniswapV2Factory (ID 5422)
    at C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@truffle\decoder\lib\allocate\storage.ts:181:13
    at Array.map (<anonymous>)
    at allocateContract (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@truffle\decoder\lib\allocate\storage.ts:178:59)
    at Object.getStorageAllocations (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@truffle\decoder\lib\allocate\storage.ts:23:19)
    at TruffleContractDecoder.<anonymous> (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@truffle\decoder\lib\interface\contract-decoder.ts:237:39)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@truffle\decoder\dist\interface\contract-decoder.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:21
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1470

**Closed by davidmurdoch** 2020-10-28 18:21 UTC
