### ISSUE TITLE
System Error when running Ganache 1.0.1 on linux > Ganache on Remix <

### ISSUE THREAD

**Issue by jdetychey** [trufflesuite/ganache#109] opened 2017-11-20 15:03 UTC
PLATFORM: linux
GANACHE VERSION: 1.0.1

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by fatmatto** [comment] 2017-11-21 16:16
I have the same issue when I launch it as my user, but it works when I run it with sudo.

**Comment by Vishalckc** [comment] 2017-11-28 10:34
I agree when I open  on console with admin privilege  connects to my locally running geth node

**Comment by benjamincburns** [comment] 2017-11-30 22:28
Closing this as duplicate of #83.  Will comment on that case shortly.

**Closed by benjamincburns** 2017-11-30 22:28 UTC
