### ISSUE TITLE
System Error when running Ganache 2.3.1 on win32

### ISSUE THREAD

**Issue by xwx19991020** [trufflesuite/ganache#1740] opened 2020-04-22 09:19 UTC
PLATFORM: win32
GANACHE VERSION: 2.3.1

EXCEPTION:
```
Error: connection not open
    at WebsocketProvider.send (C:\Program Files\WindowsApps\GanacheUI_2.3.1.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\web3-providers-ws\src\index.js:282:18)
    at Timeout._onTimeout (C:\Program Files\WindowsApps\GanacheUI_2.3.1.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\web3-providers-ws\src\index.js:267:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:15
closing as duplicate of https://github.com/trufflesuite/ganache/issues/2039

**Closed by davidmurdoch** 2020-10-28 18:15 UTC
Labels: Ethereum, bug, windows
