### ISSUE TITLE
System Error when running Ganache 2.0.0 on darwin

### ISSUE THREAD

**Issue by CodeFuriate** [trufflesuite/ganache#1169] opened 2019-03-22 12:18 UTC
This keeps happening when I want to browse ANY contract in new contract tab.
If i leave GUI i can keep working...  

PLATFORM: darwin
GANACHE VERSION: 2.0.0

EXCEPTION:
```
TypeError: Cannot read property 'nodes' of undefined
    at getStateVariables (/node_modules/truffle-decoder/dist/allocate/storage.js:146:24)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:154:73)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:154:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:28:23)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:87:43)
    at Object.getDecodedEvent (/src/truffle-integration/decode.js:42:11)
    at process.<anonymous> (/src/truffle-integration/index.js:92:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":1000,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"<<<USER_HOME_DIR>>>/Library/Application Support/Ganache/workspaces/solid-robin/chaindata"}
T+1101ms: Ganache started successfully!
T+1101ms: Waiting for requests...
T+1188ms: eth_subscribe
T+1254ms: eth_getLogs
T+1305ms: eth_subscribe
T+1390ms: eth_getCode
T+1493ms: eth_getCode
T+1519ms: eth_getCode
T+1555ms: eth_getCode
T+21847ms: eth_unsubscribe
T+21887ms: eth_unsubscribe
T+21934ms: eth_unsubscribe
T+21934ms: eth_unsubscribe
T+21934ms: eth_unsubscribe
```

**Comment by DiscRiskandBisque** [comment] 2019-03-22 15:24
Hi @CodeFuriate, it would be helpful for reproduction if we could see the dapp you're working with. Is there a repo you mind sharing?

**Comment by theophoric** [comment] 2019-03-28 02:43
I am having this issue as well.

**Comment by CodeFuriate** [comment] 2019-03-28 07:44
@DiscRiskandBisque Yes, https://github.com/GeonNetwork/geon-ethereum

**Comment by davidmurdoch** [comment] 2019-04-02 14:26
Thanks @CodeFuriate! We're looking into it and working on a fix now!

**Comment by haltman-at** [comment] 2019-04-03 20:32
Hm, I don't seem to be able to reproduce this issue.  It's possible later versions of the decoder fixed this, maybe?  (I've been using the development versions.)  I guess I may have to retry with the released versions to be sure.  But for now I'm fairly stumped, because I haven't been able to reproduce this; I haven't gotten any errors of this form either upon inspecting contracts in this project with Ganache, or just checking out the storage allocations from the debugger's debug info.

**Comment by haltman-at** [comment] 2019-04-05 23:56
Oops, seems I made a mistake above -- I was using the application bundle, meaning I was using the released version after all.  Meaning, I can't reproduce this, sorry.  We'll have to figure out some other approach here, I suppose...

**Comment by davidmurdoch** [comment] 2019-04-09 15:48
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.

**Comment by CodeFuriate** [comment] 2019-04-16 09:31
@davidmurdoch sadly its not #https://github.com/trufflesuite/ganache/issues/1256
It starts with "truffle projects" configuration and makes Transaction details and Contracts details crash. 
I have full list of deployed contracts but viewing any of them cases a crash (probably loading transactions part crashes)

**Comment by amorriscode** [comment] 2019-04-16 21:53
Still appears to happen to me on `2.0.1.631`.

**Comment by haltman-at** [comment] 2019-04-19 23:07
So, we're currently looking into the problem, but I wanted to suggest a workaround until such time as we have a fix.  Would you mind trying this and letting us know if it works?  Try recompling your Truffle project with `truffle compile --all`, or, if necessary, recompiling and redeploying the whole thing with `truffle migrate --compile-all --reset`.

See if that fixes the problem for now; let us know if it works.  Meanwhile, we are, as I said, looking into a more proper fix.  Thank you!

**Comment by haltman-at** [comment] 2019-04-22 19:29
OK @davidmurdoch, you are presumably already aware of this, but writing this down here where you can find it again more easily: I just merged [this Truffle PR](https://github.com/trufflesuite/truffle/pull/1933), which causes the decoder to throw a special class of error when this error condition comes up, so that you can catch it rather than crashing.  Obviously that's not a proper fix, but a proper fix is still being worked on; in the meantime, once Truffle 5.0.14 is released, if you upgrade your decoder version you'll be able to catch the error.

Note that Truffle 5.0.13 included a breaking change to the decoder, in that `init` is now async, so you'll have to change that if you haven't already.  But obviously that's pretty minor.

**Comment by davidmurdoch** [comment] 2019-05-03 15:46
This issue should be fixed in the latest beta! https://github.com/trufflesuite/ganache/releases/tag/v2.0.2-beta.0

**Closed by davidmurdoch** 2019-05-03 15:46 UTC
Labels: bug, needs validation, truffle-decoder
