### ISSUE TITLE
Decoding Error when running Ganache 2.4.0 on win32

### ISSUE THREAD

**Issue by smye** [trufflesuite/ganache#1954] opened 2020-08-14 23:08 UTC
Writing my first smart contract and after running `truffle migrate` and viewing the deployed contract, I get a message telling me to open an issue here,

PLATFORM: win32
GANACHE VERSION: 2.4.0

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 153$ of contract$ Colourful (ID 97)
    at C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@truffle\decoder\lib\allocate\storage.ts:181:13
    at Array.map (<anonymous>)
    at allocateContract (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@truffle\decoder\lib\allocate\storage.ts:178:59)
    at Object.getStorageAllocations (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@truffle\decoder\lib\allocate\storage.ts:23:19)
    at TruffleContractDecoder.<anonymous> (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@truffle\decoder\lib\interface\contract-decoder.ts:237:39)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@truffle\decoder\dist\interface\contract-decoder.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by smye** [comment] 2020-08-14 23:11
The solution was to delete everything in the build folder, run `truffle compile` and `truffle deploy` again.

**Comment by patrickodacre** [comment] 2020-09-06 23:31
Thank you!

**Comment by davidmurdoch** [comment] 2020-10-28 18:21
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1470

**Closed by davidmurdoch** 2020-10-28 18:21 UTC
