### ISSUE TITLE
System Error when running Ganache 2.0.0 on linux

### ISSUE THREAD

**Issue by carlosmiei** [trufflesuite/ganache#1187] opened 2019-03-27 13:13 UTC
I was trying to see what was inside a block, after a call a contract's method and ganache just stops working

PLATFORM: linux
GANACHE VERSION: 2.0.0

EXCEPTION:
```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at allocateMembers (/node_modules/truffle-decoder/dist/allocate/storage.js:46:24)
    at allocateStruct (/node_modules/truffle-decoder/dist/allocate/storage.js:34:12)
    at storageSizeAndAllocate (/node_modules/truffle-decoder/dist/allocate/storage.js:250:31)
    at allocateMembers (/node_modules/truffle-decoder/dist/allocate/storage.js:61:31)
    at allocateStruct (/node_modules/truffle-decoder/dist/allocate/storage.js:34:12)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:24:27)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:87:43)
    at Object.getDecodedEvent (/src/truffle-integration/decode.js:42:11)
    at process.<anonymous> (/src/truffle-integration/index.js:92:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"/home/pc/.config/Ganache/workspaces/projeto-LEI/chaindata"}
T+63ms: Ganache started successfully!
T+63ms: Waiting for requests...
T+76ms: eth_subscribe
T+84ms: eth_getLogs
T+96ms: eth_subscribe
T+99ms: eth_getCode
T+103ms: eth_getCode
T+9367ms: net_version
T+9367ms: eth_accounts
T+9367ms: eth_getBlockByNumber
T+9367ms: eth_accounts
T+9393ms: eth_getBlockByNumber
T+9397ms: eth_getBlockByNumber
T+9401ms: eth_getBlockByNumber
T+9406ms: eth_estimateGas
T+9436ms: eth_getBlockByNumber
T+9442ms: eth_blockNumber
T+9448ms: eth_sendTransaction
T+10705ms:   Transaction: 0xd0b593e07c2b5309fc40fdc99b2fea1dcb54c8c2466fa30617709cd587337e9c
T+10708ms:   Contract created: 0x6fa29eb9dd94b7cd2e7bc729ba425b9eb3a996c0
T+10708ms:   Gas usage: 284908
T+10708ms:   Block Number: 3
T+10708ms:   Block Time: Wed Mar 27 2019 13:12:29 GMT+0000 (WET)
T+10710ms: eth_getBlockByNumber
T+10718ms: eth_getTransactionReceipt
T+10722ms: eth_getCode
T+10727ms: eth_getTransactionByHash
T+10730ms: eth_getBalance
T+10733ms: eth_getBlockByNumber
T+10735ms: eth_getBlockByNumber
T+10738ms: eth_sendTransaction
T+10742ms:   Transaction: 0xc5ea10316567bc4f8dd8bbb8aae1c733096abbb707ce129f5230d4913475035a
T+10742ms:   Gas usage: 42034
T+10742ms:   Block Number: 4
T+10746ms:   Block Time: Wed Mar 27 2019 13:12:29 GMT+0000 (WET)
T+10748ms: eth_getBlockByNumber
T+10757ms: eth_getTransactionReceipt
T+10833ms: eth_getBlockByNumber
T+10833ms: eth_accounts
T+10833ms: eth_getBlockByNumber
T+10833ms: eth_getBlockByNumber
T+10833ms: eth_getBlockByNumber
T+10833ms: eth_estimateGas
T+10837ms: eth_getBlockByNumber
T+10839ms: eth_blockNumber
T+10842ms: eth_sendTransaction
T+10844ms:   Transaction: 0x31a7e26406bee56408c1d422497dd1693d30caa0eebe41a817f06a8874387df2
T+10844ms:   Contract created: 0x9a684a0bb0e32e15c0f3de4d36577c329da80566
T+10844ms:   Gas usage: 954998
T+10844ms:   Block Number: 5
T+10847ms:   Block Time: Wed Mar 27 2019 13:12:29 GMT+0000 (WET)
T+10855ms: eth_getBlockByNumber
T+10858ms: eth_getTransactionReceipt
T+10860ms: eth_getCode
T+10863ms: eth_getTransactionByHash
T+10865ms: eth_getBalance
T+10868ms: eth_getBlockByNumber
T+10870ms: eth_getBlockByNumber
T+10873ms: eth_sendTransaction
T+10875ms:   Transaction: 0xdcb0f78eb2b6e74305544a48d07817d158bb5235c671dfbb3b9458a2ab824c10
T+10875ms:   Gas usage: 27034
T+10875ms:   Block Number: 6
T+10878ms:   Block Time: Wed Mar 27 2019 13:12:29 GMT+0000 (WET)
T+10886ms: eth_getBlockByNumber
T+10888ms: eth_getTransactionReceipt
T+19344ms: net_version
T+19356ms: eth_accounts
T+21502ms: eth_getBlockByNumber
T+34807ms: eth_getBlockByNumber
T+34816ms: eth_sendTransaction
T+35230ms:   Transaction: 0xe59048ec20c36bb60f8615960a919491983bc09da115a783dffdc97b88f6d4a6
T+35230ms:   Gas usage: 63896
T+35230ms:   Block Number: 7
T+35230ms:   Block Time: Wed Mar 27 2019 13:12:54 GMT+0000 (WET)
T+35233ms: eth_getBlockByNumber
T+35233ms: eth_getTransactionReceipt
T+43678ms: eth_unsubscribe
T+43682ms: eth_unsubscribe
T+43687ms: eth_unsubscribe
T+43692ms: eth_unsubscribe
T+43701ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment] 2019-04-02 15:07
Thanks for opening the issue, @carlosmiei. We're looking into the cause now!

**Comment by haltman-at** [comment] 2019-04-03 19:44
Hi, do you possibly have more detailed reproduction instructions, say an example project that causes the error?  Thank you!

**Comment by carlosmiei** [comment] 2019-04-09 08:05
Hi, this happened to me several times, One of the times was when i was trying to open a contract call, inside a block.

**Comment by davidmurdoch** [comment] 2019-04-09 15:45
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have an issues or if the fix doesn't work for you.

**Comment by carlosmiei** [comment] 2019-04-10 19:16
@davidmurdoch  Thank you :)

**Closed** 2019-04-15 12:16 UTC
Labels: bug, needs validation, truffle-decoder
