### ISSUE TITLE
Build from source code "ganache-1.3.1.tar.gz" on Mac, but npm install shows warnings and waste a lot of CPU and time consuming

### ISSUE THREAD

**Issue by PeterTsungYu** [trufflesuite/ganache#1162] opened 2019-03-17 10:27 UTC
I tried to build from source code for new release "ganache-1.3.1.tar.gz". (Since the ganache UI cannot be updated in its application)
I am running in a pure nodejs package only creating by anaconda. (no other packages involved)
But however, after extracting the tar.gz file into a directory, I ran npm install inside the directory. 
And, It kept showing the warnings regarding the tarball data seems to be corrupted. 
It used a lot of CPU and times.
Finally, I force to quit the process.

 

## Current Behavior

WARN tarball tarball data for async@1.5.2 (sha1-7GphrlZIDAw8skHJVhjiCJL5Zyo=) seems to be corrupted. Trying one more time.
WARN tarball tarball data for react-moment@0.2.4 (sha1-sn7AZLjWwylmCvoUr227R/8O95k=) seems to be corrupted. Trying one more time.
WARN tarball tarball data for fs-extra@7.0.1 (sha512-YJDaCJZEnBmcbw13fvdAM9AwNOJwOzrE4pqMqBq5nFiEqXUqHwlK4B+3pUw6JNvfSPtX05xFHtYy/1ni01eGCw==) seems to be corrupted. Trying one more time.
WARN tarball tarball data for dmg-builder@5.3.1 (sha512-/+vtqlgvTtha/4Gc76XIRKS2KzYO58sTWXhZ/kgfNr05ZXY6bIw26v7xDu8ZBpTYnfWI09JRZTMv1yIXT/vvfg==) seems to be corrupted. Trying one more time.
WARN tarball tarball data for ganache-core@2.5.1 (sha512-sqTpmUtoExsUZqCqMdIZ+kPmXXu/fab755LpCaaty2u9EHb9gfIM9f/8gTpg0biaJ7LesbdyTfAbw66wHi4ujw==) seems to be corrupted. Trying one more time.
...
WARN tarball tarball data for typescript@3.1.6 (sha512-tDMYfVtvpb96msS1lDX9MEdHrW4yOuZ4Kdc4Him9oU796XldPYF/t2+uKoX0BBa0hXXwDlqYQbXY5Rzjzc5hBA==) seems to be corrupted. Trying one more time.
WARN tarball tarball data for app-builder-bin@2.1.2 (sha512-PZJspzAqB0+z60OalXChP9I05BzODd/ffDz6RvTmDG3qclr7YrnpqzvPF+T7vGVtk2nN7syuveTQROJfXcB8xA==) seems to be corrupted. Trying one more time.

## Steps to Reproduce (for bugs)

1.  tar xzvf ganache-1.3.1.tar.gz
2. cd ganache-1.3.1/  
3. conda activate environment
4. npm install

## Context

well, I am trying to build from source code with npm.
Seems like a stupid procee, because I could just download a dmg file for my Mac.
I would say, I just would like to give this a try.

## Your Environment

* Version used: ganache-1.3.1.tar.gz
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): 
libcxx                    4.0.1
libcxxabi               4.0.1 
nodejs                   10.13.0
npm                       6.4.1
* Server type and version: local 
* Operating System and version: macOC Mojave v10.14.3

**Comment by davidmurdoch** [comment] 2019-03-17 15:43
interesting that the install isn't working. I'll look into why that is.

Why can't you use the dmg file offered on [v1.3.1 the release](https://github.com/trufflesuite/ganache/releases/tag/v1.3.1)?

**Comment by PeterTsungYu** [comment] 2019-03-17 18:52
> interesting that the install isn't working. I'll look into why that is.
> 
> Why can't you use the dmg file offered on [v1.3.1 the release](https://github.com/trufflesuite/ganache/releases/tag/v1.3.1)?

Actually, I can use dmg to install on my Mac.
I installed the previous version.
When I tried to update it in the UI, it can't be updated.
It makes me go for the source code for the newest version this time.

**Comment by davidmurdoch** [comment] 2019-03-18 00:40
> When I tried to update it in the UI, it can't be updated.
> It makes me go for the source code for the newest version this time.

The UI should send you to the releases page for v1.3.1 (https://github.com/trufflesuite/ganache/releases/v1.3.1). Where you can download the dmg. Is that not what is happening?

**Comment by PeterTsungYu** [comment] 2019-03-18 08:15
> Is that not what is happening?

So, in the UI, there is a button for updating. 
When I click the button, it doesn't work.
It said I cannot update to the new version or something like that.
Sorry, I already deleted the file, so I cannot show the screenshot.

**Comment by davidmurdoch** [comment] 2019-03-18 14:12
@PeterTsungYu 	Thanks for taking the time to file the issue. I'm going to go ahead and close it since neither of us can reproduce now. If you run into the issue again please feel free to comment on this issue with the details! Thanks!

**Closed by davidmurdoch** 2019-03-18 14:12 UTC

**Comment by PeterTsungYu** [comment] 2019-03-18 18:18
Oh, well, I mean to issue for the build of source code. Not the UI though...
