### ISSUE TITLE
System Error when running Ganache 2.0.0 on darwin (ABIEncoderV2)

### ISSUE THREAD

**Issue by loredanacirstea** [trufflesuite/ganache#1193] opened 2019-03-29 16:39 UTC
This error happened in two cases:
- when I wanted to look at a contract that uses ABIEncoderV2 features - `struct`s as inputs in external/public functions
- when I wanted to look at a transaction that contains calls to public functions with `struct`s as inputs

Using solc 0.5.7

PLATFORM: darwin
GANACHE VERSION: 2.0.0

EXCEPTION:
```
TypeError: Cannot read property 'members' of undefined
    at allocateStruct (/node_modules/truffle-decoder/dist/allocate/storage.js:34:62)
    at storageSizeAndAllocate (/node_modules/truffle-decoder/dist/allocate/storage.js:250:31)
    at allocateMembers (/node_modules/truffle-decoder/dist/allocate/storage.js:61:31)
    at allocateStruct (/node_modules/truffle-decoder/dist/allocate/storage.js:34:12)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:24:27)
    at TruffleContractDecoder.init (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:87:43)
    at Object.getDecodedEvent (/src/truffle-integration/decode.js:42:11)
    at process.<anonymous> (/src/truffle-integration/index.js:92:31)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:768:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":8545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"/Users/loredana/Library/Application Support/Ganache/workspaces/dType/chaindata"}
T+449ms: Ganache started successfully!
T+449ms: Waiting for requests...
T+487ms: net_version
T+532ms: eth_getCode
T+573ms: eth_subscribe
T+612ms: eth_getLogs
T+659ms: eth_subscribe
T+698ms: eth_getCode
T+735ms: eth_getCode
T+774ms: eth_getCode
T+812ms: eth_getCode
T+860ms: eth_getCode
T+899ms: eth_getCode
T+1126ms: net_version
T+7152ms: eth_blockNumber
T+7196ms: net_version
T+7245ms: eth_blockNumber
T+7284ms: net_version
T+7324ms: eth_blockNumber
T+8003ms: net_version
T+10002ms: net_version
T+11068ms: eth_blockNumber
T+13001ms: net_version
T+14995ms: net_version
T+15072ms: eth_blockNumber
T+17679ms: net_version
T+19174ms: eth_blockNumber
T+19789ms: eth_unsubscribe
T+19830ms: eth_unsubscribe
T+19873ms: eth_unsubscribe
T+19925ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment] 2019-04-02 15:01
Thanks for filing the issue, @loredanacirstea! We're looking into a fix for it now!

**Comment by haltman-at** [comment] 2019-04-03 19:44
Hi, do you possibly have more detailed reproduction instructions, say an example project that causes the error?  Thank you!

**Comment by loredanacirstea** [comment] 2019-04-03 19:59
@haltman-at , I was running this `run` function here: https://github.com/ctzurcanu/dType/blob/242edbb518c59362fb69cb3a387bbe3d87575ba0/contracts/contracts/dType.sol#L259

**Comment by loredanacirstea** [comment] 2019-04-03 20:37
To reproduce:
- comment out external file dependencies & other network configs in `truffle-config.js`
- running `truffle migrate --network ganache --reset` from `/contracts` -> going to `Contracts` tab in Ganache and clicking on `Deployed` next to the `dType` contract -> the error above

I tried to easily reproduce the error when looking at a transaction with:
- using Ganache as the truffle `development` network
- running `truffle test test/dtype_AB.js` from `/contracts` - last transaction should be the above `run()`
but the error did not appear (it seems that in this case, the source code of the contracts  is not linked). The error appeared however when doing a `run()` transaction on the `dType` contract deployed through migrations.

**Comment by haltman-at** [comment] 2019-04-04 04:52
Hm, I don't seem to be able to reproduce this issue. It's possible later versions of the decoder fixed this, maybe? (I've been using the development versions.) I guess I may have to retry with the released versions to be sure, though I'm skeptical there's been any relevant change. But for now I'm fairly stumped, because I haven't been able to reproduce this; I haven't gotten any errors of this form either upon inspecting contracts in this project with Ganache, or just checking out the storage allocations from the debugger's debug info. Allocation seems to be working fine here, so I'm not sure how I can isolate the problem at the moment, unfortunately.  But like I said I'll try again shortly.

**Comment by haltman-at** [comment] 2019-04-05 23:56
Oops, seems I made a mistake above -- I was using the application bundle, meaning I was using the released version after all.  Meaning, I can't reproduce this, sorry.  We'll have to figure out some other approach here, I suppose...

**Comment by loredanacirstea** [comment] 2019-04-06 00:22
The error was happening consistently with the 2.0.0 version that I had installed.
I downloaded it again (`Ganache-2.0.0.dmg`) and reinstalled -> error does not happen anymore and now I actually see the storage layout in the `dType` contract.

I don't know why it did not work before (same version, no updates in between).
From my side, this issue can be closed.

**Comment by haltman-at** [comment] 2019-04-08 16:26
How odd!  Well, thanks for reporting it.  Hopefully we can figure out why this is happening with some installations.

**Comment by davidmurdoch** [comment] 2019-04-09 15:46
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have an issues or if the fix doesn't work for you.

**Closed by davidmurdoch** 2019-04-09 15:46 UTC
Labels: bug, truffle-decoder
