### ISSUE TITLE
System Error when running Ganache 2.1.2 on darwin

### ISSUE THREAD

**Issue by vaibs28** [trufflesuite/ganache#1737] opened 2020-04-21 07:12 UTC
PLATFORM: darwin
GANACHE VERSION: 2.1.2

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 313$ of contract$ HashStorage (ID 185)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:164:19)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:161:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:117:47)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.1.2) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"/Users/vaibhav/Library/Application Support/Ganache/workspaces/proj/chaindata"}
T+198ms: Ganache started successfully!
T+198ms: Waiting for requests...
T+246ms: eth_subscribe
T+256ms: eth_getLogs
T+267ms: eth_subscribe
T+291ms: eth_getCode
T+324ms: eth_getCode
T+6728ms: net_version
T+6798ms: net_version
T+6813ms: eth_unsubscribe
T+6833ms: eth_unsubscribe
T+6852ms: eth_unsubscribe
T+6859ms: eth_unsubscribe
```

**Comment by nicholasjpaterno** [comment] 2020-04-21 15:16
This should be fixed if you update to the latest release. Thanks! https://github.com/trufflesuite/ganache/releases/

**Comment by nicholasjpaterno** [comment] 2020-04-21 19:58
This may have been closed in error, I'm going to reopen this for tracking!

**Comment by davidmurdoch** [comment] 2020-10-28 18:22
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1470

**Closed by davidmurdoch** 2020-10-28 18:22 UTC
