### ISSUE TITLE
System Error when running Ganache 2.1.2 on darwin

### ISSUE THREAD

**Issue by iamBishalChakraborty** [trufflesuite/ganache#1706] opened 2020-04-11 09:29 UTC
PLATFORM: darwin
GANACHE VERSION: 2.1.2

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 184$ of contract$ indVerify (ID 110)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:164:19)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:161:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:117:47)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+2945612ms:    >   ],
T+2945612ms:    >   "id": 1586597324087
T+2945612ms:    > }
T+2945612ms: eth_unsubscribe
T+2945621ms:    > {
T+2945621ms:    >   "jsonrpc": "2.0",
T+2945621ms:    >   "method": "eth_unsubscribe",
T+2945621ms:    >   "params": [
T+2945621ms:    >     "0x2"
T+2945621ms:    >   ],
T+2945621ms:    >   "id": 1586597324088
T+2945621ms:    > }
T+2945621ms:  <   {
T+2945621ms:  <     "id": 28,
T+2945621ms:  <     "jsonrpc": "2.0",
T+2945621ms:  <     "result": true
T+2945621ms:  <   }
T+2945631ms:  <   {
T+2945631ms:  <     "id": 29,
T+2945631ms:  <     "jsonrpc": "2.0",
T+2945631ms:  <     "result": true
T+2945631ms:  <   }
T+2945639ms:  <   {
T+2945639ms:  <     "id": 1586597324087,
T+2945639ms:  <     "jsonrpc": "2.0",
T+2945639ms:  <     "result": true
T+2945639ms:  <   }
T+2945652ms:  <   {
T+2945652ms:  <     "id": 1586597324087,
T+2945652ms:  <     "jsonrpc": "2.0",
T+2945652ms:  <     "error": {
T+2945652ms:  <       "message": "Subscription ID 0x1 not found.",
T+2945652ms:  <       "code": -32000,
T+2945652ms:  <       "data": {
T+2945652ms:  <         "stack": "Error: Subscription ID 0x1 not found.\n    at SubscriptionSubprovider.eth_unsubscribe (/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:78:8)\n    at SubscriptionSubprovider.handleRequest (/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:134:12)\n    at next (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:136:18)\n    at DelayedBlockFilter.handleRequest (/node_modules/ganache-core/lib/subproviders/delayedblockfilter.js:31:3)\n    at next (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:136:18)\n    at RequestFunnel.handleRequest (/node_modules/ganache-core/lib/subproviders/requestfunnel.js:32:12)\n    at next (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:136:18)\n    at Web3ProviderEngine._handleAsync (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:123:3)\n    at Timeout._onTimeout (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:107:12)\n    at ontimeout (timers.js:469:11)\n    at tryOnTimeout (timers.js:304:5)\n    at Timer.listOnTimeout (timers.js:264:5)",
T+2945652ms:  <         "name": "Error"
T+2945652ms:  <       }
T+2945652ms:  <     }
T+2945652ms:  <   }
T+2945660ms:  <   {
T+2945660ms:  <     "id": 1586597324088,
T+2945660ms:  <     "jsonrpc": "2.0",
T+2945660ms:  <     "error": {
T+2945660ms:  <       "message": "Subscription ID 0x2 not found.",
T+2945660ms:  <       "code": -32000,
T+2945660ms:  <       "data": {
T+2945660ms:  <         "stack": "Error: Subscription ID 0x2 not found.\n    at SubscriptionSubprovider.eth_unsubscribe (/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:78:8)\n    at SubscriptionSubprovider.handleRequest (/node_modules/ganache-core/node_modules/web3-provider-engine/subproviders/subscriptions.js:134:12)\n    at next (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:136:18)\n    at DelayedBlockFilter.handleRequest (/node_modules/ganache-core/lib/subproviders/delayedblockfilter.js:31:3)\n    at next (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:136:18)\n    at RequestFunnel.handleRequest (/node_modules/ganache-core/lib/subproviders/requestfunnel.js:32:12)\n    at next (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:136:18)\n    at Web3ProviderEngine._handleAsync (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:123:3)\n    at Timeout._onTimeout (/node_modules/ganache-core/node_modules/web3-provider-engine/index.js:107:12)\n    at ontimeout (timers.js:469:11)\n    at tryOnTimeout (timers.js:304:5)\n    at Timer.listOnTimeout (timers.js:264:5)",
T+2945660ms:  <         "name": "Error"
T+2945660ms:  <       }
T+2945660ms:  <     }
T+2945660ms:  <   }
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:18
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1333

**Closed by davidmurdoch** 2020-10-28 18:18 UTC
