### ISSUE TITLE
Decoding Error when running Ganache 2.3.1 on darwin

### ISSUE THREAD

**Issue by srinivasmangipudi** [trufflesuite/ganache#1751] opened 2020-04-25 16:55 UTC
PLATFORM: darwin
GANACHE VERSION: 2.3.1

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 711$ of contract$ CryptoLightOwnership (ID 465)
    at /Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:181:13
    at Array.map (<anonymous>)
    at allocateContract (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:178:59)
    at Object.getStorageAllocations (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:23:19)
    at TruffleContractDecoder.<anonymous> (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/interface/contract-decoder.ts:237:39)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/dist/interface/contract-decoder.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:22
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1470

**Closed by davidmurdoch** 2020-10-28 18:22 UTC
