### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by fffy2366** [trufflesuite/ganache#616] opened 2018-05-14 06:30 UTC
PLATFORM: win32
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+273645101ms: eth_getBlockByNumber
T+273653112ms: eth_getBlockByNumber
T+273661122ms: eth_getBlockByNumber
T+273669135ms: eth_getBlockByNumber
T+273677148ms: eth_getBlockByNumber
T+273685158ms: eth_getBlockByNumber
T+273693170ms: eth_getBlockByNumber
T+273701180ms: eth_getBlockByNumber
T+273709191ms: eth_getBlockByNumber
T+273717202ms: eth_getBlockByNumber
T+273725214ms: eth_getBlockByNumber
T+273733225ms: eth_getBlockByNumber
T+273741236ms: eth_getBlockByNumber
T+273749248ms: eth_getBlockByNumber
T+273757259ms: eth_getBlockByNumber
T+273765270ms: eth_getBlockByNumber
T+273773280ms: eth_getBlockByNumber
T+273781293ms: eth_getBlockByNumber
T+273789303ms: eth_getBlockByNumber
T+273797314ms: eth_getBlockByNumber
T+273805326ms: eth_getBlockByNumber
T+273813337ms: eth_getBlockByNumber
T+273821348ms: eth_getBlockByNumber
T+273829360ms: eth_getBlockByNumber
T+273837372ms: eth_getBlockByNumber
T+273845382ms: eth_getBlockByNumber
T+273853394ms: eth_getBlockByNumber
T+273861405ms: eth_getBlockByNumber
T+273869416ms: eth_getBlockByNumber
T+273877427ms: eth_getBlockByNumber
T+273885438ms: eth_getBlockByNumber
T+273893448ms: eth_getBlockByNumber
T+273901460ms: eth_getBlockByNumber
T+273909472ms: eth_getBlockByNumber
T+273917484ms: eth_getBlockByNumber
T+273925495ms: eth_getBlockByNumber
T+273933507ms: eth_getBlockByNumber
T+273941518ms: eth_getBlockByNumber
T+273949530ms: eth_getBlockByNumber
T+273957541ms: eth_getBlockByNumber
T+273965551ms: eth_getBlockByNumber
T+273973563ms: eth_getBlockByNumber
T+273981574ms: eth_getBlockByNumber
T+273989585ms: eth_getBlockByNumber
T+273997596ms: eth_getBlockByNumber
T+274005608ms: eth_getBlockByNumber
T+274013619ms: eth_getBlockByNumber
T+274021630ms: eth_getBlockByNumber
T+274029643ms: eth_getBlockByNumber
T+274037656ms: eth_getBlockByNumber
T+274045666ms: eth_getBlockByNumber
T+274053678ms: eth_getBlockByNumber
T+274061690ms: eth_getBlockByNumber
T+274069701ms: eth_getBlockByNumber
T+274077712ms: eth_getBlockByNumber
T+274085724ms: eth_getBlockByNumber
T+274093735ms: eth_getBlockByNumber
T+274101745ms: eth_getBlockByNumber
T+274109755ms: eth_getBlockByNumber
T+274117765ms: eth_getBlockByNumber
T+274125777ms: eth_getBlockByNumber
T+274133788ms: eth_getBlockByNumber
T+274141802ms: eth_getBlockByNumber
T+274149814ms: eth_getBlockByNumber
T+274157825ms: eth_getBlockByNumber
T+274165837ms: eth_getBlockByNumber
T+274173849ms: eth_getBlockByNumber
T+274181862ms: eth_getBlockByNumber
T+274189873ms: eth_getBlockByNumber
T+274197883ms: eth_getBlockByNumber
T+274205895ms: eth_getBlockByNumber
T+274213906ms: eth_getBlockByNumber
T+274221917ms: eth_getBlockByNumber
T+274229928ms: eth_getBlockByNumber
T+274237939ms: eth_getBlockByNumber
T+274245949ms: eth_getBlockByNumber
T+274253961ms: eth_getBlockByNumber
T+274261975ms: eth_getBlockByNumber
T+274269987ms: eth_getBlockByNumber
T+274277999ms: eth_getBlockByNumber
T+274286010ms: eth_getBlockByNumber
T+274294022ms: eth_getBlockByNumber
T+274302032ms: eth_getBlockByNumber
T+274310042ms: eth_getBlockByNumber
T+274318054ms: eth_getBlockByNumber
T+274326065ms: eth_getBlockByNumber
T+274334075ms: eth_getBlockByNumber
T+274342086ms: eth_getBlockByNumber
T+274350096ms: eth_getBlockByNumber
T+274358107ms: eth_getBlockByNumber
T+274366119ms: eth_getBlockByNumber
T+274374129ms: eth_getBlockByNumber
T+274382140ms: eth_getBlockByNumber
T+274390151ms: eth_getBlockByNumber
T+274398163ms: eth_getBlockByNumber
T+274406173ms: eth_getBlockByNumber
T+274414216ms: eth_getBlockByNumber
T+274422196ms: eth_getBlockByNumber
T+274430209ms: eth_getBlockByNumber
T+274438221ms: eth_getBlockByNumber
T+274446233ms: eth_getBlockByNumber
T+274454245ms: eth_getBlockByNumber
T+274462256ms: eth_getBlockByNumber
T+274470268ms: eth_getBlockByNumber
T+274478278ms: eth_getBlockByNumber
T+274486291ms: eth_getBlockByNumber
T+274494304ms: eth_getBlockByNumber
T+274502318ms: eth_getBlockByNumber
T+274510332ms: eth_getBlockByNumber
T+274518344ms: eth_getBlockByNumber
T+274526356ms: eth_getBlockByNumber
T+274534367ms: eth_getBlockByNumber
T+274542379ms: eth_getBlockByNumber
T+274550392ms: eth_getBlockByNumber
T+274558402ms: eth_getBlockByNumber
T+274566415ms: eth_getBlockByNumber
T+274574427ms: eth_getBlockByNumber
T+274582439ms: eth_getBlockByNumber
T+274590450ms: eth_getBlockByNumber
T+274598461ms: eth_getBlockByNumber
T+274606474ms: eth_getBlockByNumber
T+274614486ms: eth_getBlockByNumber
T+274622499ms: eth_getBlockByNumber
T+274630508ms: eth_getBlockByNumber
T+274638520ms: eth_getBlockByNumber
T+274646532ms: eth_getBlockByNumber
T+274654543ms: eth_getBlockByNumber
T+274662555ms: eth_getBlockByNumber
T+274664071ms: net_version
T+274664077ms: eth_accounts
T+274664131ms: eth_accounts
T+274666794ms: eth_accounts
T+274666829ms: eth_sendTransaction
T+274666970ms: C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:63898
T+274666970ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&
T+274666970ms: 
T+274666970ms: Error: ENOENT: no such file or directory, open 'C:\Users\ADMINI~1\AppData\Local\Temp\tmp-216548rspVMZ9kU71W\!trie_db!0xce93fd1157e86e4b2b6a16773cce512052e7c9adcf0ef5800f49313866601c71'
```

**Comment by seesemichaelj** [comment] 2018-05-25 23:40
Thanks so much @fffy2366 for reporting this! Is it possible that your disk space of your C Drive is getting low? Thanks!

**Comment by benjamincburns** [comment] 2018-08-27 18:36
Hi @fffy2366 - the problem here is likely caused by the temporary directory which ganache uses for storing its database being deleted while ganache is running. This might've happened due to you running a disk cleanup tool or similar.

Closing this one as this is excepted behavior.

**Closed by benjamincburns** 2018-08-27 18:36 UTC
