### ISSUE TITLE
two independent instances?

### ISSUE THREAD

**Issue by drandreaskrueger** [trufflesuite/ganache#108] opened 2017-11-20 10:09 UTC
How can I run 2 ganache instances? I need two independent chains on one machine.

I have found and changed the port 7546 & network_id 5778 here, but it's not enough seemingly:

    nano src/Services/Settings.js
```
  server: {
    hostname: "127.0.0.1",
    port: 7546,
    network_id: 5778,
    ...
  }
```
the GUI still comes up with `RPC SERVER HTTP://127.0.0.1:7545`

The repo search does not show any other [occurrence of 7545](https://github.com/trufflesuite/ganache/search?q=7545).

I cannot run two instances concurrently.   
The 2nd one reports not s.th. like "port already taken", but this error message:
```
✔ Preparing native dependencies: 1 / 1
✔ Launching Application
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (.../trufflesuite/ganache2/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

## Issue Type

- [x] Feature

## Description

please have a central settings file where everything can be configured.

## Steps to reproduce

```
git clone https://github.com/trufflesuite/ganache
git clone https://github.com/trufflesuite/ganache ganache2

cd ganache/
npm install
npm start

cd ../ganache2
npm install
nano src/Services/Settings.js  # then change port to 7546
npm start
```

# Versions

```
uname -a; npm --version; node --version
Linux ... 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
5.5.1
v9.1.0
```

**Comment by drandreaskrueger** [comment] 2017-11-29 14:18
anyone?

**Comment by drandreaskrueger** [comment] 2017-11-29 15:28
When I change something on the settings page (where I can change localhost, port 7545, networkid 5777) 
and RESTART ganache with `npm start` - it remembers my settings.

Where are the settings stored?

How can I switch that off? Because I want to run 2 concurrent ganache chains on one machine.

**Comment by seesemichaelj** [comment] 2018-06-08 06:51
This is a duplicate of #684 (using the more recent issue for tracking just for recency sake). Running multiple instances currently is not supported. They both share the same config/`Settings` file. This file is what is used despite the change of the source code you made. The file can be found here:
  - MacOS: `~/Library/Application\ Support/Ganache/Settings`
  - Windows: `%APPDATA%\Ganache\Settings`
  - Linux: either `$XDG_CONFIG_HOME/Ganache/Settings` or `~/.config/Ganache/Settings`

The software currently doesn't let you "turn off remembering my settings". In #684, we will however look into separating the settings files to allow multiple instances.

The only way you can currently run multiple instances using the ganache-core is by using https://github.com/trufflesuite/ganache-cli

**Closed by seesemichaelj** 2018-06-08 06:51 UTC
Labels: enhancement
