### ISSUE TITLE
System Error when running Ganache 2.0.0-rc.3 on linux

### ISSUE THREAD

**Issue by admazzola** [trufflesuite/ganache#1159] opened 2019-03-14 02:42 UTC
PLATFORM: linux
GANACHE VERSION: 2.0.0-rc.3

EXCEPTION:
```
Not connected to child process
```

**Comment by davidmurdoch** [comment] 2019-04-02 15:27
@admazzola 	Can you provider any more information on how to reproduce this issue?

**Comment by davidmurdoch** [comment] 2019-04-09 15:53
This error message should now be improved in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 I'm closing this one due to lack of additional info. If you do come across this bug again please do open a new issue with the new stack trace information.

**Closed by davidmurdoch** 2019-04-09 15:53 UTC
Labels: bug, needs more information, needs validation
