### ISSUE TITLE
ganache-2.3.0-beta.2-linux-x86_64.AppImage - New Workspace > blank page

### ISSUE THREAD

**Issue by SvenMeyer** [trufflesuite/ganache#1620] opened 2020-02-08 07:15 UTC
ganache-2.3.0-beta.2-linux-x86_64.AppImage
Arch Linux

- deleted ~/.config/Ganache
- started `ganache-2.3.0-beta.2-linux-x86_64.AppImage`
- chose [New Workspace]
- just a blank window showed up

**Comment by davidmurdoch** [comment] 2020-02-11 19:16
I've been unable to reproduce this issue. Are you able to reproduce this consistently?

**Comment by davidmurdoch** [comment] 2020-04-11 16:42
Should be fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!

**Closed by davidmurdoch** 2020-04-11 16:42 UTC
Labels: awaiting-response, bug
