### ISSUE TITLE
Decoding Error when running Ganache 2.3.0-beta.1 on linux

### ISSUE THREAD

**Issue by BrianMwangi21** [trufflesuite/ganache#1648] opened 2020-02-28 13:07 UTC
PLATFORM: linux
GANACHE VERSION: 2.3.0-beta.1

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 193$ of contract$ Shilingi (ID 166)
    at /tmp/.mount_ganachF72Qkx/resources/static/node/node_modules/@truffle/decoder/dist/allocate/storage.js:164:19
    at Array.map (<anonymous>)
    at allocateContract (/tmp/.mount_ganachF72Qkx/resources/static/node/node_modules/@truffle/decoder/dist/allocate/storage.js:161:61)
    at Object.getStorageAllocations (/tmp/.mount_ganachF72Qkx/resources/static/node/node_modules/@truffle/decoder/dist/allocate/storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (/tmp/.mount_ganachF72Qkx/resources/static/node/node_modules/@truffle/decoder/dist/interface/contract-decoder.js:117:47)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_ganachF72Qkx/resources/static/node/node_modules/@truffle/decoder/dist/interface/contract-decoder.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:18
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1333

**Closed by davidmurdoch** 2020-10-28 18:18 UTC
