### ISSUE TITLE
MetaMask cannot connect Ganache 1.2.2 next time

### ISSUE THREAD

**Issue by bh4rtp** [trufflesuite/ganache#898] opened 2018-09-08 03:54 UTC
Yesterday for the first connection, after input mnemonic words and password, MetaMask can connect Ganache 1.2.2 correctly. But today, everything keeps the same and it cannot connect Ganache with progress rotating endlessly.

**Comment by bh4rtp** [comment] 2018-09-08 03:55
BTW, I am using MetaMask 4.9.3 in Chrome.

**Comment by bh4rtp** [comment] 2018-09-08 04:02
Sorry, it is ok now with a restore login.

**Comment by seesemichaelj** [comment] 2018-09-08 15:10
@bh4rtp I can't reproduce this issue. While using the default host/port settings in Ganache 1.2.2, and then using the Custom RPC url of `http://127.0.0.1:7545`, I am able to connect to Ganache

**Comment by jdparkinson93** [comment] 2018-09-25 13:55
@bh4rtp @seesemichaelj Works fine for me (using Brave browser, which is based on Chromium). That said, I think I've had a similar problem before but it was resolved by clicking on another network (e.g. main) and then clicking back on the ganache network within MetaMask.

Have you tried that?

**Comment by seesemichaelj** [comment] 2018-09-25 15:53
Closing due to inactivity and not being able to reproduce. If we can get more details, we'd be happy to reopen this! Thanks!

**Closed by seesemichaelj** 2018-09-25 15:53 UTC
Labels: cantrepro, needs more information
