### ISSUE TITLE
System Error when running Ganache 2.0.0 on win32

### ISSUE THREAD

**Issue by aquiladev** [trufflesuite/ganache#1182] opened 2019-03-26 09:41 UTC
PLATFORM: win32
GANACHE VERSION: 2.0.0

EXCEPTION:
```
Error: internal/child_process.js:723
    var string = JSON.stringify(message) + '\n';
                      ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at process.target._send (internal/child_process.js:723:23)
    at process.target.send (internal/child_process.js:634:19)
    at Object.<anonymous> (C:\Users\...\AppData\Local\Temp\ganache119226-15392-186uiqk.kh19\index.js:33:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

    at Socket.child.stderr.on.data (C:\Users\...\AppData\Local\Programs\Ganache\resources\app.asar\src\truffle-integration\projectDetails.js:73:15)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:589:20)
```

**Comment by DiscRiskandBisque** [comment] 2019-03-29 15:56
Hi @aquiladev, can you provide more context for when this error occurred?

**Comment by DiscRiskandBisque** [comment] 2019-03-29 16:00
Related to #1175, #1181

**Comment by aquiladev** [comment] 2019-04-01 12:47
I have project with `truffle-config.js` when I try to add the project in Ganache, I have the error and I cant open the workspace anymore.
It happend because of `truffle-privatekey-provider` package

truffle-config:
```
var PrivateKeyProvider = require("truffle-privatekey-provider");

require('dotenv').config();

module.exports = {
  networks: {
    development: {
      host: "127.0.0.1",      // Localhost (default: none)
      port: 7545,             // Standard Ethereum port (default: none)
      network_id: "*",        // Any network (default: none)
    },

    coverage: {
      host: '127.0.0.1',
      port: 8555,
      network_id: '*',        // eslint-disable-line camelcase
      gas: 0xfffffffffff,
      gasPrice: 0x01
    },

    rinkeby: {
      provider: process.env.RINKEBY_DEV_PKEY ?
        new PrivateKeyProvider(
          process.env.RINKEBY_DEV_PKEY,
          "https://rinkeby.infura.io/v3/" + process.env.INFURA_API_KEY) :
        null,
      network_id: 4
    },
  },

  compilers: {
    solc: {
      version: '0.5.4'
    }
  },

  plugins: ["truffle-security"]
}
```

**Comment by davidmurdoch** [comment] 2019-04-01 15:10
Thanks @aquiladev 	This helped me track the core of the issue down very quickly!

This is caused by attempting to serialize the `PrivateKeyProvider` when sending the truffle config from the child process back to the main process here: https://github.com/trufflesuite/ganache/blob/16f44f84370798a33710f8569be0fe829cddc216/src/truffle-project-loader/index.js#L33

I'm currently exploring solutions and hope to get a release out with the fix shortly.

**Comment by davidmurdoch** [comment] 2019-04-09 15:39
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.

**Closed by davidmurdoch** 2019-04-09 15:39 UTC
Labels: bug
