### ISSUE TITLE
System Error when running Ganache 2.4.0 on win32

### ISSUE THREAD

**Issue by hannespfeiffer** [trufflesuite/ganache#1990] opened 2020-09-14 16:45 UTC
Contract is inheriting from OpenZeppelin's ERC20PresetMinterPauser, but is otherwise empty. Sent a mint() transaction via truffle console. Tried to inspect it in Ganache and this error pops up. Also cannot look at the storage of the contract ("There was an issue decoding your contract. Please file a GitHub Issue by clicking the button below."). 

PLATFORM: win32
GANACHE VERSION: 2.4.0

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 677$ of contract$ DisubToken (ID 28)
    at D:\Programme\Ganache\resources\static\node\node_modules\@truffle\decoder\lib\allocate\storage.ts:181:13
    at Array.map (<anonymous>)
    at allocateContract (D:\Programme\Ganache\resources\static\node\node_modules\@truffle\decoder\lib\allocate\storage.ts:178:59)
    at Object.getStorageAllocations (D:\Programme\Ganache\resources\static\node\node_modules\@truffle\decoder\lib\allocate\storage.ts:23:19)
    at TruffleContractDecoder.<anonymous> (D:\Programme\Ganache\resources\static\node\node_modules\@truffle\decoder\lib\interface\contract-decoder.ts:237:39)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Programme\Ganache\resources\static\node\node_modules\@truffle\decoder\dist\interface\contract-decoder.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:21
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1470

**Closed by davidmurdoch** 2020-10-28 18:21 UTC
