### ISSUE TITLE
System Error when running Ganache 2.3.0 on win32

### ISSUE THREAD

**Issue by pcaversaccio** [trufflesuite/ganache#1722] opened 2020-04-16 12:52 UTC
PLATFORM: win32
GANACHE VERSION: 2.3.0

EXCEPTION:
```
Error: Process exited with code 3221225781
    at ChildProcess.done (C:\Program Files\WindowsApps\GanacheUI_2.3.0.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\promisify-child-process\index.js:64:19)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

**Comment by pcaversaccio** [comment] 2020-04-16 13:00
**More Background Information**
I wanted to create a new Corda project and it started to download PostgreSQL. After maybe 10 seconds I got this error. For Ethereum everything works fine.
Let me know if you need more information.
Best,
Pascal

**Comment by davidmurdoch** [comment] 2020-04-16 19:09
Sorry your are experiencing this issue! Did you try corda again after this? If so, did it work?

**Comment by pcaversaccio** [comment] 2020-04-16 19:20
The problem arised after newly downloading Ganache as a Windows App (I've been using Ganache since version 1). Thus I couldn't start any corda project. I always get a message with the option of either relaunching or open a new GitHub issue whenever I want to launch a corda project.

**Comment by davidmurdoch** [comment] 2020-04-16 19:48
Can you check if you have postgres.exe already running on your machine already? Easy way to do this is to open Task Manager -> Details tab, then look for `postgres.exe`

**Comment by davidmurdoch** [comment] 2020-04-16 19:57
If you were starting Corda via QuickStart, can you copy the contents of `%TEMP%/__ganache_chaindata_{TIMESTAMP_RANDOM}/__ganache__postgres_data/postgres-logfile.log` here?

If you starting Corda as a new Workspace, can you copy the contents of `%APPDATA%/Ganache/workspaces/{workspace-name}/chaindata/__ganache__postgres_data/postgres-logfile.log` here?

Thanks!

**Comment by pcaversaccio** [comment] 2020-04-16 20:44
What I just realised is that I used PostgreSQL for other projects and it is installed on my computer. Re your question, I don't get any log file unfortunately. In the folder I just get 4 different files `notary_node.conf`, `partya_node.conf`, `partyb_node.conf`, and `partyc_node.conf`. Do you need some information from there?

**Comment by pcaversaccio** [comment] 2020-04-16 20:45
That's what I get as a screenshot:
![2020-04-16_22-45-12](https://user-images.githubusercontent.com/25297591/79504975-f7f5f400-8033-11ea-9234-827e72b8e882.png)

**Comment by davidmurdoch** [comment] 2020-04-16 21:10
No, I don't need those files. Can you delete `%APPDATA%/Ganache/extras` and try again?

**Comment by pcaversaccio** [comment] 2020-04-16 21:28
Ok I resolved the problem. I uninstalled Ganache & PostgreSQL and reinstalled Ganache again. Now Corda Quickstart works (even though it takes ca. 5 min until the corda network is established). However, I don't think the PostregSQL uninstallation resolved the issue because I already tried it before and it didn't work (and reinstalled it later).

**Comment by davidmurdoch** [comment] 2020-04-16 21:40
> Ok I resolved the problem. I uninstalled Ganache & PostgreSQL and reinstalled Ganache again. 

Hm, interesting. I don't think you needed to uninstall postgres, as Corda Ganache downloads it's own postgres. What may have happened is that when the Postgres binaries were unpacked something got corrupted. I'll go ahead and close this as "unable to reproduce" for now.

I think what will likely happen is that more users will come across this issue over the next few weeks and I'll get a better feel for what might be going wrong.

> even though it takes ca. 5 min until the corda network is established

This is very normal for an initial Corda network bootstrap and launch. The next release, v2.3.1 will come with some optimizations that will make things a little faster on successive launches.

**Closed by davidmurdoch** 2020-04-16 21:40 UTC
Labels: bug, corda, windows

**Comment by pcaversaccio** [comment] 2020-04-17 07:01
@davidmurdoch yes that was also my first guess that files got corrupted. In any case, thx for the support!
