### ISSUE TITLE
System Error when running Ganache 2.4.0 on win32

### ISSUE THREAD

**Issue by sacredwx** [trufflesuite/ganache#1785] opened 2020-05-11 17:18 UTC
_Running Ganache on 8545 while geth runs on 8545.
It tells me I have an already listening port on 8545,
I change to 7545, restart and get this error.
When closing the app and reopening it - the issue is gone._

PLATFORM: win32
GANACHE VERSION: 2.4.0

EXCEPTION:
```
Error: connection not open
    at WebsocketProvider.send (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\web3-providers-ws\src\index.js:282:18)
    at Timeout._onTimeout (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\web3-providers-ws\src\index.js:267:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:15
closing as duplicate of https://github.com/trufflesuite/ganache/issues/2039

**Closed by davidmurdoch** 2020-10-28 18:15 UTC
