### ISSUE TITLE
System Error when running Ganache 1.0.0 on win32

### ISSUE THREAD

**Issue by icocheck** [trufflesuite/ganache#82] opened 2017-11-16 05:23 UTC
PLATFORM: win32
GANACHE VERSION: 1.0.0

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by Shrugs** [comment] 2017-11-16 06:54
Same error on darwin with v1.0.0

TestRPC has the same issue; here are the testrpc crash logs.

```

**Comment by Shrugs** [comment] 2017-11-16 06:58
truffle throws within the before block in `truffle test` somewhere here: https://github.com/trufflesuite/truffle-core/blob/develop/lib/testing/testrunner.js#L42

because it can't connect to the testrpc instance after it crashes

```
  Contract: InfiniteCappedCrowdsale
    2) "before all" hook: prepare suite
```

**Comment by Shrugs** [comment] 2017-11-16 07:03
Looks like this is a testrpc issue, so I'll move discussion to that repo.

**Comment by Shrugs** [comment] 2017-11-16 07:12
For me, this is caused by truffle's snapshotting, so the solution is to just not use truffle's `contract()` method for tests and replace it with a normal `describe` block. You can request accounts and deploy contracts on your own, ignoring the snapshotting feature.

**Comment by benjamincburns** [comment] 2017-11-30 22:15
Thanks for all the investigation into this one @Shrugs! I'll close this one as the issue is better tracked over on [trufflesuite/ganache-cli](https://github.com/trufflesuite/ganache-cli).

**Closed by benjamincburns** 2017-11-30 22:15 UTC
