### ISSUE TITLE
System Error when running Ganache 2.1.2 on darwin

### ISSUE THREAD

**Issue by makoto** [trufflesuite/ganache#1520] opened 2019-12-12 12:14 UTC
PLATFORM: darwin
GANACHE VERSION: 2.1.2

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 1989$ of contract$ Deployer (ID 1318)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:164:19)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:161:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:117:47)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+238531ms: eth_blockNumber
T+238531ms: eth_blockNumber
T+238531ms: eth_blockNumber
T+238531ms: eth_blockNumber
T+238531ms: eth_blockNumber
T+238531ms: eth_blockNumber
T+238531ms: eth_blockNumber
T+238531ms: eth_blockNumber
T+238587ms: eth_getTransactionCount
T+238636ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238672ms: eth_blockNumber
T+238707ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238747ms: eth_blockNumber
T+238785ms: eth_blockNumber
T+238822ms: eth_getBlockByNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238864ms: eth_blockNumber
T+238948ms: eth_blockNumber
T+238948ms: eth_blockNumber
T+238948ms: eth_getBalance
T+239067ms: eth_getBlockByNumber
T+239109ms: eth_blockNumber
T+239109ms: eth_getBlockByNumber
T+239109ms: eth_getBalance
T+239109ms: net_version
T+239161ms: eth_getBlockByNumber
T+239197ms: net_version
T+239197ms: eth_getCode
T+239235ms: eth_getTransactionCount
T+239271ms: eth_getBalance
T+239346ms: eth_blockNumber
T+240313ms: eth_blockNumber
T+241909ms: net_version
T+241964ms: net_version
T+242016ms: eth_blockNumber
T+242016ms: eth_getBalance
T+242016ms: eth_getBalance
T+242103ms: net_version
T+242155ms: eth_getBalance
T+242254ms: eth_getBalance
T+242353ms: eth_getCode
T+242504ms: eth_gasPrice
T+242576ms: eth_getCode
T+242631ms: eth_getBlockByNumber
T+243454ms: eth_blockNumber
T+243454ms: eth_getBalance
T+243454ms: eth_blockNumber
T+244008ms: eth_getTransactionCount
T+244604ms: eth_blockNumber
T+244604ms: eth_blockNumber
T+245107ms: eth_getBlockByNumber
T+245181ms: eth_getTransactionCount
T+245254ms: eth_sendRawTransaction
T+247071ms:   Transaction: 0xf29961abba20c2e48fc9c27e40c942fb39e9392a0557fad32704c64a169ad5ce
T+247071ms:   Gas usage: 2421873
T+247071ms:   Block Number: 5
T+247071ms:   Block Time: Thu Dec 12 2019 12:13:18 GMT+0000 (GMT)
T+247071ms: eth_getBlockByNumber
T+247224ms: eth_getTransactionCount
T+247224ms: eth_blockNumber
T+247224ms: eth_blockNumber
T+247224ms: eth_getBlockByNumber
T+247224ms: eth_getTransactionCount
T+247224ms: eth_getTransactionCount
T+247224ms: eth_getTransactionReceipt
T+247224ms: eth_getTransactionReceipt
T+247224ms: eth_getTransactionReceipt
T+247263ms: eth_getBalance
T+247263ms: eth_getTransactionReceipt
T+247298ms: eth_getTransactionReceipt
T+247298ms: eth_getTransactionCount
T+247334ms: eth_getTransactionReceipt
T+247370ms: eth_getTransactionReceipt
T+247406ms: eth_getTransactionReceipt
T+247445ms: eth_getBlockByNumber
T+248582ms: net_version
T+248582ms: eth_getBlockByNumber
T+248582ms: net_version
T+248623ms: eth_getCode
T+255107ms: eth_blockNumber
T+255160ms: eth_getBlockByNumber
T+256780ms: eth_blockNumber
T+256815ms: eth_getBlockByNumber
T+258422ms: net_version
T+258462ms: eth_getBlockByNumber
T+258502ms: net_version
T+258551ms: eth_getCode
T+261984ms: net_version
T+262569ms: net_version
T+262652ms: eth_unsubscribe
T+262652ms: eth_unsubscribe
T+262652ms: eth_unsubscribe
T+262652ms: eth_unsubscribe
T+262652ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:20
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1470

**Closed** 2020-10-28 18:21 UTC
