### ISSUE TITLE
Decoding Error when running Ganache 2.0.3 on win32

### ISSUE THREAD

**Issue by Thiaoouba-noaccount** [trufflesuite/ganache#1970] opened 2020-08-27 03:29 UTC
PLATFORM: win32
GANACHE VERSION: 2.0.3

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 2182$ of contract$ ThiaooubaToken (ID 156)
    at vars.concat.linearizedBaseContractsFromBase.map (C:\Program Files\WindowsApps\Ganache_2.0.3.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:158:19)
    at Array.map (native)
    at allocateContract (C:\Program Files\WindowsApps\Ganache_2.0.3.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:155:61)
    at Object.getStorageAllocations (C:\Program Files\WindowsApps\Ganache_2.0.3.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.0.3.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:113:47)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\WindowsApps\Ganache_2.0.3.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:22
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1470

**Closed by davidmurdoch** 2020-10-28 18:22 UTC
