### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by PopTudor** [trufflesuite/ganache#746] opened 2018-06-13 10:04 UTC
just reporting...called a .call on a get(key) method from web3 js

PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRINUSE 127.0.0.1:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":5778,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by seesemichaelj** [comment] 2018-06-13 17:14
Hey @PopTudor, thanks for reporting this! Sounds like the error you're reporting is not the original error? There's a bug where if an error pops up, and you press relaunch, a process hangs around still listening to the RPC port. That's why when you start Ganache again, this error appears.

Unfortunately, I'm going to have to close this because EADDRINUSE bug is being tracked in #665. If you encounter the original issue again, please report that so we can try to solve the root cause.

You can change your settings file `~/Library/Application\ Support/Ganache/Settings` to get back up and running (changing the port to something else). Otherwise, make sure all Ganache processes are killed before starting Ganache.

**Closed by seesemichaelj** 2018-06-13 17:14 UTC

**Comment by PopTudor** [comment] 2018-06-14 09:36
no problem... Ganache just show restart/report ....tried restart but I was keep seeing that screen without option to bypass so I thought will leave me alone after reporting and it did.
