### ISSUE TITLE
System Error when running Ganache 2.1.2 on darwin

### ISSUE THREAD

**Issue by minton1** [trufflesuite/ganache#1681] opened 2020-03-27 20:48 UTC
PLATFORM: darwin
GANACHE VERSION: 2.1.2

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 289$ of contract$ Token1 (ID 262)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:164:19)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:161:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:117:47)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+720315ms: eth_getBlockByNumber
T+720417ms: eth_getBlockByNumber
T+720558ms: eth_getBlockByNumber
T+720679ms: eth_getBlockByNumber
T+720691ms: eth_getBlockByNumber
T+720737ms: eth_getBlockByNumber
T+720928ms: eth_getBlockByNumber
T+720943ms: eth_getBlockByNumber
T+721319ms: eth_getBlockByNumber
T+721419ms: eth_getBlockByNumber
T+721561ms: eth_getBlockByNumber
T+721682ms: eth_getBlockByNumber
T+721694ms: eth_getBlockByNumber
T+721738ms: eth_getBlockByNumber
T+721929ms: eth_getBlockByNumber
T+721945ms: eth_getBlockByNumber
T+722324ms: eth_getBlockByNumber
T+722425ms: eth_getBlockByNumber
T+722563ms: eth_getBlockByNumber
T+722685ms: eth_getBlockByNumber
T+722697ms: eth_getBlockByNumber
T+722739ms: eth_getBlockByNumber
T+722934ms: eth_getBlockByNumber
T+722949ms: eth_getBlockByNumber
T+723324ms: eth_getBlockByNumber
T+723428ms: eth_getBlockByNumber
T+723568ms: eth_getBlockByNumber
T+723689ms: eth_getBlockByNumber
T+723701ms: eth_getBlockByNumber
T+723743ms: eth_getBlockByNumber
T+723938ms: eth_getBlockByNumber
T+723950ms: eth_getBlockByNumber
T+724329ms: eth_getBlockByNumber
T+724428ms: eth_getBlockByNumber
T+724570ms: eth_getBlockByNumber
T+724695ms: eth_getBlockByNumber
T+724706ms: eth_getBlockByNumber
T+724747ms: eth_getBlockByNumber
T+724939ms: eth_getBlockByNumber
T+724954ms: eth_getBlockByNumber
T+725334ms: eth_getBlockByNumber
T+725434ms: eth_getBlockByNumber
T+725574ms: eth_getBlockByNumber
T+725698ms: eth_getBlockByNumber
T+725710ms: eth_getBlockByNumber
T+725748ms: eth_getBlockByNumber
T+725939ms: eth_getBlockByNumber
T+725951ms: eth_getBlockByNumber
T+726338ms: eth_getBlockByNumber
T+726438ms: eth_getBlockByNumber
T+726579ms: eth_getBlockByNumber
T+726701ms: eth_getBlockByNumber
T+726714ms: eth_getBlockByNumber
T+726754ms: eth_getBlockByNumber
T+726944ms: eth_getBlockByNumber
T+726959ms: eth_getBlockByNumber
T+727339ms: eth_getBlockByNumber
T+727438ms: eth_getBlockByNumber
T+727583ms: eth_getBlockByNumber
T+727706ms: eth_getBlockByNumber
T+727718ms: eth_getBlockByNumber
T+727756ms: eth_getBlockByNumber
T+727947ms: eth_getBlockByNumber
T+727959ms: eth_getBlockByNumber
T+728343ms: eth_getBlockByNumber
T+728439ms: eth_getBlockByNumber
T+728584ms: eth_getBlockByNumber
T+728709ms: eth_getBlockByNumber
T+728722ms: eth_getBlockByNumber
T+728758ms: eth_getBlockByNumber
T+728951ms: eth_getBlockByNumber
T+728966ms: eth_getBlockByNumber
T+729287ms: eth_blockNumber
T+729348ms: eth_getBlockByNumber
T+729440ms: eth_getBlockByNumber
T+729588ms: eth_getBlockByNumber
T+729712ms: eth_getBlockByNumber
T+729725ms: eth_getBlockByNumber
T+729760ms: eth_getBlockByNumber
T+729956ms: eth_getBlockByNumber
T+729971ms: eth_getBlockByNumber
T+730351ms: eth_getBlockByNumber
T+730443ms: eth_getBlockByNumber
T+730591ms: eth_getBlockByNumber
T+730717ms: eth_getBlockByNumber
T+730729ms: eth_getBlockByNumber
T+730760ms: eth_getBlockByNumber
T+730957ms: eth_getBlockByNumber
T+730968ms: eth_getBlockByNumber
T+731356ms: eth_getBlockByNumber
T+731449ms: eth_getBlockByNumber
T+731594ms: eth_getBlockByNumber
T+731721ms: eth_getBlockByNumber
T+731733ms: eth_getBlockByNumber
T+731762ms: eth_getBlockByNumber
T+731960ms: eth_getBlockByNumber
T+731977ms: eth_getBlockByNumber
T+732358ms: eth_getBlockByNumber
T+732450ms: eth_getBlockByNumber
T+732599ms: eth_getBlockByNumber
T+732727ms: eth_getBlockByNumber
T+732727ms: eth_getBlockByNumber
T+732767ms: eth_getBlockByNumber
T+732965ms: eth_getBlockByNumber
T+732977ms: eth_getBlockByNumber
T+733357ms: eth_getBlockByNumber
T+733451ms: eth_getBlockByNumber
T+733602ms: eth_getBlockByNumber
T+733728ms: eth_getBlockByNumber
T+733743ms: eth_getBlockByNumber
T+733771ms: eth_getBlockByNumber
T+733971ms: eth_getBlockByNumber
T+733985ms: eth_getBlockByNumber
T+734397ms: eth_getBlockByNumber
T+734455ms: eth_getBlockByNumber
T+734603ms: eth_getBlockByNumber
T+734729ms: eth_getBlockByNumber
T+734747ms: eth_getBlockByNumber
T+734773ms: eth_getBlockByNumber
T+734969ms: eth_getBlockByNumber
T+734981ms: eth_getBlockByNumber
T+735360ms: eth_getBlockByNumber
T+735455ms: eth_getBlockByNumber
T+735606ms: eth_getBlockByNumber
T+735733ms: eth_getBlockByNumber
T+735746ms: eth_getBlockByNumber
T+735779ms: eth_getBlockByNumber
T+735974ms: eth_getBlockByNumber
T+735990ms: eth_getBlockByNumber
T+736362ms: eth_getBlockByNumber
T+736455ms: eth_getBlockByNumber
T+736609ms: eth_getBlockByNumber
T+736738ms: eth_getBlockByNumber
T+736751ms: eth_getBlockByNumber
T+736779ms: eth_getBlockByNumber
T+736972ms: eth_getBlockByNumber
T+736989ms: eth_getBlockByNumber
T+737367ms: eth_getBlockByNumber
T+737457ms: eth_getBlockByNumber
T+737613ms: eth_getBlockByNumber
T+737741ms: eth_getBlockByNumber
T+737753ms: eth_getBlockByNumber
T+737778ms: eth_getBlockByNumber
T+737975ms: eth_getBlockByNumber
T+737975ms: eth_getBlockByNumber
T+738018ms: net_version
T+738150ms: net_version
T+738175ms: eth_unsubscribe
T+738175ms: eth_unsubscribe
T+738190ms: eth_unsubscribe
T+738190ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:18
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1333

**Closed by davidmurdoch** 2020-10-28 18:18 UTC
