### ISSUE TITLE
Decoding Error when running Ganache 2.4.0 on linux

### ISSUE THREAD

**Issue by atenjin** [trufflesuite/ganache#1865] opened 2020-06-22 15:14 UTC
PLATFORM: linux
GANACHE VERSION: 2.4.0

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 3033$ of contract$ ERC1155Bill (ID 3010)
    at /tmp/.mount_ganachktON6Y/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:181:13
    at Array.map (<anonymous>)
    at allocateContract (/tmp/.mount_ganachktON6Y/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:178:59)
    at Object.getStorageAllocations (/tmp/.mount_ganachktON6Y/resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:23:19)
    at TruffleContractDecoder.<anonymous> (/tmp/.mount_ganachktON6Y/resources/static/node/node_modules/@truffle/decoder/lib/interface/contract-decoder.ts:237:39)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_ganachktON6Y/resources/static/node/node_modules/@truffle/decoder/dist/interface/contract-decoder.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by AtenJin** [comment] 2020-06-22 15:16
project link is :
https://github.com/KhepriJin/ERC1155Bill/tree/ganache-decode-error

and after do `truffle migration --reset`, the contracts "ERC1155Bill"  would show like:
![image](https://user-images.githubusercontent.com/5023721/85304544-75c7f700-b4de-11ea-9369-279ca69a2bd4.png)

**Comment by davidmurdoch** [comment] 2020-10-28 18:22
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1470

**Closed by davidmurdoch** 2020-10-28 18:22 UTC
