### ISSUE TITLE
System Error when running Ganache 2.0.2 on darwin

### ISSUE THREAD

**Issue by simon-liu** [trufflesuite/ganache#1341] opened 2019-07-03 07:06 UTC
PLATFORM: darwin
GANACHE VERSION: 2.0.2

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 1172$ of contract$ NSNToken (ID 425)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:158:19)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:155:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:113:47)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.2) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"/Users/liuzenglu/Library/Application Support/Ganache/workspaces/exciting-increase/chaindata"}
T+137ms: Ganache started successfully!
T+137ms: Waiting for requests...
T+186ms: eth_getCode
T+195ms: eth_subscribe
T+203ms: eth_getLogs
T+217ms: eth_subscribe
T+225ms: eth_getCode
T+2008ms: eth_blockNumber
T+2737ms: eth_getBlockByNumber
T+6678ms: net_version
T+6702ms: eth_unsubscribe
T+6716ms: eth_unsubscribe
T+6726ms: eth_unsubscribe
T+6739ms: eth_unsubscribe
T+6739ms: eth_unsubscribe
```

**Comment by techieanant** [comment] 2019-07-21 23:35
Getting same error on win32. Help from Ganache team would be appreciated.

**Comment by davidmurdoch** [comment] 2020-10-28 18:21
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1470

**Closed by davidmurdoch** 2020-10-28 18:21 UTC
