### ISSUE TITLE
Can't make app window smaller

### ISSUE THREAD

**Issue by bmmpxf** [trufflesuite/ganache#116] opened 2017-11-22 00:43 UTC
## Issue Type

Bug

## Description

There appears to be a minimum window size (height and width) in Ganache, and I can't make the app any smaller than it. This is awkward, as this minimum height appears to be larger than my screen height.

![image](https://user-images.githubusercontent.com/506694/33104051-fb37baf2-ceda-11e7-9891-3c58616666ed.png)

## Steps to reproduce

* Open Ganache
* Try to resize the window
* Fail

# Version

Windows 10
Ganache v1.0.1

**Comment by ajhurliman** [comment] 2017-12-24 22:48
same problem on v1.0.1, high Sierra

**Comment by benjamincburns** [comment] 2018-01-12 06:17
This is by design at the moment. The problem is that if you make the window too narrow, there isn't enough room to display all the information in the layout, and things start to draw over the top of one another. We'll fix this eventually, but until then you wouldn't want to resize it to be more narrow than it already is, anyway.

**Comment by bmmpxf** [comment] 2018-01-12 18:35
I can certainly be patient for UI improvements. But there's a lot of white space currently in the Balance area. Can this area not be squeezed now? This app takes up most of my screen (and even scrolls off the bottom of the screen, so the full window is never able to be shown), and at a font size much larger than any other application. Even a Zoom Text In/Out would be a benefit. Just some ideas.

**Comment by ajhurliman** [comment] 2018-01-13 01:47
Thanks for responding, not a big deal. FYI, though, it takes up like 80% of a 13" MacBook; I would be very gracious if it were fixed, but I completely understand that this would take backseat to other issues.

**Comment by benjamincburns** [comment] 2018-01-15 04:22
FWIW I develop on a 13" MacBook without an external monitor. I feel your pain.

**Comment by connormcn37** [comment] 2018-02-19 22:44
Since scrolling through transactions is already a feature, vertical resizing should at least be implemented. I can never see the last transaction or two because Ganache is too tall. I get that horizontal resizing might break something, but vertical shouldn't create any problems.

**Comment by deltonmyalil** [comment] 2018-04-27 08:24
Any idea how to get the private key of the 9th account? It is not scrolling and I cant hit the key button.

**Comment by seesemichaelj** [comment] 2019-01-04 05:34
Closing this as #779 fixed this

**Closed by seesemichaelj** 2019-01-04 05:34 UTC
