### ISSUE TITLE
System Error when running Ganache 2.3.1 on win32

### ISSUE THREAD

**Issue by ifuseandprint** [trufflesuite/ganache#1736] opened 2020-04-21 06:04 UTC
PLATFORM: win32
GANACHE VERSION: 2.3.1

EXCEPTION:
```
Error: Process exited with code 3221225781
    at ChildProcess.done (C:\Program Files\WindowsApps\GanacheUI_2.3.1.0_x64__5dg5pnz03psnj\app\resources\app.asar\node_modules\promisify-child-process\index.js:64:19)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

**Comment by davidmurdoch** [comment] 2020-04-22 15:54
Sorry you are experiencing this issue!

This error is caused by a missing sub-dependency in Ganache's Windows postgresql package. This dependency has since been added to the package.

To fix this please navigate to `%APPDATA%/Ganache` and then delete the `extras` folder. The next time you start Ganache and load a Corda network the updated PostgreSQL package will be downloaded automatically.

Please let me know if this issue is not resolved by following the above steps.

Thanks!

**Closed by davidmurdoch** 2020-04-22 15:54 UTC
Labels: bug, windows
