### ISSUE TITLE
System Error when running Ganache 2.0.3 on win32

### ISSUE THREAD

**Issue by dontcryme** [trufflesuite/ganache#1353] opened 2019-07-11 06:17 UTC
If I click transactions menu, below error occur.

PLATFORM: win32(Windows 10 x64)
GANACHE VERSION: 2.0.3

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 939$ of contract$ CartoonToken (ID 771)
    at vars.concat.linearizedBaseContractsFromBase.map (C:\Program Files\WindowsApps\Ganache_2.0.3.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:158:19)
    at Array.map (native)
    at allocateContract (C:\Program Files\WindowsApps\Ganache_2.0.3.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:155:61)
    at Object.getStorageAllocations (C:\Program Files\WindowsApps\Ganache_2.0.3.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.0.3.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:113:47)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\WindowsApps\Ganache_2.0.3.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+0ms: eth_unsubscribe
T+2ms: eth_unsubscribe
T+2ms: eth_unsubscribe
T+2ms: eth_unsubscribe
T+861ms: Starting server (version 2.0.3) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","default_balance_ether":100,"hostname":"127.0.0.1","locked":false,"network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[],"verbose":false,"vmErrorsOnRPCResponse":true}
T+885ms: Ganache started successfully!
T+885ms: Waiting for requests...
T+1144ms: eth_getCode
T+1167ms: eth_subscribe
T+1167ms: eth_getLogs
T+1167ms: eth_subscribe
T+1196ms: eth_getCode
T+12513ms: eth_getBlockByNumber
T+12556ms: eth_getBlockByNumber
T+12597ms: eth_getBlockByNumber
T+12644ms: eth_getBlockByNumber
T+12676ms: eth_getBlockByNumber
T+12715ms: eth_getBlockByNumber
T+12750ms: net_version
T+12816ms: eth_getBlockByNumber
T+12854ms: eth_getBlockByNumber
T+12899ms: eth_getBlockByNumber
T+12935ms: eth_getBlockByNumber
T+12985ms: eth_getBlockByNumber
T+13028ms: eth_getBlockByNumber
T+13053ms: eth_getBlockByNumber
T+13096ms: eth_getBlockByNumber
T+13138ms: eth_getBlockByNumber
T+13178ms: eth_getBlockByNumber
T+13217ms: eth_getBlockByNumber
T+13251ms: eth_getBlockByNumber
T+13280ms: eth_getBlockByNumber
T+13325ms: eth_getBlockByNumber
T+13369ms: eth_getBlockByNumber
T+13409ms: eth_getBlockByNumber
T+13453ms: eth_getBlockByNumber
T+13489ms: eth_getBlockByNumber
T+13522ms: eth_getBlockByNumber
T+13569ms: eth_getBlockByNumber
T+13622ms: eth_getBlockByNumber
T+13667ms: eth_getBlockByNumber
T+13706ms: eth_getBlockByNumber
T+13740ms: eth_getBlockByNumber
T+13782ms: eth_getBlockByNumber
T+13819ms: eth_getBlockByNumber
T+13859ms: eth_getBlockByNumber
T+13891ms: eth_getBlockByNumber
T+13923ms: eth_getBlockByNumber
T+13948ms: eth_getBlockByNumber
T+13980ms: eth_estimateGas
T+14019ms: eth_getBlockByNumber
T+14070ms: eth_blockNumber
T+14123ms: eth_getTransactionCount
T+14164ms: eth_sendRawTransaction
T+19118ms:   Transaction: 0xcf59e982e32f7f5b6a0df1b3545cd31cd7a147ce14079705702fd2a362a391b6
T+19118ms:   Contract created: 0x38025b65105e51cc517599081753196c6a559259
T+19118ms:   Gas usage: 3379705
T+19118ms:   Block Number: 1
T+19157ms:   Block Time: Thu Jul 11 2019 15:11:11 GMT+0900 (대한민국 표준시)
T+19184ms: eth_getBlockByNumber
T+19217ms: eth_getTransactionReceipt
T+19249ms: eth_getCode
T+19286ms: eth_getTransactionByHash
T+19328ms: eth_getBlockByNumber
T+19369ms: eth_getBalance
T+19405ms: eth_getBlockByNumber
T+19448ms: eth_getBlockByNumber
T+19488ms: eth_getBlockByNumber
T+19530ms: eth_estimateGas
T+19570ms: eth_getBlockByNumber
T+19607ms: eth_blockNumber
T+19633ms: eth_sendRawTransaction
T+19666ms:   Transaction: 0xd165e4d6e292dd4c905874e5f53a794f8ceec449b52f0ed47f7963121ae91d2a
T+19666ms:   Contract created: 0x34288c753e0ac4729f5ab15785faf10777c08fdf
T+19666ms:   Gas usage: 1386652
T+19666ms:   Block Number: 2
T+19699ms:   Block Time: Thu Jul 11 2019 15:11:11 GMT+0900 (대한민국 표준시)
T+19732ms: eth_getBlockByNumber
T+19766ms: eth_getTransactionReceipt
T+19799ms: eth_getCode
T+19825ms: eth_getTransactionByHash
T+19856ms: eth_getBlockByNumber
T+19891ms: eth_getBalance
T+33388ms: eth_sendTransaction
T+98609ms: eth_accounts
T+109356ms: eth_sendTransaction
T+110816ms:   Transaction: 0x788bca439d71054ed1e34a3a6a23015311f66c21c4ba4306468d131078f7875c
T+110816ms:   Gas usage: 167290
T+110816ms:   Block Number: 3
T+110816ms:   Block Time: Thu Jul 11 2019 15:12:47 GMT+0900 (대한민국 표준시)
T+110835ms: eth_getBlockByNumber
T+110835ms: eth_subscribe
T+121571ms: eth_call
T+135021ms: eth_unsubscribe
T+136003ms: eth_accounts
T+141435ms: eth_call
T+178089ms: net_version
T+178130ms: eth_unsubscribe
T+178144ms: eth_unsubscribe
T+178163ms: eth_unsubscribe
T+178163ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:21
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1470

**Closed by davidmurdoch** 2020-10-28 18:21 UTC
