### ISSUE TITLE
System Error when running Ganache 2.4.0 on win32

### ISSUE THREAD

**Issue by biahoi** [trufflesuite/ganache#2001] opened 2020-09-21 14:00 UTC
Truffle v5.1.33 (core: 5.1.33)
Node v12.18.3
solidity 0.5.9;

running Ganache truffle on local "development" mode.

When I tried to include following Provable API code into my contract:
```
constructor() public payable {
        provable_setProof(proofType_Ledger);
    }
```

then: Truffle says:
```

> Something went wrong while attempting to connect to the network. Check your network configuration.

Could not connect to your Ethereum client with the following parameters:


```

Ganache pop up:

PLATFORM: win32
GANACHE VERSION: 2.4.0

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\web3-providers-ws\node_modules\web3-core-helpers\src\errors.js:35:16)
    at WebsocketProvider._timeout (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\web3-providers-ws\src\index.js:255:48)
    at W3CWebSocket.connection.onclose (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\web3-providers-ws\src\index.js:155:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\yaeti\lib\EventTarget.js:107:17)
    at W3CWebSocket.onClose (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@web3-js\websocket\lib\W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@web3-js\websocket\lib\W3CWebSocket.js:201:17)
    at WebSocketConnection.emit (events.js:210:5)
    at WebSocketConnection.handleSocketClose (C:\Program Files\WindowsApps\GanacheUI_2.4.0.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\@web3-js\websocket\lib\WebSocketConnection.js:389:14)
    at Socket.emit (events.js:210:5)
    at TCP.<anonymous> (net.js:658:12)
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:16
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1770

**Closed by davidmurdoch** 2020-10-28 18:16 UTC
