### ISSUE TITLE
System Error when running Ganache 1.0.0 on darwin

### ISSUE THREAD

**Issue by danfinlay** [trufflesuite/ganache#104] opened 2017-11-17 22:20 UTC
I had sent a tx a bit earlier, but it was mostly just metamask doing its loop of polling for blocks, balances, & nonces.

PLATFORM: darwin
GANACHE VERSION: 1.0.0

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by danfinlay** [comment] 2017-11-17 22:21
Oh! I just noticed it looks like this also may have happened at the same time as I hit `http://localhost:8545/` in my browser.

**Comment by benjamincburns** [comment] 2017-11-30 22:19
@danfinlay I've recently removed the heartbeat functionality and replaced it with more run-of-the process monitoring. Hopefully that'll help to surface the root cause of issues which were previously causing the heartbeat to die. Unfortunately, without more to go on, I have to treat this as a duplicate of #83.

Not sure when we'll be making the next release (within a few weeks, I think), but if you want to clone the repo and do some testing from current `master`, I'd be much obliged.

**Closed by benjamincburns** 2017-11-30 22:19 UTC
