### ISSUE TITLE
TypeError: n.getAllResults is not a function

### ISSUE THREAD

**Issue by nandubatchu** [trufflesuite/ganache#718] opened 2018-06-09 10:10 UTC
I have tried to connect to the ganache instance with the web3.py module and tried to install a Filter to track the 'latest' blocks. While installing a filter worked for 'pending' blocks.

PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRINUSE 127.0.0.1:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by seesemichaelj** [comment] 2018-06-10 18:39
Thanks for reporting this! I'm not quite sure I understand the steps you took to get to this error? Perhaps you could elaborate more?

The generic error is being tracked in #665. You can get your Ganache back up and running by changing the port in the `~/Library/Application\ Support/Ganache/Settings` file.

**Comment by nandubatchu** [comment] 2018-06-10 18:48
I am sorry @seesemichaelj I accidentally submitted the wrong error. Please find the original error here:

TypeError: n.getAllResults is not a function
    at o.d.getFilterLogs (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/web3-provider-engine/subproviders/filters.js:201:1)
    at Timeout._onTimeout (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/web3-provider-engine/subproviders/filters.js:82:1)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)

**Comment by seesemichaelj** [comment] 2018-06-10 18:53
Ah that's better, thanks!

**Comment by seesemichaelj** [comment] 2018-06-10 18:55
Actually, this is a duplicate of #709

**Closed by seesemichaelj** 2018-06-10 18:55 UTC
Labels: bug

**Comment by nandubatchu** [comment] 2018-06-10 19:03
@seesemichaelj Does all types of filters work with Ganache?

**Comment by seesemichaelj** [comment] 2018-06-10 19:19
@nandubatchu Unfortunately, I do not know the answer to that question as I recently started on the Truffle/Ganache team. I don't see any reason why all types of filters wouldn't work. When we have the time addressing #709, we'll look into answering this question
