### ISSUE TITLE
System Error when running Ganache 2.4.0 on darwin

### ISSUE THREAD

**Issue by ebadiere** [trufflesuite/ganache#1874] opened 2020-06-27 02:18 UTC
I ran into the error below after deploying, (truffle migrate), the contracts in Kyber workshop project:  https://github.com/KyberNetwork/workshop/

PLATFORM: darwin
GANACHE VERSION: 2.4.0

EXCEPTION:
```
Error: connection not open
    at WebsocketProvider.send (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/web3-providers-ws/src/index.js:282:18)
    at RequestManager.send (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/web3-core-requestmanager/src/index.js:132:66)
    at sendRequest (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/web3-core-method/src/index.js:560:42)
    at Eth.send [as getBlock] (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/web3-core-method/src/index.js:581:13)
    at ProjectsWatcher.handleBlock (/Applications/Ganache.app/Contents/Resources/static/node/truffle-integration/projectsWatcher.js:178:46)
    at Subscription.<anonymous> (/Applications/Ganache.app/Contents/Resources/static/node/truffle-integration/projectsWatcher.js:57:20)
    at Subscription.emit (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/eventemitter3/index.js:181:35)
    at /Applications/Ganache.app/Contents/Resources/static/node/node_modules/web3-core-subscriptions/src/subscription.js:267:35
    at Array.forEach (<anonymous>)
    at Object.callback (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/web3-core-subscriptions/src/subscription.js:261:28)
    at requestManagerNotification (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/web3-core-requestmanager/src/index.js:103:65)
    at /Applications/Ganache.app/Contents/Resources/static/node/node_modules/web3-providers-ws/src/index.js:122:25
    at Array.forEach (<anonymous>)
    at /Applications/Ganache.app/Contents/Resources/static/node/node_modules/web3-providers-ws/src/index.js:120:45
    at Array.forEach (<anonymous>)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/web3-providers-ws/src/index.js:104:36)
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:14
closing as duplicate of https://github.com/trufflesuite/ganache/issues/2039

**Closed by davidmurdoch** 2020-10-28 18:14 UTC
