### ISSUE TITLE
System Error when running Ganache 1.0.1 on darwin

### ISSUE THREAD

**Issue by TheOriginalTrubador** [trufflesuite/ganache#105] opened 2017-11-18 23:41 UTC
**Environment:** MacOS 10.12.6, Ganache 1.0.1 (100 Accounts, Automine, Default Gas Limit & Gas Price), Truffle v4.0.1, Solidity v0.4.18

**Scenario:** Create 100 accounts, move 99.99 Eth from accounts[10] to accounts[99] to accounts[2].

**Methodology:** From the Truffle Console, execute a simple loop:

```javascript
for (var i = 10; i < 99; i++){
  web3.eth.sendTransaction({from: web3.eth.accounts[i], to: web3.eth.accounts[2], value: web3.toWei(99.99, 'ether')})
}
```
App crash occurred after 1 transaction confirming.

Repeating test either forces a full crash, or unresponsive UI.

PLATFORM: darwin
GANACHE VERSION: 1.0.1

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by benjamincburns** [comment] 2017-11-30 22:20
Closing this as duplicate of #83.  Will comment on that case shortly.

**Closed by benjamincburns** 2017-11-30 22:20 UTC
Labels: duplicate
