### ISSUE TITLE
Ganache launch stuck when changing port on mac

### ISSUE THREAD

**Issue by ben-kaufman** [trufflesuite/ganache#85] opened 2017-11-16 08:41 UTC
Hey there, 

I just noticed when I change the port number and then click on save and restart Ganache gets stuck on the launch animation screen. Closing Ganache completely and reopening it solves the problem.
I am using Mac OS High Sierra. 

Thanks,
Ben

**Comment by melnikaite** [comment] 2017-11-16 10:36
The same issue when change chain settings

**Comment by BenKaufman10** [comment] 2017-11-16 13:08
It doesn't happen when I change back to the original default port.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LiveDuo** [comment] 2018-01-15 11:42
Issue persists as of today. I am using windows 10.

**Comment by Alko89** [comment] 2018-03-06 18:38
I can confirm the same when changing the IP here on Arch Linux.

**Comment by seesemichaelj** [comment] 2018-06-08 06:40
This actually ended up being a duplicate of #665. We have addressed it in PR #712 and it will go into the next release

**Closed by seesemichaelj** 2018-06-08 06:40 UTC
