### ISSUE TITLE
System Error when running Ganache 2.1.0 on darwin

### ISSUE THREAD

**Issue by dkhroad** [trufflesuite/ganache#1389] opened 2019-08-14 22:57 UTC
PLATFORM: darwin
GANACHE VERSION: 2.1.0

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 1449$ of contract$ SupplyChain (ID 1340)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:158:19)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:155:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:113:47)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.1.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"/Users/dkhroad/Library/Application Support/Ganache/workspaces/supply-chain/chaindata"}
T+238ms: Ganache started successfully!
T+238ms: Waiting for requests...
T+278ms: eth_getCode
T+299ms: eth_subscribe
T+319ms: eth_getLogs
T+333ms: eth_subscribe
T+354ms: eth_getCode
T+375ms: eth_getCode
T+391ms: eth_getCode
T+408ms: eth_getCode
T+425ms: eth_getCode
T+3373ms: eth_blockNumber
T+12311ms: net_version
T+12351ms: eth_unsubscribe
T+12351ms: eth_unsubscribe
T+12381ms: eth_unsubscribe
T+12399ms: eth_unsubscribe
```

**Comment by tearsofphoenix** [comment] 2019-08-15 01:49
seems the 2.1.0-beta release of mac OS has something wrong with the binary build. After download & unpack the zip file, found the Electron.framework is only 35 bytes.

**Comment by davidmurdoch** [comment] 2020-10-28 18:21
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1470

**Closed by davidmurdoch** 2020-10-28 18:21 UTC
