### ISSUE TITLE
System Error when running Ganache 1.2.1 on win32

### ISSUE THREAD

**Issue by AloneTimeZ** [trufflesuite/ganache#900] opened 2018-09-11 07:34 UTC
PLATFORM: win32
GANACHE VERSION: 1.2.1

EXCEPTION:
```
Error: Number can only safely store up to 53 bits
    at r (C:\Program Files\WindowsApps\Ganache_1.2.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\bn.js\lib\bn.js:14:1)
    at n.toNumber (C:\Program Files\WindowsApps\Ganache_1.2.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\bn.js\lib\bn.js:511:1)
    at Object.t.bufferToInt (C:\Program Files\WindowsApps\Ganache_1.2.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\ethereumjs-util\dist\index.js:214:1)
    at Object.number (C:\Program Files\WindowsApps\Ganache_1.2.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\(webpack)\buildin\module.js:3:1)
    at r.blockchain.getQueuedNonce (C:\Program Files\WindowsApps\Ganache_1.2.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\ganache-core\lib\statemanager.js:827:1)
    at C:\Program Files\WindowsApps\Ganache_1.2.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\ganache-core\lib\blockchain_double.js:379:1
    at C:\Program Files\WindowsApps\Ganache_1.2.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\merkle-patricia-tree\baseTrie.js:77:1
    at C:\Program Files\WindowsApps\Ganache_1.2.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\merkle-patricia-tree\baseTrie.js:461:1
    at Object.return (C:\Program Files\WindowsApps\Ganache_1.2.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\merkle-patricia-tree\baseTrie.js:485:1)
    at C:\Program Files\WindowsApps\Ganache_1.2.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\merkle-patricia-tree\baseTrie.js:285:1
    at e (C:\Program Files\WindowsApps\Ganache_1.2.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\merkle-patricia-tree\baseTrie.js:521:1)
    at C:\Program Files\WindowsApps\Ganache_1.2.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\merkle-patricia-tree\baseTrie.js:516:1
    at C:\Program Files\WindowsApps\Ganache_1.2.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\ganache-cli\build\webpack:\ganache\node_modules\merkle-patricia-tree\baseTrie.js:180:1
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 1.2.1) with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false}
T+323ms: Ganache started successfully!
T+323ms: Waiting for requests...
T+749ms: eth_getBlockByNumber
T+1420ms: net_version
T+6209ms: eth_getTransactionCount
T+6285ms: eth_sendRawTransaction
T+6298ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment] 2018-09-11 14:29
Thanks for reporting this @AloneTimeZ. This looks to be a duplicate of https://github.com/trufflesuite/ganache/issues/847, and we'll be tracking this issue there.

**Closed by davidmurdoch** 2018-09-11 14:29 UTC
