### ISSUE TITLE
System Error when running Ganache 1.0.2 on win32

### ISSUE THREAD

**Issue by yashwantchavan** [trufflesuite/ganache#650] opened 2018-05-22 05:36 UTC
PLATFORM: win32
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+46287ms:   Block Number: 16
T+46287ms:   Block Time: Tue May 22 2018 11:05:27 GMT+0530 (India Standard Time)
T+46290ms: eth_newBlockFilter
T+46294ms: eth_getFilterChanges
T+46304ms: eth_getTransactionReceipt
T+46316ms: eth_getCode
T+46325ms: eth_uninstallFilter
T+46330ms: evm_mine
T+46682ms: eth_getBlockByNumber
T+46705ms: net_version
T+46710ms: eth_sendTransaction
T+46813ms:   Transaction: 0x9a3b14f2c14cbda6addb9619a22274d6386c3f4501c7faf5498d564e2f5062d9
T+46813ms:   Contract created: 0xeec918d74c746167564401103096d45bbd494b74
T+46813ms:   Gas usage: 3783887
T+46813ms:   Block Number: 18
T+46819ms:   Block Time: Tue May 22 2018 11:05:27 GMT+0530 (India Standard Time)
T+46827ms: eth_newBlockFilter
T+46835ms: eth_getFilterChanges
T+46842ms: eth_getTransactionReceipt
T+46847ms: eth_getCode
T+46854ms: eth_uninstallFilter
T+46862ms: net_version
T+46865ms: eth_sendTransaction
T+46981ms:   Transaction: 0x53fbdaac5de0adf8bddaa2243e0b34983765b90134bd5be2d8c03c74ca7863fd
T+46981ms:   Contract created: 0x0d8cc4b8d15d4c3ef1d70af0071376fb26b5669b
T+46981ms:   Gas usage: 2623049
T+46981ms:   Block Number: 19
T+46981ms:   Block Time: Tue May 22 2018 11:05:28 GMT+0530 (India Standard Time)
T+46986ms: eth_newBlockFilter
T+46990ms: eth_getFilterChanges
T+46996ms: eth_getTransactionReceipt
T+47005ms: eth_getCode
T+47075ms: eth_uninstallFilter
T+47082ms: net_version
T+47091ms: eth_sendTransaction
T+47440ms:   Transaction: 0x3629c32574021755a513f7602674d1876cb5f8e0f4878b3433cd1baf5850f203
T+47440ms:   Contract created: 0xecfcab0a285d3380e488a39b4bb21e777f8a4eac
T+47440ms:   Gas usage: 2077284
T+47440ms:   Block Number: 20
T+47440ms:   Block Time: Tue May 22 2018 11:05:28 GMT+0530 (India Standard Time)
T+47445ms: eth_newBlockFilter
T+47451ms: eth_getFilterChanges
T+47465ms: eth_getTransactionReceipt
T+47472ms: eth_getCode
T+47477ms: eth_uninstallFilter
T+47485ms: net_version
T+47490ms: eth_sendTransaction
T+47563ms:   Transaction: 0x909fcc7ec27917f19bf07ad34b16e40627edff75b2755d110380eed3d08e9e2a
T+47563ms:   Gas usage: 30658
T+47563ms:   Block Number: 21
T+47563ms:   Block Time: Tue May 22 2018 11:05:28 GMT+0530 (India Standard Time)
T+47569ms: eth_getTransactionReceipt
T+47572ms: net_version
T+47575ms: eth_sendTransaction
T+47670ms:   Transaction: 0xd72e231aee72fde5d9acf541265133fd06daa1db4ea24212435b264ba629da6f
T+47670ms:   Gas usage: 14464
T+47670ms:   Block Number: 22
T+47670ms:   Block Time: Tue May 22 2018 11:05:28 GMT+0530 (India Standard Time)
T+47676ms: eth_getTransactionReceipt
T+47681ms: net_version
T+47685ms: eth_sendTransaction
T+47789ms:   Transaction: 0xad6fc4e9034166c6fbaba53b5cd62ad0c684bad46ee154ec61573f331fc6dd14
T+47789ms:   Gas usage: 104039
T+47789ms:   Block Number: 23
T+47789ms:   Block Time: Tue May 22 2018 11:05:28 GMT+0530 (India Standard Time)
T+47795ms: eth_getTransactionReceipt
T+47803ms: net_version
T+47807ms: eth_sendTransaction
T+47853ms:   Transaction: 0x1cf3467f341523dbd1e50f6764d374be8ed37fd1d3e5a138a345d48aae42eee3
T+47853ms:   Gas usage: 4430100
T+47853ms:   Block Number: 24
T+47859ms:   Block Time: Tue May 22 2018 11:05:29 GMT+0530 (India Standard Time)
T+47859ms:   Runtime Error: revert
T+47904ms: eth_getLogs
T+47932ms: eth_blockNumber
T+47939ms: net_version
T+47944ms: eth_sendTransaction
T+48136ms:   Transaction: 0x84a3731796ac6297e8df8db3265f352137171217b90af92b60b15d9696279961
T+48136ms:   Contract created: 0x13274fe19c0178208bcbee397af8167a7be27f6f
T+48136ms:   Gas usage: 2623049
T+48136ms:   Block Number: 25
T+48141ms:   Block Time: Tue May 22 2018 11:05:29 GMT+0530 (India Standard Time)
T+48146ms: eth_newBlockFilter
T+48151ms: eth_getFilterChanges
T+48156ms: eth_getTransactionReceipt
T+48166ms: eth_getCode
T+48173ms: eth_uninstallFilter
T+48180ms: evm_revert
T+48256ms: 
T+48256ms: C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:63898
T+48256ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&
T+48256ms: NotFoundError: Key not found in database
T+48256ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:75532:18
T+48256ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:75297:19
T+48256ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:77442:21
T+48256ms:     at ReadFileContext.callback (C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:77339:14)
T+48256ms:     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:336:13)
```

**Comment by seesemichaelj** [comment] 2018-05-25 23:39
Thanks so much for reporting this! If you could provide some details on what you were doing, what contracts you were running, etc (the more the better), it'd help me a bunch figuring out root cause! Thanks!

I'm going to close this as it seems to be a duplicate of #362; feel free to comment here or there.

**Closed by seesemichaelj** 2018-05-25 23:39 UTC
Labels: runtime-error-code-7
