### ISSUE TITLE
Error Decoding ENSRegistry Contract

### ISSUE THREAD

**Issue by Texnomic** [trufflesuite/ganache#1434] opened 2019-09-16 00:03 UTC
I'm facing this error while executing Migration from [Deploying ENS on a Private Chain](https://docs.ens.domains/deploying-ens-on-a-private-chain#migration-file-example)

PLATFORM: Windows 10 (1903) x64
GANACHE VERSION: 2.1.1

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 531$ of contract$ ENSRegistry (ID 720)
    at vars.concat.linearizedBaseContractsFromBase.map (C:\Program Files\WindowsApps\Ganache_2.1.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:164:19)
    at Array.map (native)
    at allocateContract (C:\Program Files\WindowsApps\Ganache_2.1.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:161:61)
    at Object.getStorageAllocations (C:\Program Files\WindowsApps\Ganache_2.1.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\allocate\storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.1.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:117:47)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Program Files\WindowsApps\Ganache_2.1.1.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\truffle-decoder\dist\interface\contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:21
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1470

**Closed by davidmurdoch** 2020-10-28 18:21 UTC
