### ISSUE TITLE
System Error when running Ganache 1.2.2 on win32

### ISSUE THREAD

**Issue by erikknaake** [trufflesuite/ganache#1014] opened 2018-12-03 14:51 UTC
PLATFORM: win32
GANACHE VERSION: 1.2.2

EXCEPTION:
```
Error: ENOENT: no such file or directory, open 'C:\Users\<USER>\AppData\Local\Temp\tmp-81001QrliHyBlW8j\!trie_db!0x544cc55afb101cf92779abc109d7fb378306242bcab44bd0e9cc61d7f4943d02'
```

APPLICATION LOG:
```
T+22525353ms: eth_blockNumber
T+22526362ms: eth_blockNumber
T+22527370ms: eth_blockNumber
T+22528380ms: eth_blockNumber
T+22529393ms: eth_blockNumber
T+22530399ms: eth_blockNumber
T+22531407ms: eth_blockNumber
T+22532415ms: eth_blockNumber
T+22533423ms: eth_blockNumber
T+22534431ms: eth_blockNumber
T+22535440ms: eth_blockNumber
T+22536450ms: eth_blockNumber
T+22537461ms: eth_blockNumber
T+22538475ms: eth_blockNumber
T+22539483ms: eth_blockNumber
T+22540491ms: eth_blockNumber
T+22541500ms: eth_blockNumber
T+22542511ms: eth_blockNumber
T+22543521ms: eth_blockNumber
T+22544531ms: eth_blockNumber
T+22545538ms: eth_blockNumber
T+22546546ms: eth_blockNumber
T+22547554ms: eth_blockNumber
T+22548562ms: eth_blockNumber
T+22549571ms: eth_blockNumber
T+22550580ms: eth_blockNumber
T+22551588ms: eth_blockNumber
T+22552596ms: eth_blockNumber
T+22553622ms: eth_blockNumber
T+22554636ms: eth_blockNumber
T+22555642ms: eth_blockNumber
T+22556652ms: eth_blockNumber
T+22557662ms: eth_blockNumber
T+22558672ms: eth_blockNumber
T+22559683ms: eth_blockNumber
T+22560693ms: eth_blockNumber
T+22561701ms: eth_blockNumber
T+22562708ms: eth_blockNumber
T+22563714ms: eth_blockNumber
T+22564726ms: eth_blockNumber
T+22565754ms: eth_blockNumber
T+22566764ms: eth_blockNumber
T+22567770ms: eth_blockNumber
T+22568777ms: eth_blockNumber
T+22569790ms: eth_blockNumber
T+22570799ms: eth_blockNumber
T+22571809ms: eth_blockNumber
T+22572819ms: eth_blockNumber
T+22573829ms: eth_blockNumber
T+22574847ms: eth_blockNumber
T+22575856ms: eth_blockNumber
T+22576867ms: eth_blockNumber
T+22577874ms: eth_blockNumber
T+22578885ms: eth_blockNumber
T+22579893ms: eth_blockNumber
T+22580903ms: eth_blockNumber
T+22581913ms: eth_blockNumber
T+22582921ms: eth_blockNumber
T+22583929ms: eth_blockNumber
T+22584939ms: eth_blockNumber
T+22585951ms: eth_blockNumber
T+22586961ms: eth_blockNumber
T+22587970ms: eth_blockNumber
T+22588980ms: eth_blockNumber
T+22589990ms: eth_blockNumber
T+22590999ms: eth_blockNumber
T+22592012ms: eth_blockNumber
T+22593021ms: eth_blockNumber
T+22594037ms: eth_blockNumber
T+22595046ms: eth_blockNumber
T+22596055ms: eth_blockNumber
T+22597061ms: eth_blockNumber
T+22598082ms: eth_blockNumber
T+22599090ms: eth_blockNumber
T+22600097ms: eth_blockNumber
T+22601106ms: eth_blockNumber
T+22602112ms: eth_blockNumber
T+22603120ms: eth_blockNumber
T+22604129ms: eth_blockNumber
T+22605136ms: eth_blockNumber
T+22606143ms: eth_blockNumber
T+22607152ms: eth_blockNumber
T+22608160ms: eth_blockNumber
T+22609168ms: eth_blockNumber
T+22610175ms: eth_blockNumber
T+22611185ms: eth_blockNumber
T+22612193ms: eth_blockNumber
T+22613200ms: eth_blockNumber
T+22614209ms: eth_blockNumber
T+22615215ms: eth_blockNumber
T+22616224ms: eth_blockNumber
T+22617231ms: eth_blockNumber
T+22618240ms: eth_blockNumber
T+22619248ms: eth_blockNumber
T+22620257ms: eth_blockNumber
T+22621263ms: eth_blockNumber
T+22622271ms: eth_blockNumber
T+22623278ms: eth_blockNumber
T+22624286ms: eth_blockNumber
T+22625295ms: eth_blockNumber
T+22626306ms: eth_blockNumber
T+22627316ms: eth_blockNumber
T+22628325ms: eth_blockNumber
T+22629335ms: eth_blockNumber
T+22630346ms: eth_blockNumber
T+22631356ms: eth_blockNumber
T+22632367ms: eth_blockNumber
T+22633377ms: eth_blockNumber
T+22634387ms: eth_blockNumber
T+22635396ms: eth_blockNumber
T+22636408ms: eth_blockNumber
T+22637420ms: eth_blockNumber
T+22638431ms: eth_blockNumber
T+22639441ms: eth_blockNumber
T+22640454ms: eth_blockNumber
T+22641466ms: eth_blockNumber
T+22642478ms: eth_blockNumber
T+22643491ms: eth_blockNumber
T+22644502ms: eth_blockNumber
T+22645514ms: eth_blockNumber
T+22646525ms: eth_blockNumber
T+22647536ms: eth_blockNumber
T+22648546ms: eth_blockNumber
T+22649555ms: eth_blockNumber
T+22650565ms: eth_blockNumber
T+22651574ms: eth_blockNumber
T+22652581ms: eth_blockNumber
T+22653591ms: eth_blockNumber
T+22654602ms: eth_blockNumber
T+22655611ms: eth_blockNumber
T+22656617ms: eth_blockNumber
T+22657627ms: eth_blockNumber
T+22658636ms: eth_blockNumber
T+22659644ms: eth_blockNumber
T+22660652ms: eth_blockNumber
T+22661662ms: eth_blockNumber
T+22662668ms: eth_blockNumber
T+22663680ms: eth_blockNumber
T+22664690ms: eth_blockNumber
T+22665700ms: eth_blockNumber
T+22666712ms: eth_blockNumber
T+22667721ms: eth_blockNumber
T+22668735ms: eth_blockNumber
T+22669755ms: eth_blockNumber
T+22670783ms: eth_blockNumber
T+22671790ms: eth_blockNumber
T+22672797ms: eth_blockNumber
T+22673805ms: eth_blockNumber
T+22674841ms: eth_blockNumber
T+22675848ms: eth_blockNumber
T+22676856ms: eth_blockNumber
T+22677863ms: eth_blockNumber
T+22678874ms: eth_blockNumber
T+22679880ms: eth_blockNumber
T+22680887ms: eth_blockNumber
T+22681896ms: eth_blockNumber
T+22682906ms: eth_blockNumber
T+22683915ms: eth_blockNumber
T+22684921ms: eth_blockNumber
T+22685930ms: eth_blockNumber
T+22686939ms: eth_blockNumber
T+22687950ms: eth_blockNumber
T+22688299ms: eth_accounts
T+22688301ms: eth_accounts
T+22688425ms: eth_accounts
T+22688552ms: eth_getTransactionCount
T+22688552ms: eth_getTransactionCount
T+22688560ms: eth_getTransactionCount
T+22688586ms: net_version
T+22688587ms: net_version
T+22688588ms: net_version
T+22688614ms: eth_sendTransaction
T+22688615ms: eth_sendTransaction
T+22688615ms: eth_sendTransaction
T+22688688ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment] 2019-04-02 15:17
Closing due to not being able to reproduce with the information provided. Please reopen if you can provide more information. Thanks!

**Closed by davidmurdoch** 2019-04-02 15:17 UTC
Labels: needs more information, needs validation, priority-medium
