### ISSUE TITLE
Feature Request: Copy option

### ISSUE THREAD

**Issue by B5Happy** [trufflesuite/ganache#1287] opened 2019-05-12 07:51 UTC
# Feature

I think it would be nice to have a copy option after a right click.

![Ganache](https://user-images.githubusercontent.com/39341595/57579402-ccc86380-74b8-11e9-985c-0b685ace0284.png)

**Comment by davidmurdoch** [comment] 2019-05-20 20:01
Thanks for taking the time to open this issue, @B5Happy. This issue is a duplicate of https://github.com/trufflesuite/ganache/issues/1093 so I'm closing this one.

**Closed by davidmurdoch** 2019-05-20 20:01 UTC
