### ISSUE TITLE
Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by morrigan** [trufflesuite/ganache#449] opened 2018-03-22 20:47 UTC
I was trying to use `truffle debug` command but it just got stuck on "Gathering transaction data... ".

PLATFORM: darwin
GANACHE VERSION: 1.1.0-beta.1

EXCEPTION:
```
Blockchain process exited prematurely due to signal 'SIGABRT'.
```

APPLICATION LOG:
```
T+601461ms: eth_getBalance
T+601464ms: eth_getBalance
T+601468ms: eth_getBalance
T+601468ms: eth_getBalance
T+601475ms: eth_getBalance
T+601477ms: eth_getBalance
T+601483ms: eth_getBalance
T+601486ms: eth_getBalance
T+601494ms: eth_getBalance
T+601494ms: eth_getBalance
T+606404ms: net_version
T+611353ms: eth_getBlockByNumber
T+611570ms: net_version
T+611570ms: eth_getBalance
T+611570ms: eth_getBalance
T+611570ms: eth_getBalance
T+611570ms: eth_getBalance
T+611570ms: eth_getBalance
T+611576ms: eth_getBalance
T+611591ms: eth_getBalance
T+611593ms: eth_getBalance
T+611595ms: eth_getBalance
T+611597ms: eth_getBalance
T+611598ms: eth_getBalance
T+611600ms: eth_getBalance
T+611602ms: eth_getBalance
T+611603ms: eth_getBalance
T+611605ms: eth_getBalance
T+611606ms: eth_getBalance
T+611609ms: eth_getBalance
T+611611ms: eth_getBalance
T+611613ms: eth_getBalance
T+611616ms: eth_getBalance
T+616582ms: net_version
T+621585ms: net_version
T+621662ms: eth_getBalance
T+621668ms: eth_getBalance
T+621670ms: eth_getBalance
T+621685ms: eth_getBalance
T+621687ms: eth_getBalance
T+621689ms: eth_getBalance
T+621690ms: eth_getBalance
T+621698ms: eth_getBalance
T+621698ms: eth_getBalance
T+621698ms: eth_getBalance
T+621698ms: eth_getBalance
T+621698ms: eth_getBalance
T+621704ms: eth_getBalance
T+621705ms: eth_getBalance
T+621707ms: eth_getBalance
T+621710ms: eth_getBalance
T+621716ms: eth_getBalance
T+621718ms: eth_getBalance
T+621720ms: eth_getBalance
T+621724ms: eth_getBalance
T+626567ms: eth_getBlockByNumber
T+626567ms: net_version
T+631659ms: net_version
T+631661ms: eth_getBalance
T+631663ms: eth_getBalance
T+631663ms: eth_getBalance
T+631665ms: eth_getBalance
T+631667ms: eth_getBalance
T+631669ms: eth_getBalance
T+631670ms: eth_getBalance
T+631670ms: eth_getBalance
T+631672ms: eth_getBalance
T+631674ms: eth_getBalance
T+631676ms: eth_getBalance
T+631677ms: eth_getBalance
T+631679ms: eth_getBalance
T+631681ms: eth_getBalance
T+631691ms: eth_getBalance
T+631694ms: eth_getBalance
T+631695ms: eth_getBalance
T+631698ms: eth_getBalance
T+631700ms: eth_getBalance
T+631702ms: eth_getBalance
T+636573ms: net_version
T+641581ms: eth_getBlockByNumber
T+641583ms: net_version
T+641584ms: eth_getBalance
T+641585ms: eth_getBalance
T+641588ms: eth_getBalance
T+641591ms: eth_getBalance
T+641593ms: eth_getBalance
T+641597ms: eth_getBalance
T+641599ms: eth_getBalance
T+641601ms: eth_getBalance
T+641603ms: eth_getBalance
T+641607ms: eth_getBalance
T+641610ms: eth_getBalance
T+641612ms: eth_getBalance
T+641614ms: eth_getBalance
T+641616ms: eth_getBalance
T+641620ms: eth_getBalance
T+641622ms: eth_getBalance
T+641624ms: eth_getBalance
T+641627ms: eth_getBalance
T+641629ms: eth_getBalance
T+641633ms: eth_getBalance
T+646579ms: net_version
T+651098ms: net_version
T+651104ms: eth_accounts
T+651190ms: net_version
T+651190ms: net_version
T+651214ms: debug_traceTransaction
T+651611ms: net_version
T+651613ms: eth_getBalance
T+651613ms: eth_getBalance
T+651614ms: eth_getBalance
T+651614ms: eth_getBalance
T+651615ms: eth_getBalance
T+789875ms: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
T+789875ms:  1: 
T+789887ms: node::Abort() [/Applications/Ganache.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
T+789887ms:  2: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Ganache.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
T+789887ms:  3: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Ganache.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
T+789887ms:  4: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Ganache.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
T+789887ms:  5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/Applications/Ganache.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
T+789887ms:  6: 
T+789937ms: v8::internal::compiler::Node::Uses::empty() const [/Applications/Ganache.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
T+789937ms:  7: 
T+789938ms: v8::internal::RegisterConfiguration::AreAliases(v8::internal::MachineRepresentation, int, v8::internal::MachineRepresentation, int) const [/Applications/Ganache.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
T+789938ms:  8: 0x14f1570843a7
T+789938ms:  9: 0x14f157d7784f
T+789938ms: 10: 0x14f157d73a15
T+789940ms: 
T+789940ms: <--- Last few GCs --->
T+789940ms: 
T+789940ms: [14648:0x7fd9ee803600]   566942 ms: Mark-sweep 1450.6 (1510.8) -> 1450.6 (1479.8) MB, 1759.8 / 0.0 ms  last resort 
T+789940ms: [14648:0x7fd9ee803600]   568763 ms: Mark-sweep 1450.6 (1479.8) -> 1450.6 (1479.8) MB, 1820.5 / 0.0 ms  last resort 
T+789940ms: 
T+789940ms: 
T+789940ms: <--- JS stacktrace --->
T+789940ms: 
T+789940ms: ==== JS stack trace =========================================
T+789940ms: 
T+789940ms: Security context: 0x1739752a7831 <JS Object>
T+789940ms:     1: set [native collection.js:~252] [pc=0x14f157d7784f](this=0x345ae74e44c1 <a Map with map 0x1b75a2607dc9>,q=0x1a4227d95e99 <JS Array[5]>,y=0x161d7437f231 <JS Array[5]>)
T+789940ms:     2: set(aka mapCacheSet) [/node_modules/ganache-cli/build/lib.node.js:~166116] [pc=0x14f157d73a15](this=0x1749aa52e39 <a MapCache with map 0x1fc52dcb3ed1>,key=0x1a4227d95e9...
T+789940ms: 
```

**Comment by jdkanani** [comment] 2018-06-17 15:30
Same error while fetching `debug_traceTransaction`

**Comment by seesemichaelj** [comment] 2018-06-26 17:02
Thanks for reporting this! It would be great if this was very repeatable/reproducible as well as steps to reproduce (i.e. source code/etc.). Thanks!

**Comment by seesemichaelj** [comment] 2018-08-13 21:40
Just putting this here for posterity's sake. Looking at the comments more specifically, looks like `debug_traceTransaction` is probably the issue. Probably need to increase the heap size (`--max-old-space-size=4096`)

**Comment by seesemichaelj** [comment] 2018-10-15 18:55
This issue is prevalent likely in `ganache-core`, but going to leave this issue open for posterity's sake. We also have an issue open at https://github.com/trufflesuite/ganache-cli/issues/570

**Comment by eshaben** [comment] 2018-12-03 23:02
Thanks @morrigan for submitting the issue! I was unable to reproduce the heap out of memory issue revolving around `debug_traceTransaction` in Ganache version 1.1.0-beta.1. As the issue would have been in `ganache-core`, I also went ahead and tested our latest version 2.3.1 and was unable to detect any memory leaks. I am going to go ahead and close this issue, but if you are still experiencing any problems please open up a new issue with reproducible steps. Thanks!!

**Closed by eshaben** 2018-12-03 23:02 UTC
Labels: bug, priority-high
