### ISSUE TITLE
System Error when running Ganache 1.1.0 on win32 - I think I know what happened. I am a newbie and I left the truffle develop network running in another powershell while trying to start up a ganache network. I went and shut down the second powershell and retried the migrate and it worked. thanks  anne

### ISSUE THREAD

**Issue by annebreene** [trufflesuite/ganache#887] opened 2018-08-28 05:58 UTC
![image](https://user-images.githubusercontent.com/20629473/44703448-a7e4ab00-aa65-11e8-8822-51e91fe76c8f.png)

PLATFORM: win32
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: ENOENT: no such file or directory, open 'C:\Users\anneb\AppData\Local\Temp\tmp-7592UMF9zQnCL0LV\!trie_db!0xce6d72d78d351ebbb13f3d29a7c8781c49db8d8a376f721e7ae124f734f0876c'
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
T+940ms: Ganache started successfully!
T+940ms: Waiting for requests...
T+153998581ms: eth_getBlockByNumber
T+153998717ms: net_version
T+153998723ms: net_version
T+153998734ms: net_version
T+153998752ms: eth_getBlockByNumber
T+154006723ms: eth_getBlockByNumber
T+154015095ms: eth_getBlockByNumber
T+154023146ms: eth_getBlockByNumber
T+154031467ms: eth_getBlockByNumber
T+154039489ms: eth_getBlockByNumber
T+154047811ms: eth_getBlockByNumber
T+154055859ms: eth_getBlockByNumber
T+154064190ms: eth_getBlockByNumber
T+154072208ms: eth_getBlockByNumber
T+154080545ms: eth_getBlockByNumber
T+154088591ms: eth_getBlockByNumber
T+154096913ms: eth_getBlockByNumber
T+154104953ms: eth_getBlockByNumber
T+154113273ms: eth_getBlockByNumber
T+154121294ms: eth_getBlockByNumber
T+154129635ms: eth_getBlockByNumber
T+154137657ms: eth_getBlockByNumber
T+154145979ms: eth_getBlockByNumber
T+154154003ms: eth_getBlockByNumber
T+154162328ms: eth_getBlockByNumber
T+154170350ms: eth_getBlockByNumber
T+154178670ms: eth_getBlockByNumber
T+154186695ms: eth_getBlockByNumber
T+154195014ms: eth_getBlockByNumber
T+154203030ms: eth_getBlockByNumber
T+154211349ms: eth_getBlockByNumber
T+154219367ms: eth_getBlockByNumber
T+154227685ms: eth_getBlockByNumber
T+154235702ms: eth_getBlockByNumber
T+154244026ms: eth_getBlockByNumber
T+154252056ms: eth_getBlockByNumber
T+154260374ms: eth_getBlockByNumber
T+154268396ms: eth_getBlockByNumber
T+154276720ms: eth_getBlockByNumber
T+154284765ms: eth_getBlockByNumber
T+154293086ms: eth_getBlockByNumber
T+154301106ms: eth_getBlockByNumber
T+154309427ms: eth_getBlockByNumber
T+154317443ms: eth_getBlockByNumber
T+154325767ms: eth_getBlockByNumber
T+154333781ms: eth_getBlockByNumber
T+154342129ms: eth_getBlockByNumber
T+154350151ms: eth_getBlockByNumber
T+154358480ms: eth_getBlockByNumber
T+154366497ms: eth_getBlockByNumber
T+154374814ms: eth_getBlockByNumber
T+154382833ms: eth_getBlockByNumber
T+154391153ms: eth_getBlockByNumber
T+154399171ms: eth_getBlockByNumber
T+154407494ms: eth_getBlockByNumber
T+154415516ms: eth_getBlockByNumber
T+154423837ms: eth_getBlockByNumber
T+154431856ms: eth_getBlockByNumber
T+154440178ms: eth_getBlockByNumber
T+154448197ms: eth_getBlockByNumber
T+154456520ms: eth_getBlockByNumber
T+518840633ms: net_version
T+518840649ms: eth_accounts
T+518840649ms: eth_accounts
T+518840655ms: net_version
T+518840662ms: net_version
T+518840678ms: eth_sendTransaction
```

**Comment by seesemichaelj** [comment] 2018-08-28 21:03
Hi @annebreene! Looks like you may have mitigated the problem!

On another note, here's what we said in a similar issue (#616): the problem here is likely caused by the temporary directory which ganache uses for storing its database being deleted while ganache is running. This might've happened due to you running a disk cleanup tool or similar.

Closing this one as this is excepted behavior.

**Closed by seesemichaelj** 2018-08-28 21:03 UTC
