### ISSUE TITLE
Heartbeat lost when following `ThrowProxy` tutorial

### ISSUE THREAD

**Issue by ChosunOne** [trufflesuite/ganache#130] opened 2017-11-30 03:04 UTC
Attempting to test a ThrowProxy from the tutorials crashes ganache.  
Offending Solidity Code:
```
function testThrower() {
        address destination = 0x0;
        uint value = 1;
        bytes data;

        Thrower thrower = Thrower(DeployedAddresses.Thrower());
        thrower.send(1 ether);
        ThrowProxy throwProxy = new ThrowProxy(address(thrower));
        Thrower(address(throwProxy)).execute(destination, value, data);

        bool r = throwProxy.execute.gas(500000)();

        Assert.isFalse(r, "Should not successfully execute");
    }
```
Report from Ganache:
```
PLATFORM: win32
GANACHE VERSION: 1.0.1

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by benjamincburns** [comment] 2017-11-30 22:25
Was going to close this as a dupe of #83, however it appears that you have repro steps, so I'll leave this open. Thanks so much, @ChosunOne!

If you wanted to clone the source and test against latest master, that will likely shine some further light on the problem, as I nixed the heartbeat for better error reporting.

**Comment by benjamincburns** [comment] 2017-11-30 22:26
@ChosunOne if you find that no error occurs on current master, it's likely a dupe of #83.

**Comment by ChosunOne** [comment] 2017-12-01 04:11
Ok I'll give it a shot.  I'm also experiencing a lot of crashes in general with Ganache 1.0.1 (not always seeming to be deterministic either) release so I'll see if using the latest master improves things.

**Comment by ChosunOne** [comment] 2017-12-01 04:36
Running tests from truffle test with a javascript test suite, but this doesn't happen every time.  I'm not sure if it was specific to the contract code, but removing that element and just running the javascript tests produce the same error.  Before running the tests I restart Ganache so that it starts at block 0. Sometimes it completes without error, other times I get this report:

PLATFORM: win32
GANACHE VERSION: 1.6.11

EXCEPTION:
Blockchain process exited prematurely with code '7', due to signal 'null'.

It is always the same exception report as above.

**Comment by benjamincburns** [comment] 2017-12-01 14:34
Thanks, @ChosunOne - I’ll dig into that ASAP!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by benjamincburns** [comment] 2017-12-01 17:54
@ChosunOne so I think part of the problem here is that even though we have an uncaught exception handler, something else is actually catching an exception and killing the server process before the error is reported back to the main Ganache process. If I'm correct on this, then the error description will be in the Ganache logs.

Problem is, you can't get to the Ganache logs once the fatal error dialog box pops up, so I'm going to see if I can't modify the fatal error dialog & report to github features to include recent (hopefully relevant) log lines.

**Comment by benjamincburns** [comment] 2017-12-02 00:49
@ChosunOne - good news: I managed to repro this while testing #135.

Until that PR is merged, if you test using the `report-logs-in-gh-issues`, that will allow you to raise a GH issue which includes a tail of your logs.

**Comment by benjamincburns** [comment] 2017-12-02 01:02
I managed to repro this again, this time from the branch I suggested, and the one I'm observing appears to be caused by trufflesuite/ganache-cli#417.

```
T+136202ms: TypeError: Cannot read property 'get' of undefined
T+136202ms:     at dbGet (/Users/bburns/projects/consensys/ganache/node_modules/ganache-cli/build/lib.node.js:56029:7)
T+136202ms:     at /Users/bburns/projects/consensys/ganache/node_modules/ganache-cli/build/lib.node.js:17614:5
T+136202ms:     at /Users/bburns/projects/consensys/ganache/node_modules/ganache-cli/build/lib.node.js:23091:20
T+136202ms:     at iterate (/Users/bburns/projects/consensys/ganache/node_modules/ganache-cli/build/lib.node.js:23172:13)
T+136202ms:     at /Users/bburns/projects/consensys/ganache/node_modules/ganache-cli/build/lib.node.js:23184:29
T+136202ms:     at /Users/bburns/projects/consensys/ganache/node_modules/ganache-cli/build/lib.node.js:22954:16
T+136202ms:     at /Users/bburns/projects/consensys/ganache/node_modules/ganache-cli/build/lib.node.js:17619:7
T+136202ms:     at /Users/bburns/projects/consensys/ganache/node_modules/ganache-cli/build/lib.node.js:56034:9
T+136202ms:     at dispatchError (/Users/bburns/projects/consensys/ganache/node_modules/ganache-cli/build/lib.node.js:36358:36)
T+136202ms:     at /Users/bburns/projects/consensys/ganache/node_modules/ganache-cli/build/lib.node.js:22744:14
```

**Comment by benjamincburns** [comment] 2018-01-09 05:50
Closing this in favor of trufflesuite/ganache-cli#417.

**Closed by benjamincburns** 2018-01-09 05:50 UTC
