### ISSUE TITLE
System Error when running Ganache 2.3.0 on darwin

### ISSUE THREAD

**Issue by sepapple** [trufflesuite/ganache#1735] opened 2020-04-20 05:04 UTC
PLATFORM: darwin
GANACHE VERSION: 2.3.0

EXCEPTION:
```
Error: connection not open
    at WebsocketProvider.send (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/web3-providers-ws/src/index.js:282:18)
    at Timeout._onTimeout (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/web3-providers-ws/src/index.js:267:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:14
closing as duplicate of https://github.com/trufflesuite/ganache/issues/2039

**Closed by davidmurdoch** 2020-10-28 18:14 UTC
