### ISSUE TITLE
System Error when running Ganache 2.1.2 on win32

### ISSUE THREAD

**Issue by ashawinm** [trufflesuite/ganache#1876] opened 2020-06-27 17:49 UTC
PLATFORM: win32
GANACHE VERSION: 2.1.2

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-core-helpers\src\errors.js:35:16)
    at WebsocketProvider._timeout (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:255:48)
    at W3CWebSocket.connection.onclose (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:155:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\yaeti\lib\EventTarget.js:107:17)
    at W3CWebSocket.onClose (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (C:\Program Files\WindowsApps\Ganache_2.1.2.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\websocket\lib\WebSocketConnection.js:389:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.1.2) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"C:\\Users\\ashWIN\\AppData\\Roaming\\Ganache\\workspaces\\womanly-sidewalk\\chaindata"}
T+826ms: Ganache started successfully!
T+826ms: Waiting for requests...
T+889ms: eth_blockNumber
T+941ms: eth_blockNumber
T+1043ms: eth_getCode
T+1132ms: eth_subscribe
T+1182ms: eth_getLogs
T+1228ms: eth_subscribe
T+1275ms: eth_getCode
T+19863ms: eth_blockNumber
T+19978ms: eth_blockNumber
T+39977ms: eth_blockNumber
T+40088ms: eth_blockNumber
T+59926ms: eth_blockNumber
T+60053ms: eth_blockNumber
T+79948ms: eth_blockNumber
T+80141ms: eth_blockNumber
T+99955ms: eth_blockNumber
T+100218ms: eth_blockNumber
T+119983ms: eth_blockNumber
T+120127ms: eth_blockNumber
T+140180ms: eth_blockNumber
T+140180ms: net_version
T+140180ms: eth_accounts
T+140180ms: eth_getBlockByNumber
T+140180ms: eth_accounts
T+140180ms: eth_getBlockByNumber
T+140180ms: eth_getBlockByNumber
T+140180ms: eth_getBlockByNumber
T+140180ms: eth_estimateGas
T+142212ms: eth_blockNumber
T+142212ms: eth_blockNumber
T+144470ms: eth_getBlockByNumber
T+144470ms: eth_blockNumber
T+144470ms: eth_sendTransaction
T+144470ms:   Transaction: 0x3597038b01efedf8175a58df0808137409eabf80ffbb0c255421cbe6d4c320b2
T+144470ms:   Contract created: 0x8dece02a7c97a75b8936a0f9547b66bb742a617b
T+144470ms:   Gas usage: 263741
T+144470ms:   Block Number: 86
T+144470ms:   Block Time: Sat Jun 27 2020 10:46:53 GMT-0700 (Pacific Daylight Time)
T+144470ms: eth_getTransactionReceipt
T+144470ms: eth_getCode
T+144470ms: eth_getTransactionByHash
T+144470ms: eth_getBlockByNumber
T+144470ms: eth_getBalance
T+144470ms: eth_getBlockByNumber
T+144470ms: eth_getBlockByNumber
T+144470ms: eth_sendTransaction
T+144470ms:   Transaction: 0x8241e48f5656ec16ba1ad3400eb0195e5b36b2fb6dfbf34c616b3e7b5a4e6647
T+144470ms:   Gas usage: 42023
T+144470ms:   Block Number: 87
T+144470ms:   Block Time: Sat Jun 27 2020 10:46:53 GMT-0700 (Pacific Daylight Time)
T+144470ms: eth_getTransactionReceipt
T+144470ms: eth_getBlockByNumber
T+144470ms: eth_accounts
T+145217ms: eth_getBlockByNumber
T+145217ms: eth_getBlockByNumber
T+145217ms: eth_getBlockByNumber
T+145217ms: eth_estimateGas
T+145217ms: eth_getBlockByNumber
T+145217ms: eth_blockNumber
T+145217ms: eth_sendTransaction
T+145217ms:   Transaction: 0x6c21f7050d5df02e78b2b5b3632e3659ac3a58699ea2fb342872c85666a91d4c
T+145217ms:   Contract created: 0x96a396b4e30d5943527286d0d71f96116b64e7e1
T+145217ms:   Gas usage: 2290511
T+145217ms:   Block Number: 88
T+145217ms:   Block Time: Sat Jun 27 2020 10:46:53 GMT-0700 (Pacific Daylight Time)
T+145217ms: eth_getTransactionReceipt
T+145217ms: eth_getCode
T+145217ms: eth_getTransactionByHash
T+145217ms: eth_getBlockByNumber
T+145217ms: eth_getBalance
T+145217ms: eth_getBlockByNumber
T+145217ms: eth_getBlockByNumber
T+145217ms: eth_sendTransaction
T+145217ms:   Transaction: 0xc144532fb8e5d86d8d689e29e76c34893eb2dc97e6efe344e820beaedb7342cd
T+145217ms:   Gas usage: 27023
T+145217ms:   Block Number: 89
T+145217ms:   Block Time: Sat Jun 27 2020 10:46:53 GMT-0700 (Pacific Daylight Time)
T+145217ms: eth_getTransactionReceipt
T+162376ms: eth_unsubscribe
T+162376ms: eth_unsubscribe
T+169354ms: eth_accounts
T+173526ms: eth_sendTransaction
T+173526ms:   Transaction: 0xf9253a68dda8e7e41cb7b7a4f3a1026fda919c8faf7b64e52189cd9a1b0c324b
T+173526ms:   Gas usage: 90000
T+173526ms:   Block Number: 90
T+173526ms:   Block Time: Sat Jun 27 2020 10:47:08 GMT-0700 (Pacific Daylight Time)
T+173526ms:   Runtime Error: invalid opcode
T+176580ms: eth_blockNumber
T+176580ms: eth_getBlockByNumber
T+177168ms: eth_blockNumber
T+177168ms: eth_getBlockByNumber
T+177168ms: eth_getLogs
T+186604ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:16
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1770

**Closed by davidmurdoch** 2020-10-28 18:16 UTC
