### ISSUE TITLE
Decoding Error when running Ganache 2.1.2 on linux

### ISSUE THREAD

**Issue by cyril-attie** [trufflesuite/ganache#1602] opened 2020-01-26 19:02 UTC
PLATFORM: linux
GANACHE VERSION: 2.1.2

This is my contract storage:

  ```
  uint256 numTransports=0;

    enum SizeCategory {Enveloppe, SmallBox, BigBox} ///@dev size categories of the packet
    enum WeightCategory {lessThan1kg, between1kgAnd10kg, moreThan10kg} ///@dev weight categories of the packet
    enum TransportState {Unallocated, Allocated, PickedUp} ///@dev status of the transport

    ///@dev Transport
    struct Transport {
        address fromAddress;
        address toAddress;
        address transporter;
        SizeCategory sizeCategory;
        WeightCategory weightCategory;
        uint8[4] itinerary; ///@dev contains _fromLatitude, _fromLongitude, _toLatitude, _toLongitude
        uint256 timestamp;
        uint256 maxDeliveryTimestamp;
        uint256 weiPacketValue; /// for insurance purposes
        uint256 price; ///@dev fee offered or paid for this transport
    }

    struct Offer {
        address transporter;
        uint256 askPrice;
    }

    mapping(uint256 => Transport) public transportDemandPool; ///@dev to record transportation demands
    mapping(uint256 => Offer[]) AvailableTransportSupply; ///@dev to record transportation supplies with offered price
    mapping(uint256 => TransportState) onGoingTransportation; ///@dev ongoing transportations and their state

```
The ganache GUI returns an error message saying 

> "There was an issue decoding your contract. Please file a GitHub Issue by clicking the button below." 

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 715$ of contract$ EthMov (ID 625)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:164:19)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:161:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:117:47)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:18
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1333

**Closed by davidmurdoch** 2020-10-28 18:18 UTC
