### ISSUE TITLE
System Error when running Ganache 1.2.2 on darwin

### ISSUE THREAD

**Issue by MareoRaft** [trufflesuite/ganache#941] opened 2018-10-16 15:39 UTC
I was updating a solidity contract (not shown here) and a solidity test file:

    pragma solidity ^0.4.2;
    
    import "truffle/Assert.sol";
    import "truffle/DeployedAddresses.sol";
    
    import "../contracts/Round.sol";
    
    
    contract TestRound {
    
    
    	// or just write Assert.equal(this, that, "not working") below
    	using Assert for bool;
    	using Assert for int;
    	using Assert for uint;
    	using Assert for address; // working?
    	using Assert for bytes;
        ...

using `truffle test` when Ganache.app said that it had encountered a bug:

    TypeError: Cannot read property 'pop' of undefined
        at CheckpointTrie.Trie._updateNode (/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:360:23)
        at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:107:16
        at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:461:14
        at processNode (/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:471:23)
        at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:516:13
        at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:180:7
        at /node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:75:7
        at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:16
        at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:269:32
        at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:16
        at /node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:71:7
        at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:157:9
        at /node_modules/ganache-core/lib/database/levelupobjectadapter.js:30:23
        at /node_modules/ganache-core/node_modules/level-sublevel/shell.js:101:15
        at /node_modules/ganache-core/node_modules/level-sublevel/nut.js:121:19
        at /node_modules/ganache-core/node_modules/cachedown/index.js:58:21
        at ReadFileContext.callback (/node_modules/ganache-core/lib/database/filedown.js:27:14)
        at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

**Comment by eshaben** [comment] 2019-02-25 17:00
Thanks @MareoRaft for submitting this issue! I have been unable to reproduce the bug so far. Is there any additional information you could provide to help me reproduce it? 

@nmclrn, thank you for your comment as well. I cloned the `TruSet / bitmask-rbac` repo and ran `truffle test --network ganache` with Ganache version 1.2.2 but didn't get any errors. If you have any suggestions as to how to reproduce this issue, please let me know!

**Comment by MareoRaft** [comment] 2019-02-27 01:20
It's been a while, but try using solidity pragma 0.4.2, and here is the full contents of the file:

https://github.com/MareoRaft/charity-wars/blob/master/source/blockchain/test/TestRound.sol

Hope that helps.  Have a great day!

**Comment by eshaben** [comment] 2019-03-06 00:16
@MareoRaft thanks for the additional information! I will try to reproduce this again now.

**Comment by eshaben** [comment] 2019-03-07 19:46
@MareoRaft, I still have not been able to reproduce the bug which makes me think the issue may have been resolved. I know you mentioned it's been a while, but are you still running into problems? Have you upgraded to the latest version of Ganache and ran into these errors as well?

I'm feeling like this issue may be ok to close, but if you are still getting errors then I do not want to close it. So please let me know and if I don't hear back from you in a few days I will assume it's safe to close. Thanks!

**Comment by eshaben** [comment] 2019-03-11 16:49
Going to go ahead and close this issue now due to inability to reproduce.

**Closed by eshaben** 2019-03-11 16:49 UTC
Labels: needs validation, priority-high

**Comment by MareoRaft** [comment] 2019-03-23 23:07
Well my personal Ganache development ceased when I got my full-time job, so it no longer affects me personally.  Thanks for everything and have a nice day.
