### ISSUE TITLE
System Error when running Ganache 1.0.2 on ubuntu16.04 - npm install error

### ISSUE THREAD

**Issue by LEscobar-Driver** [trufflesuite/ganache#432] opened 2018-03-18 22:30 UTC
## Expected Behavior
When `npm install` is invoked, I expect the install to succeed

## Current Behavior
When  `npm install` is invoked the build fails with the following output: log file included

[2018-03-18T22_13_59_352Z-debug.log](https://github.com/trufflesuite/ganache/files/1823209/2018-03-18T22_13_59_352Z-debug.log)

## Steps to Reproduce (for bugs)
1. Clone git repo
2. npm install | also tried sudo nom install

## Your Environment

* Version used: ganache-1.02-x86
* node 9.8.0
* npm 5.7.1
* Operating System and version: Ubuntu 16.04

**Comment by seesemichaelj** [comment] 2018-08-03 22:12
Thanks for reporting this! I'm going close this however since the issue is old and we're not noticing these issues. Please open a new issue if the problem persists in `v1.2.1+`.

Thanks!

**Closed by seesemichaelj** 2018-08-03 22:12 UTC
