### ISSUE TITLE
Balance not updated on 1.0.1

### ISSUE THREAD

**Issue by eloudsa** [trufflesuite/ganache#122] opened 2017-11-26 20:47 UTC
Hello

When I deploy a contract to Ganache, the balance of the account is not updated on the UI.

I'm using Ganache 1.0.1 on macOS.

Is it a know issue?

S.

**Comment by eloudsa** [comment] 2017-11-27 20:38
Some additional information.

I noticed that this problem appears when I deploy a contract on a fresh instance of Ganache (0 transactions).

But, if I deploy a contract with Truffle, the balance is properly updated.

**Comment by eloudsa** [comment] 2017-12-02 14:25
I'm creating a Dapp. When I call a function exposed my the contract deployed on Ganache, the balance is not updated while the transaction is properly received.

So, I confirm that there is an issue with the update of the balance on Ganache.

I'm using:
- Ganache 1.0.1
- Truffle 4.0.1
- macOS 10.13.1

**Comment by herrBez** [comment] 2017-12-14 10:07
I have the same issue on Linux 4.9 (Ganache 1.0.1, Truffle 4.0.1)

**Comment by benjamincburns** [comment] 2017-12-20 00:56
@eloudsa and @herrBez I haven't been able to reproduce this issue locally. Can you please check the logs page for me while your contract deployment is underway and confirm for me that you see log lines indicating transaction execution?

Depending on how exactly you're kicking off your deployment (either with Truffle, Remix, or other tooling), my suspicion is that you might be deploying to an embedded instance of ganache, or an instance of `ganache-cli` you have running in the background rather than deploying to ganache. I've fallen victim to this mistake, myself.

**Comment by eloudsa** [comment] 2017-12-20 20:59
@benjamincburns I'm sure no other nodes were running at the same time.

**Comment by seesemichaelj** [comment] 2018-06-08 07:03
I have not been able to reproduce this. I'm guessing this issue was fixed in some `ganache-core` change since then. Closing until the issue reappears

**Closed by seesemichaelj** 2018-06-08 07:03 UTC
