### ISSUE TITLE
Potential issue with snapping window to half screen on Windows

### ISSUE THREAD

**Issue by annebreene** [trufflesuite/ganache#793] opened 2018-06-29 05:50 UTC
I tried to put Ganache on a half screen page. It raised the issue. Won't do that again.

PLATFORM: win32
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRINUSE 127.0.0.1:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by seesemichaelj** [comment] 2018-06-29 06:02
Thanks for reporting this! We're tracking this in #627, but I believe the issue is very similar to #665. You can get your Ganache back up and running by changing the port in the `%APPDATA%\Ganache\Settings` file. There's a bug which leaves the port open sometimes, which I think is causing this issue. We've scheduled a fix for the next release.

Unfortunately not sure why making it half screen would cause an issue. I'll keep this issue open to track the half screen issue

**Comment by annebreene** [comment] 2018-07-02 11:12
Cool. Thanks!

**Comment by davidmurdoch** [comment] 2019-04-02 15:15
I've been unable to reproduce the half-screen snapping crash on windows so I'm going to go ahead close this. Please open a new issue if this occurs again. Thanks!

**Closed by davidmurdoch** 2019-04-02 15:15 UTC
Labels: ui-triage-needed
