### ISSUE TITLE
System Error when running Ganache 2.1.1 on win32

### ISSUE THREAD

**Issue by RostyslavDzhohola** [trufflesuite/ganache#2082] opened 2020-10-21 17:02 UTC
PLATFORM: win32
GANACHE VERSION: 2.1.1

EXCEPTION:
```
Error: CONNECTION ERROR: Couldn't connect to node on WS.
    at Object.InvalidConnection (C:\Users\Rostyslav\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\web3-core-helpers\src\errors.js:35:16)
    at WebsocketProvider._timeout (C:\Users\Rostyslav\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\web3-providers-ws\src\index.js:255:48)
    at W3CWebSocket.connection.onclose (C:\Users\Rostyslav\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\web3-providers-ws\src\index.js:155:15)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (C:\Users\Rostyslav\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\yaeti\lib\EventTarget.js:107:17)
    at W3CWebSocket.onClose (C:\Users\Rostyslav\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:228:10)
    at WebSocketConnection.<anonymous> (C:\Users\Rostyslav\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\websocket\lib\W3CWebSocket.js:201:17)
    at emitTwo (events.js:125:13)
    at WebSocketConnection.emit (events.js:213:7)
    at WebSocketConnection.handleSocketClose (C:\Users\Rostyslav\AppData\Local\Programs\Ganache\resources\app.asar\node_modules\websocket\lib\WebSocketConnection.js:389:14)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:549:12)
```

APPLICATION LOG:
```
T+328763ms: eth_call
T+328763ms: eth_blockNumber
T+328763ms: eth_getBlockByNumber
T+328763ms: eth_sendTransaction
T+328763ms:   Transaction: 0xc1e69a336c507624ec3ea64eda166c5cf17966595263425783add471bee84acb
T+328763ms:   Gas usage: 21417
T+328763ms:   Block Number: 41
T+328763ms:   Block Time: Wed Oct 21 2020 12:00:11 GMT-0500 (Central Daylight Time)
T+328763ms:   Runtime Error: revert
T+328763ms: eth_call
T+328763ms: eth_getBlockByNumber
T+328763ms: eth_call
T+328763ms: eth_blockNumber
T+328763ms: eth_getBlockByNumber
T+328763ms: eth_sendTransaction
T+328763ms:   Transaction: 0x507cacd0be6112d54e11119958810531fcd5a5ba6d2b42dbbbb8e8e29e446c70
T+328763ms:   Gas usage: 21667
T+328763ms:   Block Number: 42
T+328763ms:   Block Time: Wed Oct 21 2020 12:00:12 GMT-0500 (Central Daylight Time)
T+328763ms:   Runtime Error: revert
T+328763ms: eth_call
T+328763ms: eth_blockNumber
T+328763ms: eth_getBlockByNumber
T+328763ms: eth_sendTransaction
T+328763ms:   Transaction: 0x04715ccd84f88fd233645ddac85d56a9dbae34aa6d05bfc1759854bd9fa943e5
T+328763ms:   Gas usage: 19507
T+328763ms:   Block Number: 43
T+328763ms:   Block Time: Wed Oct 21 2020 12:00:12 GMT-0500 (Central Daylight Time)
T+328763ms: eth_getTransactionReceipt
T+328763ms: eth_getBlockByNumber
T+328763ms: eth_call
T+328763ms: eth_blockNumber
T+328763ms: eth_getBlockByNumber
T+328763ms: eth_sendTransaction
T+328763ms:   Transaction: 0x7654203e444e1dc3d88d34749defa6ff6527aec6513b7d84665605f7e66ed247
T+328763ms:   Contract created: 0xb787b4bc1cff9684483789968150dfd282cdfd02
T+328763ms:   Gas usage: 956279
T+328763ms:   Block Number: 44
T+328763ms:   Block Time: Wed Oct 21 2020 12:00:12 GMT-0500 (Central Daylight Time)
T+328763ms: eth_getTransactionReceipt
T+328763ms: eth_getCode
T+328763ms: eth_getBlockByNumber
T+328763ms: eth_sendTransaction
T+328763ms:   Transaction: 0x64d8f5a185f6229baa8588670cfcb43d7ee6f181bd3ed09c268434b82eed2605
T+328763ms:   Gas usage: 21707
T+328763ms:   Block Number: 45
T+328763ms:   Block Time: Wed Oct 21 2020 12:00:12 GMT-0500 (Central Daylight Time)
T+328763ms:   Runtime Error: revert
T+328763ms: eth_call
T+328763ms: eth_getBlockByNumber
T+328763ms: eth_call
T+328763ms: eth_blockNumber
T+328763ms: eth_getBlockByNumber
T+328763ms: eth_sendTransaction
T+328763ms:   Transaction: 0x9f81f59387af266d1cb5999f79c24e21a91adcf1624a6f611991ecca4abb21fc
T+328763ms:   Contract created: 0x2a87e2904185ec7fba28ed96f46fb1b08bfa1b11
T+328763ms:   Gas usage: 956279
T+328763ms:   Block Number: 46
T+328763ms:   Block Time: Wed Oct 21 2020 12:00:12 GMT-0500 (Central Daylight Time)
T+328763ms: eth_getTransactionReceipt
T+328763ms: eth_getCode
T+328763ms: eth_getBlockByNumber
T+328763ms: eth_sendTransaction
T+328763ms:   Transaction: 0x88ef3acd6b4af0dfa0fee0545536e1e7f1e38bf43914c4cc7fe46aad724a71cf
T+328763ms:   Gas usage: 19507
T+328763ms:   Block Number: 47
T+328763ms:   Block Time: Wed Oct 21 2020 12:00:12 GMT-0500 (Central Daylight Time)
T+328763ms: eth_getTransactionReceipt
T+328763ms: eth_getBlockByNumber
T+328763ms: eth_call
T+328763ms: eth_getBalance
T+328763ms: eth_getBlockByNumber
T+328763ms: eth_call
T+328763ms: eth_blockNumber
T+328763ms: eth_getBlockByNumber
T+328763ms: eth_sendTransaction
T+328763ms:   Transaction: 0x335e2c074fe66306a4edd023f45c3d49fff82b741d6207e4a8259d003e83f592
T+328763ms:   Contract created: 0x05f45c27ab6c50129160410cefc2ae62d1f9e2d3
T+328763ms:   Gas usage: 956279
T+328763ms:   Block Number: 48
T+328763ms:   Block Time: Wed Oct 21 2020 12:00:13 GMT-0500 (Central Daylight Time)
T+328763ms: eth_getTransactionReceipt
T+328763ms: eth_getCode
T+328763ms: eth_getBalance
T+328763ms: eth_getBlockByNumber
T+328763ms: eth_sendTransaction
T+328763ms:   Transaction: 0x27d086ec10b0d562057fb5faeaebd6a71e78805bf5387fa31c696f0d43288878
T+328763ms:   Gas usage: 19507
T+328763ms:   Block Number: 49
T+328763ms:   Block Time: Wed Oct 21 2020 12:00:13 GMT-0500 (Central Daylight Time)
T+328763ms: eth_getTransactionReceipt
T+328763ms: eth_getBalance
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:16
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1770

**Closed by davidmurdoch** 2020-10-28 18:16 UTC
