### ISSUE TITLE
Blockchain process exited prematurely with code '7', due to signal 'null'.

### ISSUE THREAD

**Issue by chebykin** [trufflesuite/ganache#265] opened 2018-01-12 17:14 UTC
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+120989ms:   Block Time: Fri Jan 12 2018 20:10:23 GMT+0300 (MSK)
T+120994ms: eth_getTransactionReceipt
T+120998ms: eth_call
T+121018ms: eth_blockNumber
T+121022ms: eth_sendTransaction
T+121053ms:   Transaction: 0x917f343521beda431ddea5dbdf8af3f97515cd5e46ae4199fd71679a185b86b8
T+121053ms:   Contract created: 0x25cbab0c13650026c7bcbcce7ef963c303b68cd6
T+121053ms:   Gas usage: 1755968
T+121053ms:   Block Number: 111
T+121057ms:   Block Time: Fri Jan 12 2018 20:10:23 GMT+0300 (MSK)
T+121060ms: eth_newBlockFilter
T+121063ms: eth_getFilterChanges
T+121066ms: eth_getTransactionReceipt
T+121073ms: eth_getCode
T+121079ms: eth_uninstallFilter
T+121083ms: eth_gasPrice
T+121086ms: eth_sendTransaction
T+121120ms:   Transaction: 0x9eefe2455c898a614c8233f0d75841b117089e84b469c9ac2e7ba1f1e98f256a
T+121120ms:   Gas usage: 86257
T+121120ms:   Block Number: 112
T+121124ms:   Block Time: Fri Jan 12 2018 20:10:23 GMT+0300 (MSK)
T+121128ms: eth_getTransactionReceipt
T+121132ms: eth_gasPrice
T+121138ms: eth_sendTransaction
T+121248ms:   Transaction: 0x273e2258f3f1ba3f393c879193c5d18df3ae35eed13c719f0be0b8428167b2e6
T+121248ms:   Gas usage: 71257
T+121248ms:   Block Number: 113
T+121251ms:   Block Time: Fri Jan 12 2018 20:10:23 GMT+0300 (MSK)
T+121260ms: eth_getTransactionReceipt
T+121265ms: eth_gasPrice
T+121271ms: eth_sendTransaction
T+121320ms:   Transaction: 0xeee128db4780b34acf97188a97a5f50fbf79764e76a48046db46654fb753619c
T+121320ms:   Gas usage: 71257
T+121320ms:   Block Number: 114
T+121325ms:   Block Time: Fri Jan 12 2018 20:10:24 GMT+0300 (MSK)
T+121330ms: eth_getTransactionReceipt
T+121337ms: eth_call
T+121369ms: eth_getLogs
T+121377ms: eth_blockNumber
T+121381ms: eth_sendTransaction
T+121414ms:   Transaction: 0xc751f3d83713d457ebda8e0c615c9cbb4a51135ceb3d769ed535d0b6a6f8c327
T+121414ms:   Contract created: 0xf57f76d23568e31b12f62e7b8eb880f486369bcf
T+121414ms:   Gas usage: 1755968
T+121414ms:   Block Number: 115
T+121418ms:   Block Time: Fri Jan 12 2018 20:10:24 GMT+0300 (MSK)
T+121421ms: eth_newBlockFilter
T+121424ms: eth_getFilterChanges
T+121429ms: eth_getTransactionReceipt
T+121435ms: eth_getCode
T+121444ms: eth_uninstallFilter
T+121452ms: eth_gasPrice
T+121456ms: eth_sendTransaction
T+121497ms:   Transaction: 0x639968c374dfcb8745cfb18d8cfcce4eac06f9c3ed4be680dad875954615205f
T+121497ms:   Gas usage: 86257
T+121497ms:   Block Number: 116
T+121502ms:   Block Time: Fri Jan 12 2018 20:10:24 GMT+0300 (MSK)
T+121509ms: eth_getTransactionReceipt
T+121514ms: eth_gasPrice
T+121522ms: eth_sendTransaction
T+121557ms:   Transaction: 0x1687da49cf565821c1ed266affa10728fb6bce5e790ac97bf3860e678ff1e4cb
T+121557ms:   Gas usage: 71257
T+121557ms:   Block Number: 117
T+121562ms:   Block Time: Fri Jan 12 2018 20:10:24 GMT+0300 (MSK)
T+121568ms: eth_getTransactionReceipt
T+121573ms: eth_gasPrice
T+121579ms: eth_sendTransaction
T+121623ms:   Transaction: 0x1288ca9d3ee695a01a0353159db4dc196c76396fa801fb35a81059eb5ef975fd
T+121623ms:   Gas usage: 71257
T+121623ms:   Block Number: 118
T+121627ms:   Block Time: Fri Jan 12 2018 20:10:24 GMT+0300 (MSK)
T+121633ms: eth_getTransactionReceipt
T+121638ms: eth_call
T+121665ms: eth_call
T+121670ms: eth_gasPrice
T+121676ms: eth_sendTransaction
T+121689ms: evm_revert
T+121887ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+121887ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+121887ms: 
T+121895ms: TypeError: Cannot read property 'toJSON' of null
T+121895ms:     at /node_modules/ganache-cli/build/lib.node.js:80442:24
T+121895ms:     at /node_modules/ganache-cli/build/lib.node.js:21713:5
T+121895ms:     at /node_modules/ganache-cli/build/lib.node.js:78351:7
T+121895ms:     at /node_modules/ganache-cli/build/lib.node.js:7539:16
T+121895ms:     at /node_modules/ganache-cli/build/lib.node.js:7756:32
T+121895ms:     at /node_modules/ganache-cli/build/lib.node.js:7531:16
T+121895ms:     at /node_modules/ganache-cli/build/lib.node.js:78346:9
T+121895ms:     at Object.decode (/node_modules/ganache-cli/build/lib.node.js:47235:5)
T+121895ms:     at /node_modules/ganache-cli/build/lib.node.js:783
T+121902ms: 43:20
T+121902ms:     at /node_modules/ganache-cli/build/lib.node.js:7668:20
```

**Comment by chebykin** [comment] 2018-01-12 17:18
* system node version: v9.1.0
* macOS version: 10.13.2

**Comment by chebykin** [comment] 2018-01-12 17:21
The similar error message on Ubuntu #259

**Comment by cserb** [comment] 2018-01-14 09:29
Same problem here on Arch Linux

**Comment by benjamincburns** [comment] 2018-01-15 04:19
@chebykin & @cserb - thanks for reporting this. We believe this is actually caused by trufflesuite/ganache-cli#417. This has also been reported in trufflesuite/ganache-cli#426 and trufflesuite/ganache-cli#359.

I have a "band-aid" fix PR open for this issue, trufflesuite/ganache-core#53. This doesn't fix the actual underlying problem, but it works around it by processing only one request at a time.

Because of all of the above, I'm closing this as a duplicate. I recommend you subscribe to the above issues/PR to follow progress on this problem.

**Closed by benjamincburns** 2018-01-15 04:19 UTC
