### ISSUE TITLE
System Error when running Ganache 1.0.2 on darwin

### ISSUE THREAD

**Issue by 1975210542** [trufflesuite/ganache#412] opened 2018-03-13 05:54 UTC
PLATFORM: darwin
GANACHE VERSION: 1.0.2

EXCEPTION:
```
Blockchain process exited prematurely due to signal 'SIGKILL'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":999,"port":8545,"total_accounts":10,"unlocked_accounts":[]}
T+117ms: Ganache started successfully!
T+117ms: Waiting for requests...
```

**Comment by seesemichaelj** [comment] 2018-08-03 22:09
It looks like Ganache got killed from a KILL signal. I've tried reproducing this with `v1.2.1` with `sudo pkill -KILL Ganache`, and it was able to handle the `SIGKILL` signal appropriately (by closing rather than showing the modal error).

If you're still having issues, please submit a new issue.

Thanks!

**Closed by seesemichaelj** 2018-08-03 22:09 UTC
