### ISSUE TITLE
Decoding Error when running Ganache 2.4.0 on darwin

### ISSUE THREAD

**Issue by alexroan** [trufflesuite/ganache#1772] opened 2020-05-04 10:47 UTC
Issue decoding contract on Storage section of Contract page.

<img width="1133" alt="Screenshot 2020-05-04 at 11 46 47" src="https://user-images.githubusercontent.com/6523673/80958497-0b0f0f00-8dfd-11ea-898c-ed81eefa0e3c.png">

PLATFORM: darwin
GANACHE VERSION: 2.4.0

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 902$ of contract$ Game (ID 456)
    at /Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:181:13
    at Array.map (<anonymous>)
    at allocateContract (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:178:59)
    at Object.getStorageAllocations (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:23:19)
    at TruffleContractDecoder.<anonymous> (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/interface/contract-decoder.ts:237:39)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/dist/interface/contract-decoder.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by bearDream** [comment] 2020-05-15 14:53
Same as you

**Comment by deniro98** [comment] 2020-10-10 00:02
same

**Comment by davidmurdoch** [comment] 2020-10-28 18:21
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1470

**Closed by davidmurdoch** 2020-10-28 18:21 UTC
