### ISSUE TITLE
Go fails to unmarshall result

### ISSUE THREAD

**Issue by ahmed-arkonsys** [trufflesuite/ganache#1090] opened 2019-01-19 03:40 UTC
I am trying to read the blockchain blocks and transitions to validate contract related transaction data using go-ethereum libraries
## Expected Behavior
The call to `eth_getBlockByNumber` result should return the block with the transactions to be traversed. I guess something is messing around adding a `0x` or some other formatting issue I really don't know the error happend deep inside the Go JSON libs

## Current Behavior
I am getting the following error:
json: cannot unmarshal hex number with leading zero digits into Go value of type *hexutil.Big

## Steps to Reproduce (for bugs)
1. Create a smart contract
2. Deploy the contract
3. Loop over the blockchain using the code snippet below

## Code being used to traverse the blockchain
```go
	tipHeader, err := ethBlockchainClient.BlockByNumber(context.Background(), nil)
	if err != nil {
		log.Fatalf("Failed to get tip: %v", err)
	}

	log.Printf("Tip: %d", tipHeader.Number().Int64())

	for i := tipHeader.Number().Int64(); i > 0; i-- {
		log.Printf("Block Index: %d", i)

		block, err := ethBlockchainClient.HeaderByNumber(context.Background(), big.NewInt(i))
		if err != nil {
			log.Fatalf(" Failed to fetch block header for block %d : %v", i, err)
		}

		blockHash := block.Hash()
		blockNumber := block.Number

		transactionCount, err := ethBlockchainClient.TransactionCount(context.Background(), blockHash)
		if err != nil {
			log.Fatalf("Failed to get transaction count for block %d: %v", blockNumber.Int64(), err)
		}

		if transactionCount > 0 {
			fullBlock, err := ethBlockchainClient.BlockByNumber(context.Background(), blockNumber)
			if err != nil {
				log.Fatalf("Failed to fetch full block %s", blockNumber.String())
			}

			for transactionIndex, transaction := range fullBlock.Transactions() {
				transactionHex := transaction.Hash().Hex()

				data, err := parser.ParseTxBytesData(transaction.Data())
				if err != nil {
					log.Fatalf("Failed to parse transaction %s data: %v", transactionHex, err)
				}

				log.Printf("%d -> %v @ %s", transactionIndex, data, transactionHex)

			}
		}
	}
}
```
## Your Environment
* Ganache 1.2.3
* Golang 1.11.4.:

* Operating System and version: Mac OS X Mojave

Thanks in advance for the help

**Comment by davidmurdoch** [comment] 2019-01-19 14:48
Thanks @ahmed-arkonsys for reporting this issue. What line in your code fails? Can you provide the stack trace when the error occurs?

**Comment by ahmed-arkonsys** [comment] 2019-01-19 17:46
So I am unable to get any stack trace that makes sense, I can't get it to give me the error location deeper than my code. Long story short, there is also an inconsistency, now that I am debugging the error is actually happening at the point where I get the transaction count

**Comment by ahmed-arkonsys** [comment] 2019-01-20 05:33
Another update, just configured a parity dev node, and everything is working just fine

**Comment by davidmurdoch** [comment] 2019-01-22 16:32
@ahmed-arkonsys Thanks for the additional information. I've copied your example code and ran it again Ganache v1.2.3 with default settings and received the following output:

```
2019/01/22 11:25:17 Tip: 0
2019/01/22 11:25:17 Block Index: 0 (0x0)
2019/01/22 11:25:17 Block Hash: 0xb0f20b308119c7db39c4d9ce25290c1ea6e8865edfd1bc6bfbcc09750949887b
2019/01/22 11:25:17 Block Index: -1 (-0x1)
2019/01/22 11:25:17 Block Hash: 0xb0f20b308119c7db39c4d9ce25290c1ea6e8865edfd1bc6bfbcc09750949887b
```

I'm unable to reproduce the issue. To assist you further I'll need for you to enable `Verbose Logs` in the Ganache settings. Click the `⚙` icon in the top right corner, then click on the `Advanced` tab, then toggle `Verbose Logs` to the On position. After enabling `Verbose Logs`, click the `🔂 Save and Restart` button, then run your Go experimental code, then go to the `Logs` tab of Ganache and copy all the Logs and paste them here. Thanks!

**Comment by ahmed-arkonsys** [comment] 2019-01-24 04:01
Sorry for the delay, the code fails literally on the first `getBlockByNumber` call

```ACCOUNTS
BLOCKS
TRANSACTIONS
LOGS

SEARCH FOR BLOCK NUMBERS OR TX HASHES
CURRENT BLOCK
30
GAS PRICE
20000000000
GAS LIMIT
6721975
NETWORK ID
5777
RPC SERVER
HTTP://127.0.0.1:7545
MINING STATUS
AUTOMINING
CLEAR LOGS
[10:59:32 PM] eth_getBlockByNumber
[10:59:32 PM] eth_getBlockByNumber
[10:59:32 PM]    > {
[10:59:32 PM]    >   "jsonrpc": "2.0",
[10:59:32 PM]    >   "id": 1,
[10:59:32 PM]    >   "method": "eth_getBlockByNumber",
[10:59:32 PM]    >   "params": [
[10:59:32 PM]    >     "latest",
[10:59:32 PM]    >     true
[10:59:32 PM]    >   ]
[10:59:32 PM]    > }
[10:59:32 PM]  <   {
[10:59:32 PM]  <     "id": 1,
[10:59:32 PM]  <     "jsonrpc": "2.0",
[10:59:32 PM]  <     "result": {
[10:59:32 PM]  <       "number": "0x1e",
[10:59:32 PM]  <       "hash": "0xfd54f39c4a98918c214a3a9341f6446f8ad84905da537babc286428a3d18da85",
[10:59:32 PM]  <       "parentHash": "0x56f524d77fbb143173b237cfb61b7b8efc11f0e74b2471782fef1bf6dc66228d",
[10:59:32 PM]  <       "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
[10:59:32 PM]  <       "nonce": "0x0000000000000000",
[10:59:32 PM]  <       "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
[10:59:32 PM]  <       "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
[10:59:32 PM]  <       "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
[10:59:32 PM]  <       "stateRoot": "0x9d5c2c5ed2078d5972590d85987a0bbc96ad84c2ef76fed041666bb4ecc5b2d5",
[10:59:32 PM]  <       "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
[10:59:32 PM]  <       "miner": "0x0000000000000000000000000000000000000000",
[10:59:32 PM]  <       "difficulty": "0x0",
[10:59:32 PM]  <       "totalDifficulty": "0x0",
[10:59:32 PM]  <       "extraData": "0x",
[10:59:32 PM]  <       "size": "0x3e8",
[10:59:32 PM]  <       "gasLimit": "0x6691b7",
[10:59:32 PM]  <       "gasUsed": "0x7e20",
[10:59:32 PM]  <       "timestamp": "0x5c4937d3",
[10:59:32 PM]  <       "transactions": [
[10:59:32 PM]  <         {
[10:59:32 PM]  <           "hash": "0xdce63b5a4b4bba77d1d68c0d2af534e26544c74e44f4d40fc77bbc44d034d346",
[10:59:32 PM]  <           "nonce": "0x1d",
[10:59:32 PM]  <           "blockHash": "0xfd54f39c4a98918c214a3a9341f6446f8ad84905da537babc286428a3d18da85",
[10:59:32 PM]  <           "blockNumber": "0x1e",
[10:59:32 PM]  <           "transactionIndex": "0x0",
[10:59:32 PM]  <           "from": "0x6c725674c22d4d80d17c46789262261bd4ab6ecd",
[10:59:32 PM]  <           "to": "0xfab3a316c52a03228c8fd40903f40297cb66ae7d",
[10:59:32 PM]  <           "value": "0x0",
[10:59:32 PM]  <           "gas": "0x6691b7",
[10:59:32 PM]  <           "gasPrice": "0x4a817c800",
[10:59:32 PM]  <           "input": "0x84bb08fe0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000ed512b6da76601511fe76d4085b2937563903373000000000000000000000000000000000000000000000000000000000000000973747564656e745f350000000000000000000000000000000000000000000000",
[10:59:32 PM]  <           "v": "0x1b",
[10:59:32 PM]  <           "r": "0xe87cf70d602987ff904d055edc69be12cf8a23c1b57e05eacd991d6afbe9cc03",
[10:59:32 PM]  <           "s": "0x42e5a2dcce976ef53d53e8d556cb7a949af8c16b8a79720c7fe3419fd8948f84"
[10:59:32 PM]  <         }
[10:59:32 PM]  <       ],
[10:59:32 PM]  <       "uncles": []
[10:59:32 PM]  <     }
[10:59:32 PM]  <   }```

**Comment by YanB25** [comment] 2019-03-12 15:47
I also encounter this problem.
Here's the versions.
``` 
$ truffle version
Truffle v4.1.8 (core: 4.1.8)
Solidity v0.4.23 (solc-js)
$ ganache-cli version
Ganache CLI v6.4.1 (ganache-core: 2.5.3)
```
I find out that below codes return an error
[The go-ethereum codes](https://github.com/ethereum/go-ethereum/blob/b87a68407bb5beeb0b4d9f074ed08fe21f1dc426/ethclient/ethclient.go#L101-L103)
After a deeper debuging, I print out what `ganache` returns when calling `eth_getBlockByNumber`
I'll paste it below. (Sorry for not displaying in good format)
```
{"number":"0x2c","hash":"0xc35a1d63e8161fa1a0924971a58fb690ebce886f4ac603828ebf4c3d2962e290","parentHash":"0x568540a86589ef3e3ede3f918f31785bc206710260392d538841bc0d52029f83","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000000","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","logsBloom":"0x20000000000000000000000002000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000002000000000000000000000000000010000000000000000080000000000000000000000000000000000000000000000000000000000000002000000002000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000004000000","transactionsRoot":"0x7279b6dc5f5a0db39d82dba089d1e12398ee3ce22f045015961d3e96ff6e4852","stateRoot":"0xc392c46f14703f183d026158034ccf6c98640fe9a1f5b715364b09e8c6599ecc","receiptsRoot":"0x46966b720a1252db43c3e348e1f86df7975fcf47660221d7a5cc408911fc1042","miner":"0x0000000000000000000000000000000000000000","difficulty":"0x0","totalDifficulty":"0x0","extraData":"0x","size":"0x3e8","gasLimit":"0xfffffffffff","gasUsed":"0xdc74","timestamp":"0x5c878539","transactions":[{"hash":"0xb5dfa7e42c63582f8d4f3b1d7192d029088208e70df956f39c7bc96227d9f0db","nonce":"0x2a","blockHash":"0xc35a1d63e8161fa1a0924971a58fb690ebce886f4ac603828ebf4c3d2962e290","blockNumber":"0x2c","transactionIndex":"0x0","from":"0x5c865774723bf00895b3620700998906e58085fe","to":"0xa5c6f21cf4942df4ec6f3be6a4c631937db52099","value":"0x0","gas":"0x186a0","gasPrice":"0x0","input":"0x1a3d5f820000000000000000000000009c4486f5e78a5b6fee55f59ca1f8753b98f3909c","v":"0x1b","r":"0xdbc6cf7b3804d2b1698b00d99bd2e9ca8c155e15513da8d170a556a3f21ae3e9","s":"0x0b8bae10a4716f27cb8eac0454ff55005897741d230d6833436541bd43b7b607"}],"uncles":[]}
```
It seems that the field
```
... "extraData":"0x"
```
is an error. It should be `"extraData":"0x0"`

**Comment by davidmurdoch** [comment] 2019-03-12 20:00
`0x0` is invalid for the `extraData` field as it is a `DATA` type. A `DATA` field should always be encoded as a string of hex _pairs_, or `0x` if the is no data -- and `0` should be encoded as `"0x00"`.

See: https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbyhash and
https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding

**Comment by eshaben** [comment] 2019-03-13 23:07
@ahmed-arkonsys, thanks again for filing this issue! @YanB25, thank you as well for commenting with your findings! It looks like the go-ethereum ethclient is looking for the `r` and `s` fields of the transaction object to be `QUANTITY` types. However, JSON-RPC spec defines these fields to be of type `DATA` (https://github.com/ethereum/wiki/wiki/JSON-RPC#returns-28). So I am going to go ahead and close this issue since their ethclient is encoding those fields incorrectly. 

There has already been an issue filed with go-ethereum in regards to this, which can be seen here: https://github.com/ethereum/go-ethereum/issues/18152. I went ahead and upvoted the issue in hopes of it getting fixed sooner than later!

**Closed by eshaben** 2019-03-13 23:07 UTC
Labels: priority-medium
