### ISSUE TITLE
System Error when running Ganache 1.0.0 on win32

### ISSUE THREAD

**Issue by flexo45** [trufflesuite/ganache#100] opened 2017-11-17 07:06 UTC
Left working app for the night. In the morning. In the morning I came, and I see an error. At night, there were no transactions. Mining was launched.

PLATFORM: win32
GANACHE VERSION: 1.0.0

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by benjamincburns** [comment] 2017-11-30 22:17
Closing this as duplicate of #83.  Will comment on that case shortly.

**Closed by benjamincburns** 2017-11-30 22:17 UTC
Labels: duplicate
