### ISSUE TITLE
System Error when running Ganache 2.1.2 on linux

### ISSUE THREAD

**Issue by nshCore** [trufflesuite/ganache#1495] opened 2019-11-25 12:29 UTC
PLATFORM: linux
GANACHE VERSION: 2.1.2

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 465$ of contract$ HeavenTicket (ID 381)
    at vars.concat.linearizedBaseContractsFromBase.map (/node_modules/truffle-decoder/dist/allocate/storage.js:164:19)
    at Array.map (native)
    at allocateContract (/node_modules/truffle-decoder/dist/allocate/storage.js:161:61)
    at Object.getStorageAllocations (/node_modules/truffle-decoder/dist/allocate/storage.js:29:23)
    at TruffleContractDecoder.<anonymous> (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:117:47)
    at Generator.next (<anonymous>)
    at fulfilled (/node_modules/truffle-decoder/dist/interface/contract-decoder.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+4654948ms: eth_getLogs
T+4654986ms: eth_getTransactionReceipt
T+4655025ms: eth_getBalance
T+4655072ms: eth_getBalance
T+4655110ms: eth_getBlockByNumber
T+4655148ms: eth_getTransactionCount
T+4655186ms: eth_call
T+4655224ms: eth_call
T+4655271ms: eth_call
T+4655309ms: eth_call
T+4655347ms: eth_call
T+4655385ms: eth_call
T+4655683ms: eth_call
T+4655720ms: eth_call
T+4657595ms: eth_blockNumber
T+4660709ms: net_version
T+4660866ms: eth_call
T+4670045ms: eth_blockNumber
T+4670084ms: eth_blockNumber
T+4677614ms: eth_blockNumber
T+4690063ms: eth_blockNumber
T+4690103ms: eth_blockNumber
T+4697631ms: eth_blockNumber
T+4710081ms: eth_blockNumber
T+4710147ms: eth_blockNumber
T+4717647ms: eth_blockNumber
T+4730098ms: eth_blockNumber
T+4730154ms: eth_blockNumber
T+4737662ms: eth_blockNumber
T+4750105ms: eth_blockNumber
T+4750160ms: eth_blockNumber
T+4757679ms: eth_blockNumber
T+4770123ms: eth_blockNumber
T+4770177ms: eth_blockNumber
T+4777695ms: eth_blockNumber
T+4790142ms: eth_blockNumber
T+4790196ms: eth_blockNumber
T+4797702ms: eth_blockNumber
T+4810160ms: eth_blockNumber
T+4810219ms: eth_blockNumber
T+4817719ms: eth_blockNumber
T+4830176ms: eth_blockNumber
T+4830229ms: eth_blockNumber
T+4837736ms: eth_blockNumber
T+4850193ms: eth_blockNumber
T+4850248ms: eth_blockNumber
T+4857753ms: eth_blockNumber
T+4865666ms: eth_blockNumber
T+4870211ms: eth_blockNumber
T+4870262ms: eth_blockNumber
T+4877760ms: eth_blockNumber
T+4884468ms: net_version
T+4890219ms: eth_blockNumber
T+4890271ms: eth_blockNumber
T+4896828ms: eth_call
T+4896894ms: eth_call
T+4897767ms: eth_blockNumber
T+4900008ms: eth_call
T+4902958ms: eth_call
T+4903011ms: eth_call
T+4906522ms: eth_gasPrice
T+4906583ms: eth_getCode
T+4906659ms: eth_estimateGas
T+4910236ms: eth_blockNumber
T+4910292ms: eth_blockNumber
T+4912620ms: eth_estimateGas
T+4917781ms: eth_blockNumber
T+4918578ms: eth_sendRawTransaction
T+4919596ms:   Transaction: 0x305233b8cd9c6075902c78032e9a3a647d3d170968f3bb456d84c4e45aef4ff5
T+4919596ms:   Gas usage: 6385876
T+4919596ms:   Block Number: 22
T+4919596ms:   Block Time: Mon Nov 25 2019 12:28:33 GMT+0000 (GMT)
T+4919596ms:   Runtime Error: invalid opcode
T+4919637ms: eth_getBlockByNumber
T+4919907ms: eth_sendRawTransaction
T+4925344ms: net_version
T+4925511ms: eth_call
T+4927575ms: eth_estimateGas
T+4930088ms: eth_estimateGas
T+4930243ms: eth_blockNumber
T+4930278ms: eth_blockNumber
T+4930311ms: eth_getBlockByNumber
T+4930350ms: eth_getLogs
T+4930386ms: eth_getLogs
T+4930424ms: eth_getLogs
T+4930463ms: eth_getBalance
T+4930524ms: eth_getBalance
T+4930599ms: eth_getBlockByNumber
T+4930631ms: eth_call
T+4930664ms: eth_call
T+4930698ms: eth_call
T+4930737ms: eth_getTransactionCount
T+4930771ms: eth_call
T+4930803ms: eth_call
T+4930837ms: eth_call
T+4930900ms: eth_call
T+4930971ms: eth_call
T+4933428ms: eth_sendRawTransaction
T+4934306ms:   Transaction: 0x8c5653385b1085bbea9ae0d0de519c32c89d82459e3787db7fc3d28d9243409d
T+4934306ms:   Gas usage: 6385876
T+4934306ms:   Block Number: 23
T+4934306ms:   Block Time: Mon Nov 25 2019 12:28:48 GMT+0000 (GMT)
T+4934306ms:   Runtime Error: invalid opcode
T+4934339ms: eth_getBlockByNumber
T+4935710ms: eth_sendRawTransaction
T+4937788ms: eth_blockNumber
T+4937829ms: eth_getBlockByNumber
T+4937864ms: eth_getLogs
T+4937897ms: eth_getLogs
T+4937932ms: eth_getLogs
T+4937970ms: eth_getBalance
T+4938017ms: eth_getBalance
T+4938054ms: eth_getBlockByNumber
T+4938088ms: eth_call
T+4938127ms: eth_call
T+4938162ms: eth_call
T+4938207ms: eth_call
T+4938268ms: eth_call
T+4938339ms: eth_call
T+4938406ms: eth_call
T+4938484ms: eth_call
T+4938835ms: eth_gasPrice
T+4938893ms: eth_getCode
T+4938971ms: eth_estimateGas
T+4939284ms: eth_getTransactionCount
T+4942434ms: eth_sendRawTransaction
T+4943265ms:   Transaction: 0x6bac35eebeb2941fd4133918f32f55a32da46ae258fcdaff2f97f9d1f57f6bc9
T+4943265ms:   Gas usage: 6385876
T+4943265ms:   Block Number: 24
T+4943298ms:   Block Time: Mon Nov 25 2019 12:28:57 GMT+0000 (GMT)
T+4943298ms:   Runtime Error: invalid opcode
T+4943331ms: eth_getBlockByNumber
T+4950263ms: eth_blockNumber
T+4950304ms: eth_blockNumber
T+4950341ms: eth_getBlockByNumber
T+4950386ms: eth_getLogs
T+4950425ms: eth_getLogs
T+4950464ms: eth_getLogs
T+4950506ms: eth_getBalance
T+4950542ms: eth_getBalance
T+4950589ms: eth_getBlockByNumber
T+4950626ms: eth_call
T+4950660ms: eth_call
T+4950700ms: eth_call
T+4950755ms: eth_call
T+4950819ms: eth_call
T+4950913ms: eth_call
T+4950981ms: eth_call
T+4951052ms: eth_call
T+4957797ms: eth_blockNumber
T+4967338ms: net_version
T+4967373ms: eth_unsubscribe
T+4967441ms: eth_unsubscribe
T+4967476ms: eth_unsubscribe
T+4967521ms: eth_unsubscribe
T+4967556ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment] 2020-10-28 18:21
closing as duplicate of https://github.com/trufflesuite/ganache/issues/1470

**Closed by davidmurdoch** 2020-10-28 18:21 UTC
